--- Gacha_Details_List01_PC_C
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by A.
--- DateTime: 2023/6/14 14:53
---

require "UnLua"

local G = Class("BluePrints.UI.BP_EMUserWidget_C")

function G:OnListItemObjectSet(Obj)
    self.Obj = Obj
    --self.Obj.SelfWidget = self
    self.Image_Line:SetVisibility(UE4.ESlateVisibility.Collapsed)
    if Obj.GachaDes then
        self.Text_Desc:SetText(Obj.GachaDes)
    end
end

return G