---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lijinyi.
--- DateTime: 2023/6/13 14:31
---
require "UnLua"

local BP_DSAssetsManager_C = Class()

function BP_DSAssetsManager_C:Initialize(Initializer)
end

function BP_DSAssetsManager_C:PreLoadAssets_Lua()
    -- 预加载配置表
    self:PreLoadData()
    -- 预加载地图资源
    self:PreLoadMapAssets()
    -- 角色和怪物资源预加载
    self:PreLoadCharacterAssets()
    -- 怪物额外资源
    self:PreLoadMonsterAssets()
    -- 魅影额外资源
    self:PreLoadPhantomAssets()
    -- 被动效果
    self:PreLoadPassiveEffectsAssets()
    -- 技能创生物
    self:PreLoadSkillCreature()
    -- Buff
    self:PreLoadBuff()
    -- Base蓝图
    self:PreLoadBP()
    -- Behaviour Montage
    self:PreLoadBehaviorMontage()
end

function BP_DSAssetsManager_C:PreLoadData()
    print("BP_DSAssetsManager_C", "PreLoadData")
    DataMgr.PreLoad()
end

function BP_DSAssetsManager_C:PreLoadMapAssets()
    print("BP_DSAssetsManager_C", "PreLoadMapAssets")
    for DungeonId, Info in pairs(DataMgr.Dungeon) do
        if Info.IsMultiDungeon then
            self:AddDungeonMapAssets(DungeonId)
        end
    end
end

function BP_DSAssetsManager_C:AddDungeonMapAssets(DungeonId)
    local Info = DataMgr.Dungeon[DungeonId]
    -- 拼接关卡地图
    if not Info.DungeonJsonFile then
        return
    end

    -- 解析字符串，GameInstance
    local DungeonJsonFile = Info.DungeonJsonFile
    local Files = UE4.URuntimeCommonFunctionLibrary.GetAllFileNamesInDic(DungeonJsonFile)
    for i=1, Files:Length() do
        local File = Files:GetRef(i)
        local PathPart, FilenamePart = UE4.UBlueprintPathsLibrary.Split(File)
        local LeftS, RightS = UE4.UKismetStringLibrary.Split(PathPart, "Houdini_data/")
        local FileName = RightS.."/"..FilenamePart
        -- 读文件，LevelLoader
        local levelTable=DataMgr.GetLevelLoaderJsonData(FileName)
        local LevelCounts = #levelTable.points
        -- 只加载子关卡，策划关卡，美术关卡和导航网格关卡，音频和白模不加载
        -- todo 打包过滤音频和白模
        for j=1, LevelCounts do
            local Level = levelTable.points[j]
            local homePath=string.gsub(Level.struct,"Datas/Data_Design","Levels")
            local designPath=Level.struct.."_Design"
            local artPath=Level.art_path
            if not artPath or artPath=='' then
                artPath=string.gsub(Level.struct,"Data_Design","Data_Art").."_Art"
            end
            local navPath=string.gsub(Level.struct,"Data_Design","Data_NavMesh").."_NavMesh"

            self:AddUniqueAssets(homePath)
            self:AddUniqueAssets(designPath)
            self:AddUniqueAssets(artPath)
            self:AddUniqueAssets(navPath)
        end
    end
end

function BP_DSAssetsManager_C:PreLoadCharacterAssets()
    -- 预加载CharacterBase
    for _, Info in pairs(DataMgr.BattleChar) do
        local UnitBPPath = Info.UnitBPPath
        if UnitBPPath then
            self:AddUniqueAssets(UnitBPPath, true)
        end
    end

    -- 预加载角色引用资产
    for _, Info in pairs(DataMgr.Model) do
        self:PreLoadModelAssets(Info)
    end

    -- Common DistructableBody
    self:AddUniqueAssets(Const.CharResourcePaths.DistructableBodyBp, true)
    -- for _, Info in pairs(DataMgr.DistructableBody) do
    --     self:PreLoadDistructableBodyAssets(Info)
    -- end

    for _, Info in pairs(DataMgr.BattleWeapon) do
        self:PreLoadWeaponAssets(Info)
    end

    self:AddUniqueAssets(Const.CharResourcePaths.AccessoryBP, true)
    for _, Info in pairs(DataMgr.BodyAccessory) do
        self:PreLoadBodyAccessoryAssets(Info)
    end
end

function BP_DSAssetsManager_C:PreLoadModelAssets(Info)
    -- 披风 CloakMesh
    if Info.CloakMeshPath then
        local CloakPath = '/Game/'..Info.CloakMeshPath
        self:AddUniqueAssets(CloakPath)
    end

    -- 骨骼 SkeletonMesh
    if Info.SkeletonMeshPath then
        local SkeletonPath = '/Game/'..Info.SkeletonMeshPath
        self:AddUniqueAssets(SkeletonPath)
    end

    -- 动画蓝图 AnimInstancePath
    if Info.AnimInstancePath then
        self:AddUniqueAssets(Info.AnimInstancePath, true)
    end

    -- 蒙太奇 Montage
    if Info.MontageFolder then
        self:PreLoadMontageAssets(Info.MontageFolder)
    end
end

function BP_DSAssetsManager_C:PreLoadDistructableBodyAssets(Info)
    for _, PartMesh in pairs(Info.PartMesh) do
        self:AddUniqueAssets(PartMesh)
    end
end

function BP_DSAssetsManager_C:PreLoadWeaponAssets(Info)
    -- 武器蓝图 WeaponBlueprint
    if Info.WeaponBlueprint then
        self:AddUniqueAssets(Info.WeaponBlueprint, true)
    end
end

function BP_DSAssetsManager_C:PreLoadBodyAccessoryAssets(Info)
    -- 配饰 ModelPath
    if Info.ModelPath then
        self:AddUniqueAssets(Info.ModelPath)
    end
end

--- 跟游戏中的引用计算不同，这里图省事直接将目标目录下的所有蒙太奇全部加入缓存
--- 理论上只要没有弃用蒙太奇资源，效果是一样的
function BP_DSAssetsManager_C:PreLoadMontageAssets(MontageFolder)
    self:AddAllMontagesFromDic(self:GetAllMontageDic(MontageFolder))
end

function BP_DSAssetsManager_C:AddAllMontagesFromDic(Dic)
    for _, d in ipairs(Dic) do
        local Files = UE4.URuntimeCommonFunctionLibrary.GetAllFileNamesInDic(d)
        if Files then
            for i=1, Files:Length() do
                local File = Files:GetRef(i)
                local PathPart, FilenamePart = UE4.UBlueprintPathsLibrary.Split(File)
                local LeftS, RightS = UE4.UKismetStringLibrary.Split(PathPart, "Content/")
                local FileName = "/Game/"..RightS.."/"..FilenamePart
                self:AddUniqueAssets(FileName)
            end
        end
    end
end

function BP_DSAssetsManager_C:GetAllMontageDic(MontageFolder)
    local Result = {}
    for Weapon, _ in pairs(CommonConst.WeaponTypes) do
        table.insert(Result, MontageFolder.. "Combat/Weapon/".. Weapon.. "/")
    end

    table.insert(Result, MontageFolder.. "Locomotion/") -- RotationMontage PivotMontage ClimbMontage都在这个目录
    table.insert(Result, MontageFolder.. "Combat/Hit/") -- HitMontage
    table.insert(Result, MontageFolder.. "Combat/Skill/") -- SkillMontage
    table.insert(Result, MontageFolder.. "Armory/") -- ArmoryMontage
    table.insert(Result, MontageFolder.. "Interactive/") -- InteractiveMontage
    return Result
end

function BP_DSAssetsManager_C:PreLoadMonsterAssets()
    -- 怪物的CharacterBase和BT
    for _, Info in pairs(DataMgr.Monster) do
        local UnitBPPath = Info.UnitBPPath
        if UnitBPPath then
            self:AddUniqueAssets(UnitBPPath, true)
        end

        local BT = Info.BT
        if BT then
            self:AddUniqueAssets(BT)
        end
    end
end

function BP_DSAssetsManager_C:PreLoadPhantomAssets()
    -- 魅影BP和BT
    for _, Info in pairs(DataMgr.Phantom) do
        local UnitBPPath = Info.UnitBPPath
        if UnitBPPath then
            self:AddUniqueAssets(UnitBPPath, true)
        end

        local BT = Info.BT
        if BT then
            for _, bt in ipairs(BT) do
                self:AddUniqueAssets(bt)
            end
        end
    end
end

function BP_DSAssetsManager_C:PreLoadPassiveEffectsAssets()
    -- 被动效果
    for _, Info in pairs(DataMgr.PassiveEffect) do
        local BPPath = Info.BPPath
        if BPPath then
            self:AddUniqueAssets(BPPath, true)
        end
    end
end

function BP_DSAssetsManager_C:PreLoadSkillCreature()
    -- 技能创生物
    for _, Info in pairs(DataMgr.SkillCreature) do
        local BPPath = Info.BPPath
        if BPPath then
            self:AddUniqueAssets(BPPath, true)
        end
    end
end

function BP_DSAssetsManager_C:PreLoadBuff()
    -- Buff
    for _, Info in pairs(DataMgr.Buff) do
        local BPPath = Info.BPPath
        if BPPath then
            self:AddUniqueAssets(BPPath, true)
        end
    end
end

function BP_DSAssetsManager_C:PreLoadBP()
    -- 把联机可能用到的蓝图都预加载
    -- AI
    self:PreLoadBPByFolder("AI")

    --AnimNotifiers
    self:PreLoadBPByFolder("AnimNotifiers")

    --Camera
    self:PreLoadBPByFolder("Camera")

    --Char
    self:PreLoadBPByFolder("Char")

    --Combat
    self:PreLoadBPByFolder("Combat")

    --Common
    self:PreLoadBPByFolder("Common")

    --Item
    self:PreLoadBPByFolder("Item")

    --Map
    self:PreLoadBPByFolder("Map")
end

function BP_DSAssetsManager_C:PreLoadBPByFolder(Folder)
    -- Combat文件夹下的所有蓝图
    local Files = UE4.URuntimeCommonFunctionLibrary.GetAllFilePathsInDic(string.format("/Game/BluePrints/%s/", Folder), "BP_*")
    if Files then
        for i=1, Files:Length() do
            local File = Files:GetRef(i)
            local PathPart, FilenamePart = UE4.UBlueprintPathsLibrary.Split(File)
            local LeftS, RightS = UE4.UKismetStringLibrary.Split(PathPart, "Content/")
            local FileName = "/Game/"..RightS.."/"..FilenamePart
            self:AddUniqueAssets(FileName, true)
        end
    end
end

function BP_DSAssetsManager_C:PreLoadBehaviorMontage()
    for _, Info in pairs(DataMgr.BehaviorMontage) do
        self:AddUniqueAssets(Info.MontagePath)
    end
end

return BP_DSAssetsManager_C
