---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lijinyi.
--- DateTime: 2024/2/19 11:00
---

require "UnLua"

local BP_NetworkManager_C = Class()

local CONFIRM_RECONNECT = 100074

function BP_NetworkManager_C:Initialize(Initializer)
    print(_G.LogTag, "BP_NetworkManager_C:Initialize")
end

function BP_NetworkManager_C:LogoutEvent()
    ---@type USentrySubsystem
    local EMSentrySubsystem = USubsystemBlueprintLibrary.GetGameInstanceSubsystem(GWorld.GameInstance, UEMSentrySubsystem)
    if EMSentrySubsystem then
        EMSentrySubsystem:Logout()
    end
    ---@type UNewBdcSubsystem
    local BDCSubsystem = USubsystemBlueprintLibrary.GetGameInstanceSubsystem(GWorld.GameInstance, UNewBdcSubsystem)
    if BDCSubsystem then
        BDCSubsystem:Logout()
    end

    ---@type UACESubsystem
    local ACESubsystem = USubsystemBlueprintLibrary.GetGameInstanceSubsystem(GWorld.GameInstance, UACESubsystem)
    if ACESubsystem then
        ACESubsystem:Logout()
    end
    
    -- 清理按键记录
    if GWorld.GameInstance and GWorld.GameInstance.ClearKeyListRecord then
        GWorld.GameInstance:ClearKeyListRecord()
    end
end

-- @SnowMoon 客户端彻底断开连接，并弹出UI提示，退出到登录界面
function BP_NetworkManager_C:DisconnectAndShowUI(info)
    local Uid = "Error"
    local Avatar = GWorld:GetAvatar()
    if Avatar then
        Uid = Avatar.Uid
    end
    if Uid == "Error" and info and type(info) == "table" and info.Uid then
        Uid = info.Uid
    end

    self:Disconnect()
    self:LogoutEvent()

    info = info or {}
    PrintTable(info,2)
    local BanReason = info.Reason
    local BanTime = info.BanTime
    local RetCode = info.RetCode or info.ErrorCode

    if RetCode == CommonConst.KickAvatarType.KICK_AVATAR_FORCE_PATCH then
        -- 强制patch 被踢下线
        DebugPrint("强制patch 被踢下线")
        local Params =
        {
            LeftCallbackObj = self,
            LeftCallbackFunction = self.TryToGoToLoginScene,
            RightCallbackObj = self,
            RightCallbackFunction = self.TryToGoToLoginScene,
        }
        UIManager(self):ShowDisconnectUIConfirm(100151, true, Params)
        return
    elseif RetCode == CommonConst.KickAvatarType.KICK_AVATAR_BAN 
        or RetCode == ErrorCode.RET_LOGIN_BY_LIMIT_AVATAR then -- 游戏中封号被踢下线 or 登陆弹出封禁提示
        local GetEnumBanReason = function(BanReason)
            BanReason = tostring(BanReason)
            if BanReason == "1" then
                return GText("UI_COMMONPOP_TEXT_100052_1")
            elseif BanReason == "2" then
                return GText("UI_COMMONPOP_TEXT_100052_2")
            elseif BanReason == "3" then
                return GText("UI_COMMONPOP_TEXT_100052_3")
            elseif BanReason == "4" then
                return GText("UI_COMMONPOP_TEXT_100052_4")  
            end
            return GText("UI_COMMONPOP_TEXT_100052_0")
        end
        local EnumBanReason = GetEnumBanReason(BanReason)
        local ShortText = string.format(GText("UI_COMMONPOP_TEXT_100052"), tonumber(Uid) or 0, EnumBanReason, os.date("%Y-%m-%d %H:%M:%S", BanTime))
        local Params =
        {
            ShortText = ShortText,
            LeftCallbackObj = self,
            LeftCallbackFunction = self.TryToGoToLoginScene,
            RightCallbackObj = self,
            RightCallbackFunction = self.TryToGoToLoginScene,
        }
        UIManager(self):ShowDisconnectUIConfirm(100051, true, Params)
        return
    end
    DebugPrint("lgc@BP_NetworkManager_C:DisconnectAndShowUI RetCode = " .. tostring(RetCode).." BanReason = " .. tostring(BanReason).." BanTime = " .. os.date("%Y-%m-%d %H:%M:%S", BanTime))

    if BanReason == "RelayAvatar" then
        -- OnKickAvatar
        local Params =
        {
            LeftCallbackObj = self,
            LeftCallbackFunction = self.TryToGoToLoginScene,
            RightCallbackObj = self,
            RightCallbackFunction = self.TryToGoToLoginScene,
            ShortText = string.format(GText("UI_COMMONPOP_TEXT_100073"), tonumber(Uid) or 0)
        }
        UIManager(self):ShowDisconnectUIConfirm(100073, true, Params)
    elseif not BanTime or not BanReason then
        self:EndReConnect(false)
        if not GWorld.bLoginConnectFailed then
            EventManager:FireEvent(EventID.OnNetDisconnect)
            self:ShowNetDisconnectUIConfirm(RetCode, info.NecessoryPatch)
        end
    else
        -- LoginResult
        local UIManager = GWorld.GameInstance:GetGameUIManager()
        local SystemLanguage = "CN"
        for k, v in pairs(CommonConst.SystemLanguages) do
            if CommonConst.SystemLanguage == v then
                SystemLanguage = k
                break
            end
        end
        if SystemLanguage == "Default" then
            SystemLanguage = "CN"
        end
        local ShortText = ""
        if info.ErrorCode == ErrorCode.RET_LOGIN_BY_LIMIT_IP then 
            ShortText = string.format(GText("UI_Forbidden_IP"), os.date("%Y-%m-%d %H:%M:%S", BanTime))
        elseif info.ErrorCode == ErrorCode.RET_LOGIN_BY_LIMIT_DEVICE then 
            ShortText = string.format(GText("UI_Forbidden_Equipment"), os.date("%Y-%m-%d %H:%M:%S", BanTime))
        else
            ShortText = string.format(GText("UI_COMMONPOP_TEXT_100051"), tonumber(Uid) or 0, os.date("%Y-%m-%d %H:%M:%S", BanTime))
        end
        local Params =
        {
            ShortText = ShortText,
            LeftCallbackObj = self,
            LeftCallbackFunction = self.TryToGoToLoginScene,
            RightCallbackObj = self,
            RightCallbackFunction = self.TryToGoToLoginScene,
        }
        UIManager:ShowDisconnectUIConfirm(100051, true, Params)

        -- @SnowMoon 单机断线暂停游戏逻辑
        if IsStandAlone(GWorld.GameInstance) then
            local GameMode = GWorld.GameInstance:GetCurrentGameMode()
            if not GameMode then
                return
            end
            if GameMode.SetGamePaused then
                GameMode:SetGamePaused(Const.NetWorkFailure_Tag, true)
            end
        end
    end
end

-- @SnowMoon 客户端断开连接，并返回登录界面，不显示弹窗
function BP_NetworkManager_C:DisconnectAndReturnLogin(ExtraParams)
    local bHasNecessoryPatch = false
    if ExtraParams and ExtraParams.Necessorypatch and #ExtraParams.Necessorypatch > 0 then
        local HotUpdateUtils = require("Utils.HotUpdateUtils")
        HotUpdateUtils.MergeNecessoryPatchSigns(ExtraParams.Necessorypatch)
        bHasNecessoryPatch = true
    end
    self:Disconnect()
    self:TryToGoToLoginScene(nil, nil, bHasNecessoryPatch)
    self:LogoutEvent()
    
end

-- @lyz 前两个参数容易被对话框带过来，占位把
function BP_NetworkManager_C:TryToGoToLoginScene(_, _, bHasNecessoryPatch)
    -- if HeroUSDKSubsystem():IsHeroSDKEnable() then
    -- 	HeroUSDKSubsystem():HeroSDKLogout()
    -- else
    -- 	local SceneManager = GWorld.GameInstance:GetSceneManager()
    -- 	if (SceneManager ~= nil) then
    -- 		SceneManager:ChangeSceneByAssetPath(Const.DefaultLoginSceneFile)
    -- 	end
    -- end
    -- local SceneManager = GWorld.GameInstance:GetSceneManager()
    -- if (SceneManager ~= nil) then
    -- 	SceneManager:ChangeSceneByAssetPath(Const.DefaultLoginSceneFile)
    -- end
    ---断线退出到登录界面需要清理副本自动打开数据
    GWorld.GameInstance:ClearExitDungeonData()
    self:EndReConnect(false)
    HeroUSDKSubsystem():TryToGoToLoginScene(nil, nil, bHasNecessoryPatch)
end

function BP_NetworkManager_C:SendResolutionTrack()

    local NewTrack = {}
    local SceneManager = GWorld.GameInstance:GetSceneManager()
    local size = SceneManager:GetWindowSize()
    local NowInterfaceMode = UE4.UGameUserSettings:GetGameUserSettings():GetFullscreenMode()
    local ModeStr = {
        [EWindowMode.Fullscreen] = "全屏",
        [EWindowMode.WindowedFullscreen] = "无边框窗口化",
        [EWindowMode.Windowed] = "窗口化"
    }
    local str = string.format("%dx%d", size.X, size.Y)
    NewTrack.display_mode = ModeStr[NowInterfaceMode]
    NewTrack.display_resolution = str
    HeroUSDKSubsystem(self):UploadTrackLog_Lua("display_settings", NewTrack)
end

function BP_NetworkManager_C:OnDisconnectAndLoginAgain()
    self:SendResolutionTrack()
    self:Disconnect()
    local bHasLogOut = (HeroUSDKSubsystem().UserInfo.sdkUserId == "")
    if HeroUSDKSubsystem():IsHeroSDKEnable() and not bHasLogOut then
        if not UUCloudGameInstanceSubsystem.IsCloudGame() then
            HeroUSDKSubsystem():CleanUpUserInfo()
            if HeroUSDKSubsystem():IsBilibili() then
                HeroUSDKSubsystem():HeroSDKLogout()
            end
        end

    end

    self:LogoutEvent()
    -- 	local SceneManager = GWorld.GameInstance:GetSceneManager()
    -- 	if (SceneManager ~= nil) then
    -- 		SceneManager:ChangeSceneByAssetPath(Const.DefaultLoginSceneFile)
    -- 	end
    -- end

    WorldTravelSubsystem():ChangeSceneByAssetPath(Const.DefaultLoginSceneFile)
end

function BP_NetworkManager_C:OnJumpToOptionalPatchDownload()
	local HotUpdateUtils = require("Utils.HotUpdateUtils")
	local HotUpdateSubsystem = USubsystemBlueprintLibrary.GetGameInstanceSubsystem(GWorld.GameInstance, UHotUpdateSubsystem)
	local NecessoryPatchSigns = HotUpdateUtils.GetNecessoryPatchSigns()
	HotUpdateSubsystem:JumpToOptionalDownloadLevel("OptionPatch", NecessoryPatchSigns)
end

function BP_NetworkManager_C:ShowNetDisconnectUIConfirm(RetCode, NecessoryPatch)
    DebugPrint("lgc@BP_NetworkManager_C:ShowNetDisconnectUIConfirm RetCode", tostring(RetCode), NecessoryPatch)
    local IsStopGame = true
    if (GWorld.GameInstance:GetLoadingUI()) then
        IsStopGame = false
        -- 并且把鼠标显示出来
        if (CommonUtils.GetDeviceTypeByPlatformName(GWorld.GameInstance) == "PC") then
            local GameInputSubsystem = UGameInputModeSubsystem.GetGameInputModeSubsystem(GWorld.GameInstance)
            GameInputSubsystem:SetMouseCursorVisable(true)
        end
    else
        if UGameplayStatics.GetCurrentLevelName(self) == "Login" then
            return
        end
    end
    local UIManager = GWorld.GameInstance:GetGameUIManager()
    if UIManager then
        local Params =
        {
            LeftCallbackObj = self,
            LeftCallbackFunction = self.TryToGoToLoginScene,
            RightCallbackObj = self,
            RightCallbackFunction = self.TryToGoToLoginScene,
        }
        if RetCode == CommonConst.KickAvatarType.KICK_AVATAR_CHECK_SCRIPT then
            Params.ShortText = GText("UI_COMMONPOP_TEXT_100078")
        elseif NecessoryPatch and type(NecessoryPatch) == "table" and #NecessoryPatch > 0 then
            local HotUpdateUtils = require("Utils.HotUpdateUtils")
            HotUpdateUtils.MergeNecessoryPatchSigns(NecessoryPatch)
            Params.ShortText = GText("UI_Patch_Logout")
            Params.LeftCallbackFunction = self.OnJumpToOptionalPatchDownload
            Params.RightCallbackFunction = self.OnJumpToOptionalPatchDownload
        else
            Params.ShortText = GText("UI_COMMONPOP_TEXT_100074")
        end
        UIManager:ShowDisconnectUIConfirm(CONFIRM_RECONNECT, IsStopGame, Params)
    end
end

function BP_NetworkManager_C:UpdateNetDisconnectUIConfirm()
    local UIManager = GWorld.GameInstance:GetGameUIManager()
    local NetDisConnectedDialogUI = UIManager:GetUIObj("NetDisConnectedDialog")
    if (NetDisConnectedDialogUI == nil) then
        return
    end
    -- 掉线弹窗已经存在
    if IsStandAlone(GWorld.GameInstance) then
        local GameMode = GWorld.GameInstance:GetCurrentGameMode()
        if not GameMode then
            return
        end
        if GameMode.SetGamePaused then
            GameMode:SetGamePaused(Const.NetWorkFailure_Tag, true)
        end
    end
end

function BP_NetworkManager_C:StartShowReConnectUI()
    if not GWorld.GameInstance:GetLoadingUI() and UGameplayStatics.GetCurrentLevelName(self) == "Login" then
        return
    end
    DebugPrint("NetworkMgr:StartShowReConnectUI")
    local UIManager = GWorld.GameInstance:GetGameUIManager()
	self.bUIReConnecting = true
    if UIManager then
        local ReconnectUI = UIManager:GetUIObj("LoadingReconnect")
        if not ReconnectUI then
            UIManager:LoadUINew("LoadingReconnect")
        end
    end
end

function BP_NetworkManager_C:ConnectSuccess()
    DebugPrint("NetworkMgr:ConnectSuccess")
    self:EndReConnect(true)
end

function BP_NetworkManager_C:EndReConnect(bReConnectSucceed, bHeartbeatCall)
	if not bHeartbeatCall then
		DebugPrint("NetworkMgr:EndReConnect")
	end

	if self.bUIReConnecting then
        -- 不是真正的重连状态
        if self:IsReconnecting() then
            return
        end
        
		self.bUIReConnecting = false
		local UIManager = GWorld.GameInstance:GetGameUIManager()
		if UIManager then
			local UIObj = UIManager:GetUIObj("LoadingReconnect")

			if UIObj then
				if bReConnectSucceed then
					UIObj:Close()
				else
					-- 不触发动画
					UIObj:RealClose()
				end
			end

			local LoginMainPage = UIManager:GetUIObj("LoginMainPage")
			if LoginMainPage then
				LoginMainPage:CloseLoadingReconnect()
			end
		end
	end
end


return BP_NetworkManager_C