---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lijinyi.
--- DateTime: 2024/2/19 15:38
---

require "UnLua"
local RpcRecorder = require "NetworkEngine.Rpc.RpcRecorder"
local table = table

local BP_TcpConnection_C = Class()

function BP_TcpConnection_C:Initialize(Initializer)
end

local function errorHandler(err)
    -- 返回错误信息和堆栈跟踪
    return err .. "\n" .. debug.traceback()
end

function BP_TcpConnection_C:InitSuccessLua()
    _G.NetProxy = function (FuncName, ArgsTable)
        local ok, ret = xpcall(function ()
            local func = self[FuncName]
            if not func then
                error("NetProxy function not found: "..FuncName)
            end

            if ArgsTable then
                func(self, table.unpack(ArgsTable))
            else
                func(self)
            end
        end, errorHandler)

        if not ok then
            DebugPrint(ErrorTag, "NetProxy error:", ret)
        end
    end
end

function BP_TcpConnection_C:CreateEntity(entity_type, entity_id, info, use_protoattr)
    DebugNetPrint("CreateEntity ", entity_type, use_protoattr)
    local entity = GWorld.EntityManager:GetEntity(entity_id)
    if not entity then
        if entity_type == "Avatar" then
			EventManager:CheckIsLeak()
		end
        print(_G.LogTag, "CreateNewEntity", entity_type)
        entity = GWorld.EntityFactory:CreateEntity(entity_type, entity_id)

        if entity then
            entity:SetServerProxy(self)
        end
    end

    if entity then
        DebugPrint("InitFromDict before", os.time())
        entity:InitFromDict(info, use_protoattr)
        DebugPrint("InitFromDict after", os.time())
        entity:CreateSuccess()
    end
end

function BP_TcpConnection_C:DestroyEntity(entity_id)
    DebugNetPrint("DestroyEntity", entity_id)
    local entity = GWorld.EntityManager:GetEntity(entity_id)
    if entity then
        entity:Destroy()
    end
    GWorld.EntityManager:DelEntity(entity_id)
end

function BP_TcpConnection_C:EntityMessage(entity_id, func_name, ...)
    if GWorld.IsForbidEntityMessage then
        return
    end
    local entity = GWorld.EntityManager:GetEntity(entity_id)
    if entity == nil then
        return
    end

    local method = entity[func_name]
    if method == nil then
        return
    end

    -- 处理参数
    local Args = {...}
    Args = RpcUtils.ConvertArgs(Args)

    method(entity, table.unpack(Args))
end

-- endregion

AssembleComponents(BP_TcpConnection_C)
return BP_TcpConnection_C