---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lijinyi.
--- DateTime: 2023/10/10 19:23
---

require "UnLua"
local EMCache = require "EMCache.EMCache"
local msgpack = require "msgpack_core"

local BP_TcpClient_C = Class("BluePrints.Client.BP_TcpConnection_C")

function BP_TcpClient_C:Initialize(Initializer)
    self.Super.Initialize(self)
end

-- @SnowMoon 客户端主动断线，网络连接失败
function BP_TcpClient_C:K2_DisConnect()
    print(_G.LogTag, "K2_Disconnect")
end

-- @SnowMoon 客户端断线重连失败，任何情况下真正断开连接并退出到登录界面
function BP_TcpClient_C:K2_OnDisconnect()
    print(_G.LogTag, "K2_OnDisconnect")
    GWorld.NetworkMgr:DisconnectAndShowUI()
end

-- @SnowMoon 客户端socket关闭
function BP_TcpClient_C:K2_Close()
    print(_G.LogTag, "K2_Close")
end

-- @SnowMoon 客户端开始尝试重连
function BP_TcpClient_C:K2_TryReConnect()
	DebugPrint("BP_TcpClient_C:K2_TryReConnect")
	GWorld.NetworkMgr:StartShowReConnectUI()
end

-- @SnowMoon 客户端任何情况下连接成功
function BP_TcpClient_C:K2_ConnectSuccess()
	DebugPrint("BP_TcpClient_C:K2_ConnectSuccess")
    --保存公共缓存，里面有已登录的用户信息
    EMCache:SaveCommon(false)

    -- 重置Avatar的部分属性
    local Avatar = GWorld:GetAvatar()
    if Avatar then
        Avatar:ResetOnReconnect()
    end
    EventManager:FireEvent(EventID.OnConnectSuccess)
	GWorld.NetworkMgr:ConnectSuccess()

    local UIManager = GWorld.GameInstance:GetGameUIManager()
    if UIManager then
        local LoginMainPage = UIManager:GetUIObj("LoginMainPage")
        if LoginMainPage then
            LoginMainPage:CloseLoadingReconnect(true)
        end
    end
end

function BP_TcpClient_C:DestroyAvatar()
    local Avatar = GWorld:GetAvatar()
    if Avatar then
        --@note Avatar真正消亡了，才代表真的离线了
        self:DestroyEntity(Avatar.Eid)
    end
    GWorld.EntityManager:DelAllEntities()
end

AssembleComponents(BP_TcpClient_C)
return BP_TcpClient_C


