-- 定义一个函数，用于处理访问不存在的键
local function onMissingKey(table, key)
    if skynet then
        skynet.error("警告: 尝试访问不存在的键 '" .. tostring(key) .. "'")
    else
        print(_G.LogTag, "警告: 尝试访问不存在的键 '" .. tostring(key) .. "'")
    end
    return nil
end

local ErrorCode = {

    RET_SUCCESS = 0,
    RET_FAIL = 1,
    ---- 公用
    RET_PARAM_ERROR = 2,  ---------- 参数错误, 请检查RPC调用参数
    RET_UID_NOT_ONLINE = 4,  ---------- UID不在线或不存在
    RET_ASYNC_NEED_WAIT = 5,  ---------- 异步操作需要等待
    RET_UID_NOT_EXIST = 6,  ---------- UID不存在
    RET_CLUSTER_ACCOUNTMGR_NONE = 7,  ---------- 集群中没有AccountMgr
    RET_CLUSTER_REGIONONLINEMGR_NONE = 8,  ---------- 集群中没有RegionOnlineMgr
    RET_DB_TIMEOUT = 9,  ---------- 数据库超时
    RET_CLUSTER_CHATCHANNELMGR_NONE = 10,  ---------- 集群中没有chatchannelmgr
    RET_CLUSTER_OPERATIONHTTPMGR_NONE = 11,  ---------- 集群中没有OperationHttpMgr
    RET_CLUSTER_REGIONONLINEAGENT_NONE = 12,  ---------- 集群中没有RegionOnlineagent

    RET_STORYMODE_STOP_HANDLE_DELIVER_REGION = 104,  --当前处于剧情模式不许传送

    --  登录
    RET_LOGIN_ACCOUNT_EMPTY = 1001, -- 账号为空，登录失败
    RET_LOGIN_AUTH_FAILED = 1002, -- 用户验证失败
    RET_LOGIN_SESSION_FAILED = 1003, -- 会话验证失败，请重新登录
    RET_LOGIN_CREATE_AVATAR_FAILED = 1004, -- 创建角色失败
    RET_LOGIN_LOAD_AVATAR_FAILED = 1005, -- 角色加载失败
    RET_LOGIN_BY_CLIENT_VERSION_TOO_LOW = 1006, -- 版本太低,请更新升级
    RET_LOGIN_BY_KICK = 1007, -- 请重新登录
    RET_LOGIN_BY_LIMIT_AVATAR = 1008, -- 您好，您的角色由于[%s]已被封停，如有疑问，请联系客服
    RET_LOGIN_BY_LIMIT_IP = 1009, -- 您好，您的角色由于[%s]已被封停，如有疑问，请联系客服
    RET_LOGIN_BY_LIMIT_DEVICE = 1010, -- 您好，您的角色由于[%s]已被封停，如有疑问，请联系客服
    RET_LOGIN_HOSTNUM_EMPTY = 1011, -- 请选择服务器，登录失败
    RET_LOGIN_ACCOUNT_ERROR = 1012, -- 账号不一致，登录失败
    RET_LOGIN_AVATAR_FULL = 1013, -- 登录队列已满，请稍后尝试登录
    RET_LOGIN_SERVER_BUSY = 1014, -- 服务器繁忙，登录失败
    RET_LOGIN_QUIT_QUEUE = 1015, -- 您已退出登录队列
    RET_LGOIN_NOT_READY = 1016, -- 您的账号数据异常，请联系客服
    RET_LGOIN_ROLE_ENTER_FAIL = 1017, -- 您的在线时长已达上限
    RET_LGOIN_REALNAME_FAIL = 1018, -- 实名认证失败
    RET_LOGIN_REGISTER_ACCOUNT_DISABLE = 1019, -- 新账号注册已关闭
    RET_LGOIN_REALNAME_REGISTER = 1020, -- 您提交的实名信息不通过
    RET_LOGIN_IP_NOT_MATCH = 1021, -- 本产品在您当前所在区域不可用
    RET_LOGIN_ACCOUNT_HAS_CHINESE = 1022, -- 账号不可输入中文
    RET_LOGIN_GET_SERVER_LIST_FAILED = 1023, -- 获取服务器列表失败，请检查设备的网络连接
    RET_LOGIN_GETTING_SERVER_LIST = 1024, -- 正在获取服务器列表，请稍后
    RET_LOGIN_ACCOUNT_CANNOT_EMPTY = 1025, -- 账号名不能为空
    RET_LOGIN_NOT_SELECT_SERVER = 1026, -- 请选择服务器
    RET_LOGIN_HAS_REGISTERED_REAL_NAME = 1027, -- 你已实名(%s)，无须再次登记
    RET_LOGIN_IN_OTHER_PLACE = 1028, -- 您已在别处登录
    RET_LOGIN_PLAY_TIME_EXPIRED = 1029, -- 游戏时间耗尽
    RET_LOGIN_EXPERIENCE_TIME_EXPIRED = 1030, -- 体验时间已过，请进行实名认证
    RET_LOGIN_AUTH_SUCCEED = 1031, -- 认证成功，请重新登录
    RET_LOGIN_ID_CARD_NUMBER_ERROR = 1032, -- 证件号格式不对，请填写18位真实有效的身份证号
    RET_LOGIN_PLEASE_RELOGIN = 1033, -- 请重新登录
    RET_LOGIN_SDK_INFO_EMPTY = 1034, -- 请先登录渠道SDK
    RET_LOGIN_IN_DIFF_DEVICE = 1035, -- 不允许在不同设备登陆同一账号
    RET_LOGIN_REFUSE_BIND_DEVICE = 1036, -- 拒绝绑定设备
    RET_LOGIN_WHITE_LIST_CHECK_FAILED = 1037, -- 白名单检查失败
    RET_LOGIN_NOT_IN_INTERNAL_WHITE_LIST = 1038, -- 不在内部白名单
    RET_LOGIN_BY_PATCH_VERSION_TOO_LOW = 1039, -- patch version 太低，请更新升级
    RET_LOGIN_TO_TARGET_SERVER = 1040, -- 登录目标服务器
    RET_LOGIN_PATCH_RESOURCE_NOT_COMPLETE = 1041, -- 补丁资源未下载完成

    -- 角色
    RET_CHAR_NOT_EXIST = 2001, -- 角色不存在
    RET_CHAR_EXP_RESOURCES_NOT_ENOUGH = 2007, --角色升级所需狗粮不足
    RET_CHAR_CASH_RESOURCES_NOT_ENOUGH = 2008, --角色升级所需现金不足
    RET_CHAR_CURRENTLEVEL_MAXLEVEL = 2009, --当前角色等级大于最大等级
    RET_CHAR_LEVEL_DISSATISFACTION = 2010, --当前等级不满足突破所需等级
    RET_CHARBREAKTABLE_NOTEXIST_CHARRESOURCES = 2011, --角色突破表中不存在该角色所突破对应的材料
    RET_CHAR_BREAKLEVEL_RESOURCE_NO_ENOUGH = 2012, --角色突破所需要的材料不足
    RET_CHAR_LEVEL_NOT_CORRECT = 2013,--角色等级参数不正确
    RET_CHAR_GRADE_LEVEL_NOT_CORRECT = 2014,--角色阶级参数不正确
    RET_CHAR_GRADE_LEVEL_IS_MAX = 2015,--角色阶级已达最大值
    RET_CHAR_GRADE_LEVEL_RESOURCE_NOT_ENOUGH = 2016,--角色升阶所需要的材料不足
    RET_CHANGENAME_TIME_ERROR = 2017,--改名时间不允许
    RET_CHANGENAME_NO_NEED = 2018,--无需改名
    RET_CHANGENAME_TOO_LONG = 2019,--名太长
    RET_CHAR_CORNER_PARAM_NOT_VALID = 2020,--角色角部可视性参数不正确
    RET_CHAR_CORNER_VISIBLE_CONFLICT = 2021,--角色角部可视性冲突
    RET_CHANGENAME_EMPTY = 2022,--名字为空
    RET_CHAR_COMMONCHAR_NOT_EXIST = 2023, -- 角色公共数据不存在
    RET_CHAR_COLOR_PART_ERROR = 2024,  --武器染色部位不正确,存在部位重复
    RET_CHAR_COLOR_PART_ERROR_INT = 2025, --武器染色部位不正确, 非整数
    RET_CHAR_COLOR_PART_ERROR_LIMIT = 2026, --武器染色部位不正确
    RET_CHAR_COLOR_IS_SAME = 2027, --武器染色当前颜色与新颜色一致
    RET_CHAR_SKIN_NOT_EXIST = 2028, ---- 角色皮肤不存在
    RET_CHAR_SKIN_INFO_ERROR = 2029, ---- 角色皮肤未配表
    RET_CHAR_APPEARANCINDEX_ERROR = 2030, --- 外观索引错误
    RET_CHAR_APPEARANC_MAX_NUM = 2031, --- 角色拥有的外观超过最大数量
    RET_CHAR_SWITCH_SKIN_FAILER = 2032, --- 角色切换皮肤失败
    RET_CHAR_NOT_GET_CHAR = 2033,  ---- CommonChar角色未获取不能设置皮肤
    RET_CHAR_OWNER_SKIN_IS_NULL = 2034, --- OWNERSKIN 是空的
    RET_CHAR_ALREADY_UNLOCKED = 2035, -- 角色已解锁
    RET_CHAR_APPEARANC_INDEX_NOT_USE = 2036, -- 该部位不能安装配饰 
    RET_CHAR_HAIR_NOT_EXIST = 2037, -- 角色发型不存在 
    RET_CHAR_HAIR_NOT_OWNED = 2038, -- 角色发型未拥有 
    RET_CHAR_HAIR_IS_SAME = 2038, -- 角色发型与当前发型一致
    RET_CHAR_HAIR_PLAN_ERROR = 2039, -- 角色发型方案有误
    RET_CHAR_HAIR_COLOR_PART_ERROR = 2040, -- 角色发型染色部位有误
    RET_CHAR_HAIR_COLOR_IS_SAME = 2041, -- 角色发型染色颜色重复
    RET_CHAR_HAIR_COLOR_IS_COMMON = 2042, -- 角色发型是通用发型，不支持染色
    RET_CHAR_GRADE_NOT_MAX = 2043, --角色前六命没满
    RET_CHAR_CANT_UPGRADE_EXTRA_GRADE_LEVEL = 2044, --当前角色不支持七命
    RET_CHAR_ALREADY_UPGRADE_EXTRA_GRADE_LEVEL = 2045, --当前角色已七命
    RET_CHAR_EXTRA_GRADE_LEVEL_CONDITION_NOT_MET = 2046, --七命条件不满足
    RET_CHAR_SKIN_LEVEL_NOT_CORRECT = 2047,--角色皮肤升级的等级参数有误
    RET_CHAR_SKIN_LEVEL_INFO_ERROR = 2048,--角色皮肤升级的等级配表有误
    RET_CHAR_SKIN_LEVEL_CONDITION_NOT_MET = 2049,--角色皮肤升级的条件不满足
    RET_CHAR_SKIN_LEVEL_RESOURCE_NOT_ENOUGH = 2050,--角色皮肤升级所需的资源不足

    -- 武器
    RET_WEAPON_NOT_EXIST = 3001, -- 武器不存在
    RET_WEAPON_EXP_ITEMS_NOT_ENOUGH = 3002, --武器升级所需狗粮不足
    RET_WEAPON_CASH_ITEMS_NOT_ENOUGH = 3003, --武器升级所需现金不足
    RET_WEAPON_CURRENTLEVEL_MAXLEVEL = 3004, --当前武器等级大于最大等级
    RET_WEAPON_LEVEL_DISSATISFACTION = 3005, --当前等级不满足突破所需等级
    RET_WEAPONBREAKTABLE_NOTEXIST_WEAPONITEMS = 3006, --武器突破表中不存在该武器所突破对应的材料
    RET_WEAPON_BREAKLEVEL_ITEM_NO_ENOUGH = 3007, --武器突破所需要的材料不足
    RET_WEAPON_LEVEL_NOT_CORRECT = 3008,--武器等级参数不正确
    RET_WEAPON_GRADE_LEVEL_NOT_CORRECT = 3009,--武器阶级参数不正确
    RET_WEAPON_GRADE_LEVEL_IS_MAX = 3010,--武器阶级已达最大值
    RET_WEAPONCARDLEVEL_NOTEXIST_INFO = 3011,--武器同卡表里不存在该武器信息
    RET_CONSUME_WEAPON_NOT_EXIST = 3012,--武器同卡所消耗的武器不存在
    RET_CONSUME_WEAPON_IS_EQUIPMENT = 3013,--武器同卡所消耗的武器已被装备
    RET_CONSUME_WEAPON_IS_LOCK = 3014,--武器同卡所消耗的武器已被锁
    RET_CONSUME_WEAPON_ID_IS_DIFF = 3015,--武器同卡所消耗的武器不是同名武器
    RET_WEAPON_TAG_NOT_EXIST = 3006,--武器tag不存在
    RET_WEAPON_TAG_NOT_MATCH = 3017,--武器与tag不匹配
    RET_WEAPON_COLOR_PART_ERROR = 3018,--武器染色部位不正确
    RET_WEAPON_COLOR_RESOURCE_ERROR = 3019,--武器染色剂参数不正确
    RET_WEAPON_COLOR_RESOURCE_NOT_ENOUGH = 3020,--武器染色所需染色剂数量不足
    RET_WEAPON_COLOR_IS_SAME = 3021,--武器染色当前颜色与新颜色一致
    RET_WEAPON_APPEARANCE_NOT_EXIST = 3022,--武器外观不存在
    RET_WEAPON_ACCESSORY_NOT_OWNED = 3023,--武器配饰未拥有
    RET_WEAPON_ACCESSORY_IS_SAME = 3024,--武器当前配饰与新配饰一致
    RET_WEAPON_SKIN_NOT_OWNED = 3025,--武器皮肤未拥有
    RET_WEAPON_SKIN_IS_SAME = 3026,--武器当前皮肤与新皮肤一致
    RET_WEAPON_SKIN_INFO_NOT_EXIST = 3027,--武器皮肤信息不存在
    RET_WEAPON_SKIN_NOT_MATCH = 3028,--武器皮肤不适用
    RET_WEAPON_BLUK_BREAKDOWN_TABLE_NIL = 3029, --- 批量分解的武器参数是nil
    RET_CONSUME_WEAPON_INCLUDE_CURRENT_WEAPON = 3030, --武器同卡所消耗的武器包含是当前操作武器
    RET_WEAPON_IS_REMOVE_WEAPON_IN_BLUE_MGR = 3031, -- 该武器已经被移除到铸造中
    RET_WEAPON_GET_REWARD_FAILD = 3032, -- 该武器分解奖励失败
    RET_WEAPON_COLOR_PLAN_ERROR = 3033,--武器染色颜色方案不正确
    RET_WEAPON_COLOR_PLAN_IS_SAME = 3034,--武器当前染色方案与新方案一致
    RET_WEAPON_ACCESSORY_TYPE_ERROR = 3035,--武器配饰适用类型有误
    RET_WEAPON_ACCESSORY_NOT_SAME = 3036,--武器卸下配饰与当前配饰不一致
    RET_WEAPON_NOT_HYPER_WEAPON = 3037,--不是灵化武器
    RET_WEAPON_HYPERLEVEL_MAXLEVEL = 3038,--达到熔炼等级最大值
    RET_WEAPON_HYPERLEVEL_NOT_UNLOCK = 3039,--当前熔炼等级未解锁
    RET_WEAPON_HYPERLEVEL_RESOURCE_NOTENOUGH = 3040,--熔炼等级升级资源不足
    RET_WEAPON_FORGELEVEL_MAXLEVEL = 3041,--达到熔炉等级最大值
    RET_WEAPON_FORGELEVEL_QUEST_NOT_FINISH = 3042,--当前熔炉等级任务未完成
    RET_WEAPON_HYPER_INVALID_TALENT_ID = 3043,--无效天赋id
    RET_WEAPON_HYPER_ID_NOT_MATCH = 3044,--灵化武器id不匹配
    RET_WEAPON_HYPER_TALENT_NOT_UNLOCK = 3045,--天赋未解锁
    RET_WEAPON_HYPER_LEVEL_NOT_ENOUGH = 3046,--熔炉等级不足
    RET_WEAPON_HYPERTALENT_RESOURCE_NOTENOUGH = 3047,--天赋所需资源不足

    -- Mod
    RET_MOD_NOT_EXIST = 4001, -- Mod不存在
    RET_MOD_SLOT_NOT_EXIST = 4002, -- Mod槽不存在
    RET_MOD_SLOT_REPEAT_SET = 4003, -- Mod槽重复设置
    RET_MOD_APPLICATIONTYPE_NOT_SUIT = 4004, -- Mod不适用
    RET_MOD_OVER_CHAR_MODVOLUME = 4005, -- 超过角色的mod容量
    RET_MOD_SUIT_NOT_EXIST = 4006, -- Mod配置不存在
    RET_MOD_IS_REPEAT = 4007,  -- Mod出现重复
    RET_MOD_CURRENTLEVEL_GREATERTHAN_MAXLEVEL = 4008, --当前Mod等级大于最大Mod等级
    RET_DATAMGR_NOT_EXIST_MOD = 4009, --当前Mod表中不存在此Mod的信息
    RET_MOD_DECOMPOSE_SUCCESS = 4010, --Mod分解成功
    RET_MOD_ISORIGINAL = 4011, --该Mod是张原始Mod，用于锁定，不能锁定原始Mod
    RET_MOD_SLOT_LOCK = 4012,  -- Mod槽未解锁
    RET_MOD_POLARITY_INVALID = 4013,  -- 极性无效
    RET_MOD_AUTOPUTON_FAILD = 28002, --Mod自动装配中止
    RET_MOD_IS_ORIGINAL = 4015, --- Mod是原始Mod
    RET_MOD_MOD_LEVEL_NOT_MAX = 4016, -- Mod等级没有达到最大等级
    RET_MOD_CURRENTCARDLEVEL_MAX = 4017, -- 当前的突破等级已达最大
    RET_MOD_NOT_MOD_CARD_LEVEL_UP = 4018, -- 该MOd不能进行突破
    RET_MOD_MODCARD_SELECTPARAMS_ERROR = 4019, -- Mod突破所需要的
    RET_MOD_MODCARD_SELECTPARAMS_COUNT_ERROR = 4020, --- 客户端传来的SelectParam中某一Mod数量错误与表对不上
    RET_MOD_COUNT_NOT_ENOUGH = 4021, --- 所需要消耗的Mod数量不足
    RET_MOD_COUNT_ERROR_BY_LEVEL_MOD = 4022, --- 对于升级后的Mod数量只能为1 
    RET_MOD_MODCARD_REPEAT_MOD_DEDUCT = 4023, -- 扣除的Mod重复
    RET_MOD_SELF_NOT_CAN_CONSUME = 4024, --- 自身不能作为消耗材料 
    RET_MOD_CURRENT_COUNT_CLIENT_ERROR = 4025, --- 客户端当前拥有的数量与服务器对应不上
    RET_MOD_CURRENTLEVEL_MAX = 4026, --- Mod已经升级到最大等级
    RET_MOD_CURRENTLEVEL_OR_TARGETLEVEL_ERROR = 4027, --- Mod升级当前与目标等级混乱
    RET_MOD_APPLY_SLOT_ERROR = 4028, --- Mod应用槽位错误
    RET_MOD_NEW_SUIT_NAME_IS_NULL = 4029, --- 配置名不能为空
    RET_MOD_SLOT_REPEAT = 4030,--Mod槽位存在重复
    RET_MOD_ARCHIVE_ID_NOT_EXIST = 4031, --- 图鉴ID不存在
    RET_MOD_ARCHIVE_DATA_NOT_EXIST = 4032, --- 图鉴表不存在
    RET_MOD_ARCHIVE_REPEAT_REWARD = 4033, --- 图鉴奖励重复领取
    RET_MOD_ARCHIVE_MOD_LIST_ERROR = 4034, -- 图鉴列表中ModList不正确
    RET_MOD_ARCHIVE_MOD_UNLOCK_CONDITION = 4035, --- 图鉴表未解锁
    RET_MOD_ARCHIVE_MOD_NOT_GET = 4036, --- 存在未获取的Mod
    RET_MOD_TAKE_ALL_OFF_NOT_EXIST = 4037, --- 没有可卸载的Mod
    RET_MOD_CURRENT_MOD_NOT_CAN_SALE = 4038, --- 当前mod不能出售
    RET_MOD_CARD_LEVEL_COUNT_ERROR = 4039, --- Mod突破数量超过目标值
    RET_MOD_GENERAL_RESOURCE_NOT_ENOUGH = 4040, --- 通用材料不足
    RET_MOD_CARD_NEED_RESOURCE_ERROR = 4041, -- 该mod突破资源错误
    RET_MOD_CARD_NEED_RESOURCE_ID_EXIST = 4042, ---该资源未配置表
    RET_MOD_MODCARD_SELECTPARAMS_RESOURCE_COUNT_ERROR = 4043, -- 选择的资源超过或者小于所需数量

    RET_SIGNBOARD_NPC_SWITCH_FAIL = 5001 , --看板娘邀请失败
    RET_SIGNBOARD_NPC_IS_EXIST = 5002 , --看板娘已被摆放
    RET_SIGNBOARD_NPC_IS_NOT_OWNED = 5003, --看板娘未拥有
    RET_SIGNBOARD_NPC_IS_NOT_SELELCT = 5004, --请选择想要邀请的角色
    RET_SIGNBOARD_NPC_DAILY_TALK_COUNT_LIMIT = 5005, --当前看板娘每日话题已达上限
    RET_SIGNBOARD_NPC_TOTAL_DAILY_TALK_COUNT_LIMIT = 5006, --所有看板娘每日累计话题已达上限
    RET_SIGNBOARD_NPC_NOT_CORRECT = 5007, --看板娘不存在
    RET_SIGNBOARD_NPC_DIALOGUE_ERROR = 5008, --看板娘对话Id有误
    RET_SIGNBOARD_NPC_DIALOGUE_ALREADY_SAVE = 5009, --看板娘对话Id已记录


    -- 任务
    RET_QUESTCHAIN_NOT_EXIST = 6001, ---- 任务链不存在
    RET_QUESTCHAIN_INACTIVE = 6002, ---- 任务链未激活
    RET_QUESTCHAIN_IS_COMPLETE = 6003, ---- 任务链已完成
    RET_QUESTCHAIN_NOT_SATISFIED_START = 6004, ---- 任务链不满足激活条件 确保是否自动开始
    RET_QUESTMAP_NOT_EXIST = 6005 , ---- 任务目标地图不存在
    RET_QUEST_TARGET_QUEST_NONE_DOIONG = 6006, ---- 目标任务ID未在执行中
    RET_INITCONFIG_NO_MELEEWEAPONID = 6007, ---- 未设置近战武器ID
    RET_INITCONFIG_NO_RANGEDWEAPONID = 6008, ---- 未设置远程武器ID
    RET_HAS_MELEEWEAPONID = 6009, ---- 已拥有近战武器
    RET_HAS_RANGEDWEAPONID = 6010, ---- 已拥有远程武器
    RET_WEAPONID_UNVALID = 6011, ---- 武器ID无效
    RET_QUESTCHAIN_COMPLETE_FAIL = 6012, --- 请检查当前是否满足任务链完成条件
    RET_QUEST_NOT_EXIST_QUESTID = 6013, ---- 不存在任务ID
    RET_QUEST_TARGETQUEST_COMPLETE = 6014, ---- 目标任务已经完成
    RET_QUEST_QUESTPICKID_NOT_EXIST = 6015, ---- QuestPickId不存在
    RET_QUEST_QUESTCHAIN_IN_DOING = 6016, ---- 任务链未在执行中
    RET_QUEST_QUESTPICK_COMPLETE = 6017, ---- 当前QuestPickId已经完成，请重新配置新的QuestPickId
    RET_QUEST_QUESTPICK_DROP_NOT_EXIST = 6018, ---- 不存在Pick对应的Drop
    RET_QUEST_QUESTPICK_EXIST = 6019, ---- 已经存在QuestPickId对应的数据禁止重复添加
    RET_QUEST_DELIVER_PARAM_ERROR = 6020, ---- 任务传送参数错误
    RET_QUEST_QUESTCHAIN_NONE_FINISH = 6021, ---- 任务链未完成
    RET_QUEST_QUESTCHAINTABLE_NOT_EXIST_QUESTCHAINID = 6022, ---- 任务链表不存在该任务链ID
    RET_QUEST_NOT_EXIST_GAMEMODE = 6023, ---- 任务运行不存在GameMOde
    RET_QUEST_REGION_NOT_ALLREADY = 6024, ---- 任务运行IsRegionAllReady为false
    RET_QUEST_CURRENT_QUEST_DOING = 6025, ---- 当前任务正在运行中 禁止重复开始完成
    RET_QUEST_PARAMNAME_EXIST = 6026, ---- 存储的任务键值已经存在 
    RET_QUEST_REMOVE_KEY_NOT_EXIST = 6027, ---- 移除的键值对不存在
    RET_QUEST_GLOBAL_VARIABLE_NOT_EXIST = 6028, ---- 全局变量不存在或者不是全局变量
    RET_QUEST_PRE_QUEST_QUESTCHIAN_NOT_UNLOCK_STATE = 6029, --- 前置任务运行必须是QuestChain Unlock状态
    RET_QUEST_PRE_QUEST_SHOW_WINDOW = 6030, ---- 该前置任务需要手动接取完成 
    RET_QUEST_PRE_QUEST_CHAIN_NOT_RECEIVE = 6031, ---- 当前任务链状态为Unlock且未运行任何前置任务，不能接取
    RET_QUEST_CURRENT_RUNNING_IS_NOT_PRE = 6032, ---- 当前任务不是前置任务
    RET_DAILY_TASK_DAILY_NOT_EXIST = 6033, ---- 当前日常任务不存在
    RET_DAILY_TASK_ACHV_NOT_EXIST = 6034, ---- 日常成就不存在
    RET_DAILY_TASK_ACHV_NOT_COMPLETE = 6035, --- 日常任务未完成
    RET_DAILY_TASK_NOT_COMPLETE_STATE = 6036, ---- 日常任务不是完成状态
    RET_DAILY_TASK_CURRENT_PROGRESS_ERROR = 6037, --- 当前进度小于目标进度
    RER_DAILY_TASK_TARGET_PROGRESS_NOT_EXIST = 6038, --- 目标进度不存在
    RET_DAILY_TASK_TARGET_PROGRESS_NOT_COMPLETE = 6039, --- 目标进度不是完成状态
    RET_DAILY_TASK_GET_ALL_DAILY_REWARD_FAILED = 6040, --- 领取失败，没有可领取的奖励
    RET_DAILY_TASK_QUEST_REWARD_IS_NULL = 6041, --- 日常任务时空 
    RET_QUEST_CURRENT_TRACKING_QUEST_CHAIN_NOT_EQUAL = 6042, --- 当前追踪的任务链与目标任务链不一致
    RET_DAILY_GLOBAL_PROGRESS_REWARD_ERROR = 6043, --- 进度在表中不存在对应等级奖励
    RET_DAILY_GLOBAL_SYSTEM_NON_UNLOCK = 6044, --- 日常任务未解锁
    RET_DAILY_TALK_ID_NOT_EXIST = 6045, --- 日常对话ID不存在
    RET_DAILY_TALK_ID_GET_REWARD = 6046, --- 日常任务奖励已经领取
    RET_QUEST_POPUI_ID_NOT_EXIST = 6047, --- 对应的弹窗UIId不对
    RET_QUEST_POPUI_ID_EXIST = 6048, --- 对应的弹窗已经触发

    -- Item
    RET_ITEM_STATE_SPAN_LARGE = 7001,         --物品状态改变超过最大状态改变的跨度
    RET_ITEM_NONE = 7002,         --服务中不存在该物品
    RET_ITEM_COINTYPE_NONE = 7003,     --该物品不存在销售钱币类型
    RET_SALEITEM_COUNT_OVER_ITEM_ITEMCOUNT = 7004, --客户端发送出售的数量大于目前玩家所拥有的物品数
    RET_ITEM_NOT_ENOUGH = 7005,  --物品数量不足
    RET_ITEM_STATE_LOCK = 7010,  --当前物品的状态是被锁定的，无法进行出售或者锁定
    RET_ITEM_SALE_WEAPON_IS_EQUIPMENT = 7012, --当前装备的物品不容许售卖
    RET_ITEM_NO_SALE = 7015,  --当前ItemValue <= 0 不许售卖
    RET_ITEM_NO_SALE_LOCK = 7016, --当前的ItemValue < 0 不许锁定
    RET_ITEM_NO_SALE_UNLOCK = 7017, --当前的ItemValue < 0 不许解锁
    RET_ITEM_LOCK_FAILER = 7018, -- 物品锁定失败
    RET_ITEM_UNLOCK_FAILER = 7019, -- 物品解锁失败
    RET_ITEM_NOT_LOCK = 7020, -- 物品没有上锁
    RET_ITEM_NOT_USABLE = 7021, -- 物品不能使用
    RET_ITEM_CANT_OPT_USE = 7022, -- 物品不能自选
    RET_ITEM_OPTLIST_ERROR = 7023, -- 物品自选列表参数错误
    RET_ITEM_OPTCOUNT_ERROR = 7024, -- 物品自选数量错误
    RET_RESOURCE_INDEX_MAX = 7025, -- 超过最大值
    RET_RESOURCE_REPEAT_ADD = 7026, -- 重复添加
    RET_RESOURCE_LIMITED_ID_DATA_ERROR = 7027, -- 不存在该ID 表信息
    RET_RESOURCE_LIMITED_ERROR = 7028, -- 不存在该ID
    RET_RESOURCE_ADD_REASON_NOT_EXIST = 7029, -- 不存在该Reason
    RET_RESOURCE_LIMITED_NOT_EXIST = 7030, --- 不存在限时道具
    RET_RESOURCE_ITEM_EXIST = 7031, --- 该物品存在
    RET_RESOURCE_ADVANCE_NOT_ENOUGH = 7032, --- 万能染色剂不足
    RET_RESOURCE_ADVANCE_NOT_EXIST = 7033, -- 不存在万能染色剂资源
    RET_RESOUECE_ADVANCE_MUTUAL_EXCLUSION = 7034, --- 该万能染色剂不支持补充改染色资源

    -- 副本
    RET_DUNGEON_IN_BATTLE = 8001,  -- 战斗中
    RET_DUNGEON_IN_MATCHING = 8002,  -- 匹配中
    RET_DUNGEON_LOCKED = 8003,  -- 未解锁
    RET_DUNGEON_CLOSED = 8004,  -- 关闭
    RET_DUNGEON_NOT_EXIST = 8005,  -- 副本不存在
    RET_DUNGEON_NOT_CREATE = 8006, -- 副本未创建
    RET_DUNGEON_EVENT_GEN_PET_NOT_EXIST = 8007, -- 这个副本没有可生成的宠物
    RET_DUNGEON_EVENT_GEN_NOT_IN_DUNGEON = 8008, -- 调用副本事件生成器时 不在副本中
    RET_PET_DUNGEON_EVENT_NOT_HAPPEN = 8009, -- 宠物副本事件未发生
    RET_PET_CAPTURE_FAILED = 8010, -- 宠物捕捉失败
    RET_PET_FOOD_RESOURCE_NOT_ENOUGH = 8011, -- 宠物食物资源不足
    RET_DUNGEON_CANNOT_MULTI = 8012, -- 副本不能多开
    RET_DUNGEON_TICKET_INVALID = 8013, -- 副本门票无效
    -- RET_PET_NOT_EXIST_IN_EXCEL = 8014, -- 宠物不存在
    RET_PET_PREMIUM_TRANSFORM_NIL = 8015, -- 宠物没配PremiumTransform就是用food3
    RET_EVENT_DUNGEON_TYPE_INVALID = 8016, -- 活动副本类型无效
    RET_EVENT_DUNGEON_NOT_OPEN = 8017, -- 活动副本未开启
    RET_DUNGEON_MAX_ROUND = 8018, -- 副本已到最大轮次
    RET_DUNGEON_CANNOT_SELECT_TICKET = 8019, -- 副本当前阶段不能选择门票
    RET_DUNGEON_ID_INVALID = 8020, -- 副本ID无效
    RET_DUNGEON_INVALID_PARAM = 8021, -- 副本参数无效
    RET_DUNGEON_DUNGEON_INFO_NOT_EXIST = 8022, -- 副本信息不存在
    RET_DUNGEON_SETTLEMENT_ONLINE_NOT_EXIST = 8023, -- 结算联机场景信息不存在
    RET_DUNGEON_CANNOT_MATCH = 8024, -- 副本不能匹配
    RET_DUNGEON_MAX_PLAYERS = 8025, -- 副本已达人数上限
    RET_DUNGEON_NOT_IRON_SURVIVAL = 8026, -- 不是钢铁探险副本
    RET_DUNGEON_ONLY_LEADER_CAN_START = 8027, -- 仅队长可开启
    RET_DUNGEON_IRON_SURVIVAL_TICKET_NOT_VALID = 8028, -- 钢铁之证不合法
    RET_DUNGEON_IRON_SURVIVAL_DROP_NOT_VALID = 8029, -- 钢铁之证自选掉落方案不合法
    
    -- 技能
    RET_SKILL_NOT_EXIST = 9001,  -- 技能不存在
    RET_SKILL_LEVEL_IS_MAX = 9002,  -- 技能已满级
    RET_SKILL_LEVEL_IS_LIMITED = 9003,  -- 升级受到当前突破等级限制
    RET_SKILL_LEVEL_PARAM_ERROR = 9004,  -- 技能等级参数错误
    RET_SKILL_IS_LOCKED = 9005, --技能未解锁
    RET_CHAR_SKILL_TREE_NOT_EXIST = 9006,   --技能树不存在
    RET_CHAR_SKILL_TREE_NODE_NOT_EXIST = 9007,  --技能树节点不存在
    RET_CHAR_SKILL_TREE_NODE_IS_ACTIVE = 9008,   --当前技能树节点已激活
    RET_CHAR_SKILL_TREE_NODE_IS_SKILL = 9009,   --当前技能树节点是技能节点，激活依赖角色的突破等级
    RET_CHAR_SKILL_TREE_NODE_ATTR_ERROR = 90010,  --属性节点表里信息不存在或者有误
    RET_CHAR_SKILL_TREE_RESOURCE_NOT_ENOUGH = 90011,  --技能树属性节点激活所需材料不足
    RET_CHAR_SKILL_TREE_NODE_ENHANCE_LEVEL_NOT_ENOUGH = 90012,  --技能树属性节点激活所需角色突破等级不足
    RET_CHAR_SKILL_TREE_NODE_CONDITION_NOT_SATISFY = 90013,  --技能树属性节点激活所需条件不满足
    RET_CHAR_SKILL_TREE_LAST_NODE_NOT_ACTIVE = 90014,  --上一节点暂未激活
    RET_CHAR_SKILL_TREE_CHAR_LEVEL_NOT_SATISFY = 90015,  --技能树属性节点激活所需角色等级不满足
    RET_CHAR_SKILL_TREE_CHAR_SKILL_LEVEL_NOT_SATISFY = 90016,  --技能树属性节点激活所需角色技能等级不满足


    -- 世界场景
    RET_REGION_NOT_EXIT = 10001,   ----- 区域退出
    RET_REGION_IN_BATTLE = 10002,  ------ 当前处于战斗状态
    RET_REGION_IN_MATCHING = 10003, ----- 当前处于匹配阶段
    RET_REGION_NOT_EXIST = 10004,   ----- 子区域不存在
    RET_SUBREGION_NOT_EXIST = 10005,    ---- 任务数据不存在
    RET_REGION_QUESTDATA_NOT_EXIST = 10006, ----- 任务数据不存在
    RET_REGION_SYSNC_NOT_EXIST = 10007, ----- 该区域不同步位置信息

    -- 玩家位置更新
    RET_CLIENT_TO_SERVER_LASTPLAYERINFO_NOT_EXIST = 10008, --- 客户端向服务器发送的玩家信息不存在

    -- 区域跳转
    RET_CURRENT_TARGET_REGIOINID_EQUAL = 10009,  ---- 当前区域ID与跳转的区域ID相同
    RET_TARGETREGIONID_OUTSIDE = 10010,   -- 目标区域在区域外 一般指代客户端传过来为-1
    RET_TARGETREGIONID_NOT_EXIST = 10011, -- 客户端传进来一个空的区域ID
    RET_REGION_NOT_IN_BIGWORLD = 10012, ----- 当前不满足在大世界中
    RET_REGION_REGIONDATA_NULL = 10013,  -- 客户端传过来的区域数据为空 ，或者没有添加就更新了
    RET_REGOIN_ACTOR_DESTORY_NOT_SAVE = 10014, ----客户端发过来的任务数据相关的Actor已经被销毁 ，不用存储
    RET_REGION_ADD_NEW_ACTOR = 10015,  -----客户端传来的数据服务端不存在，新添加数据
    RET_REGION_NOT_EXIST_REGION_TYPE_DATA = 10016,  --- 服务器不存在该类型的区域数据
    RET_REGION_NOT_BIGWORLD_OR_NOT_IN_FIELD = 10017, ----- 不在大世界或者不在野外
    RET_REGION_NOT_EXIST_REGIONID_DATA = 10018, ------- 不存在该区域ID数据
    RET_REGION_NOT_EXIST_EXPLORE_DATA = 10019, ----- 不存在探索数据
    RET_REGION_NOT_EXIST_EXPLORE_DATA_KEY = 10020, ----- 不存在探索数据Key索引
    RET_REGION_NOT_WORLDREGIONEID = 10021, ----- 不存在区域EId
    RET_REGION_REGIONBASEDATA_IS_EXIST = 10022, ----- 区域基础数据已经存在不容许添加
    RET_REGION_NOT_EXIST_REGIONID_IN_TABLE = 10023,  ------ 不存在区域ID 在Region表里面
    RET_REGION_NOT_EXIST_MARKPOINTDATA = 10024, ------ 不存在MarkPoints
    RET_REGION_EXCEDING_MAX_NUM_MARKPOINTDATA = 10025, ------ 标记点超过最大数量
    RET_REGION_AVATAR_STATE_ENTERBIGWORLD = 10026, ------ 当前Avatar处于正在进入区域状态
    RET_REGION_NOT_EXIST_LEVELREGIONDATA = 10027, ------ 不存在LevelDatas
    RET_REGION_NOT_EXIST_LEVELNAME = 10028, ----- 不存在LevelName
    RET_REGION_NOT_EXIST_CACHE_REGIONBASEDATA = 10029, ----- 缓存中不存在RegionBaseData
    RET_CLIENT_TO_SERVER_STOP_REASON_UNKNOW = 10030, ----- 停止同步的原因未知
    RET_REGION_EXPLORE_SWITCH_STATE_FAILD = 10031,  ------ 探索组状态切换失败，重复激活
    RET_REGION_EXPLORE_UPDATEDATA_FAILD = 10032, ---- 更新探索组数据失败
    RET_REGION_SYNCLOCATION_REASON_NOT_EXIST = 10033, ----- 同步原因不存在
    RET_REGION_CREATORID_REPEAT = 10034, ----- 区域中静态刷新点重复
    RET_REGION_BASEDATA_SUBREGIONID_ERROR = 10035, ----RegionBaseData中的SubRegionID错误
    RET_REGION_BASEDATA_WORLDREGIONEID_REPEAT = 10036, ---- WORLDREGIONEID重复
    RET_REGION_QUESTDATA_NOT_ADD_REGIONBASEDATA = 10037, ---- 任务数据不能直接通过数据添加接口(任务完成存储)
    RET_REGION_SUIT_FUNCTION_NAME_NOT_EXIST = 10038, ---- 配置所关联的Function不存在
    RET_REGION_SUIT_SUITUPDATA_PARAM_NULL = 10039, ---- 配置所存储的的Param是NULL
    RET_REGION_QUEST_SPECIAL_IS_SUCCESS = 10040, ----- 该特殊任务已经完成
    RET_REGION_QUEST_IN_SPECIALDOING = 10041, ----- 当前处于特殊任务之中，不允许任务
    RET_REGION_SPECIALID_NOT_EXIST = 10042, ----- 表里不存在特殊任务ID
    RET_REGION_REGIONBASEDATA_QUESTCHAINIID_ERROR = 10043, ------- RegionBaseData中的QuestChainID不正确
    RET_REGION_REGIONBASEDATA_RARELYID_ERROR = 10044, ------ RegionBaseData中的RarelyId不正确
    RET_REGION_EXPLORE_NOT_DOING = 10045, ----- 探索组未在执行中
    RET_REGION_REGIONBASEDATA_TYPE_ERROR = 10046, ----- 任务数据中类型错误
    RET_REGION_REGIONBASEDATA_BOUNS = 10047, ----- 该物体对应的奖励已经领取过
    RET_REGION_REWARD_REASON_NOT_EXIST = 10048, ----- 奖励原因不存在
    RET_REGION_REWARD_UNIQUESIGN_NOT_EXIST = 10049, ----- 奖励唯一标识不存在
    RET_REGION_REWARD_UNIQUESIGN_BOUNS = 10050, ---- 该Eid下的奖励已经领取
    RET_SUIT_SUITKEY_IS_NULL = 10051, ----- 该配置的Key值不存在
    RET_REGION_REGIONBASEDAT_REGIONID = 10052, ---- 存储数据区域ID与服务端区域ID不一致
    RET_REGION_EXPLORE_TYPE_CHANLLAGE = 10053, ---- 探索组的类型不是挑战类
    RET_REGION_QUESTCHAIN_NOT_UNLOCK = 10054, ---- 任务链的状态不是解锁状态无法进行接取
    RET_REGION_QUESTCHAIN_STATE_CHANGE_FAILER = 10055, ---- 任务状态转换失败
    RET_REGION_QUEST_DELIVERTYPE_ERROR = 10056, ---- 任务传送类型错误
    RET_REGION_DATA_ERROR = 10057, ---- 配表错误，或者存储的UnitTypeOrId错误
    RET_REGION_KEYCHEST_NOT_EXIST_INTERACTIVEID = 10058, ----- 不存在交互ID
    RET_REGION_QUESTID_ERROR = 10059, ---- 特指完成或者开始任务不是任务流程中的一环
    RET_REGION_PETID_NOT_EXIST = 10060, ---- Pet表不存在PetId
    RET_REGION_PETID_DATA_EXIST = 10061, ---- 该pet所对应的数据已经存在 特制添加
    RET_REGION_PET_STATE_INACTIVE = 10062, ---- 该Pet的状态不是激活状态
    RET_REGION_PETID_DATA_NOT_EXIST = 10063, ---- 该Pet的状态不是激活状态 特制状态更新
    RET_REGION_MARKPOINT_KEY_EXIIST = 10064, ---- 存在相同的标记点，添加重复
    RET_REGION_MARKPOINT_DATA_NOT_EXIST = 10065, ---- 不存在MarkPointKey对应的数据
    RET_REGION_MARKPOINT_NAME_MAX_LEN = 10066, ---- 名称长度超过了最大限制12个字符
    RET_REGION_RANDOMRULEID_ERROR = 10067, ---- 随机点的RandomRuleId错误
    RET_REGION_RANDOMREGIONDATAS_NULL = 10068,  ---- 随机添加的RegionDatas为NULL
    RET_REGION_RANDOM_ADD_WAY_ERROR = 10069, ---- 随机点添加途径出错(只能特殊接口添加)
    RET_REGION_RANDOM_RANDUMRULEID_REPEAT = 10070, ---- 随机规则ID重复
    RET_SUIT_SUITTYPE_IS_NULL = 10071, ---- 不存在SuitType
    RET_REGION_RANDOM_RANDOMTABLEID_ERROR = 10072, ---- 随机TableId错误
    RET_REGION_EXPLORE_EXPLORT_DATA_ERROR = 10073, ---- 探索组自动导出数据有误或者不存在
    RET_REGION_EXPLORE_NOT_SET_CHALLAGE_COMPLETE = 10074, ---- 不能设置到挑战完成
    RET_REGION_DISPATCH_DISPATCHID_ERROR = 10075, ---- 增加的派遣ID错误 不存在或者类型错误
    RET_ERGION_DISPATCH_DISPATCHID_DATA_ERROR = 10076, ---- 派遣表中不存在该派遣
    RET_REGION_DISPATCH_DISPATCH_REPEAT_ADD = 10077, ---- 重复添加派遣
    RET_REGION_DISPATCH_ADD_REASON_NOT_EXIST = 10078, ---- 添加派遣的原因不存在
    RET_REGION_DISPATCH_ADDS_DISPATCHID_ERROR = 10079, ---- 一次性添加多个派遣存在错误
    RET_REGION_DISPATCH_CHARS_NUM_ERROR = 10080,  --- 派遣所需的角色数量不正确
    RET_REGION_DISPATCH_CHAR_DOING = 10081, --- 角色正在派遣占用中
    RET_REGION_DISPATCH_NOT_EXIST = 10082, --- 派遣不存在、或者未获取
    RET_REGION_DISPATCH_CURRRNTLIST_NOT_EXIST = 10083, --- 派遣不在可派遣列表中
    RET_REGION_DISPATCH_STATE_ERROR = 10084, --- 派遣状态不是可激活状态
    RET_REGION_DISPATCH_REGIONID_ERROR = 10085, --- 派遣所在的区域不存在
    RET_REGION_DISPATCH_PLAYERLEVEL_ERROR = 10086, --- 当前和鸣等级不满足
    RET_REGION_DISPATCH_CONDITION_ERROR = 10087, --- 当前不满足派遣条件
    RET_REGION_DISPATCH_UNKNOWN_ERROR = 10088, --- 未知错误
    RET_REGION_DISPATCH_COOLING = 10089, --- 派遣处于冷却中 特制槽位
    RET_REGION_DISPATCH_STATE_DOING = 10090, --- 派遣状态处于执行中
    RET_REGION_DISPATCH_STATE_CANDISPATCH = 10091, --- 派遣状态处于可派遣
    RET_REGION_DISPATCH_STATE_FAILER = 10092, --- 派遣状态处于失败中
    RET_REGION_DISPATCH_START_NOT_DOING = 10093, --- 派遣状态未在进行中
    RET_REGION_DISPATCH_REGION_CONDITION_ERROR = 10094, --- 派遣区域未解锁
    RET_REGION_DISPATCH_LIST_EXIST = 10095, --- 派遣已经在派遣列表中
    RET_REGION_DISPATCH_RATE_ERROR = 10096, --- 该派遣的概率过低，不能进入派遣列表中
    RET_REGION_DISPATCH_STATE_COMPLETE = 10097, --- 派遣处于完成状态
    RET_REGION_DISPATCH_CHATLIST_ERROR = 10098, --- 最少派遣一名角色
    RET_REGION_DISPATCH_STATE_COOLING = 10099, --- 当前状态处于冷却中
    RET_REGION_LOCATION_ERROR = 10100, --- 位置信息错误
    RET_REGION_DISPATCH_STATE_ISUNLOCK = 10101, --- 派遣状态处于解锁状态
    RET_REGION_DISPATCH_DYNAQUEST_UNLOCK = 10102, --- 派遣所对应的动态事件未解锁
    RET_REGION_NOT_EXIST_STATICCREATOR = 10103, --- 不存在对应的区域刷新点数据
    RET_REGION_NOT_EXIST_CREATOR_REGIONBASEDATA = 10104, --- 不存在对应的刷新点数据 特指RegionBaseData
    RET_REGION_DISPATCH_LSIT_PROP_NOT_EXIST = 10105, ----- 不存在对应的DispatchListProp
    RET_REGION_DISPATCH_GETALLREWARD_NULL = 10106, ----- 一键派遣领取奖励，没有成功一个
    RET_REGION_EXPLORE_RARELYIDS_NULL = 10107, ---- 探索组传递的RarelyIds是空的
    RET_REGION_CURRENT_REGIONID_NOT_IN_HOME = 10108, ---- 当前区域不在据点
    RET_REGION_NOT_SET_SOJOURNS = 10109, ---- 不处于邀约系统标记中
    RET_REGION_PET_FAILED_NOT_CAN_DEAD = 10110, --- 宠物捕获失败不许死亡
    RET_REGION_DISPATCH_CURRENT_CHAR_BATTLE = 10111, --- 当前出战的角色不能派遣
    RET_REGION_COMMONQUESTDATA_NOT_ADD_REGIONBASEDATA = 10112, --- 任务关卡数据添加只在任务完成
    RET_REGION_DOING_QUESTCHAIN_NOT_CAN_START_PREQUEST = 10113, --- Doing状态下的任务链不能开始前置任务
    RET_REGION_CURRENT_DIALOGUEID_PRE_ERROR = 10114, --- 当前检定的DialogueId的前置ID有问题
    RET_REGION_EXPLORE_ID_REPEAT_ERROR = 10115, --- 探索组ID重复特指已经存在一个探索组ID
    RET_REGION_SYNC_REASON_NOT_NORMAL = 10116, --- 该状态下不能同步
    RET_REGION_TABLE_PARAMS_EXIST_ERROR = 10117, --- 存在错误
    RET_REGION_SKIP_REGION_REGION_NOT_EQUAL = 10118, --- SKipRegion只能用于同区域平滑过渡切换
    RET_REGION_SKIP_REGION_SPECIAL_STATUS = 10119, -- 特殊标记中
    RET_REGION_SUB_REGION_ID_NOT_EQUIAL = 10120, -- 同步位置子区域与服务器区域对应不上
    RET_REGION_INTERACTIVE_CHEST_CONFITION_NON_COMPLETE = 10121, --- 交互宝箱的条件未完成
    RET_REGION_DISPATH_CHAR_REPEAT = 10122, --- 存在相同的角色进行派遣
    RET_REGION_RANDOM_DATAS_REPEAT = 10123, --- 随机点存在相同数据
    RET_REGION_SYNC_PLAYER_LOCATION_IN_ONLINE = 10124, --- 当前处于区域联机不能同步
    RET_REGION_EXPLORE_IN_CHALLENGE = 10125, --- 当前处于探索挑战中
    RET_REGION_EXPLORE_NOT_IN_CHALLENGE = 10126, --- 当前不处于挑战中
    RET_REGION_TEST_REGION_CHECK_QUERY = 10127, --- 未开启测试
    RET_REGION_AUTO_CREATOR_REGION_DATA_IS_NULL = 10128, --- 自动激活的刷新点为空
    RET_REGION_DISPATCH_SYSTEM_NON_UNLOCK = 10129, --- 派遣系统未解锁
    RET_REGION_DISPATCH_REWARD_NOT_GET = 10130, --- 当前派遣奖励尚不能领取
    RET_REGION_QUEST_PHANTOM_ONLY_UPDATE = 10131, --- 当前接口只能任务魅影更新数据
    RET_REGION_IS_NOT_QUEST_DATA = 10132, --- 当前非任务数据
    RET_REGION_TRY_PET_COUNT_MAX_COUNT = 10133, -- 超过捕捉最大值
    RET_REGION_RANDOM_RULE_ID_NOT_EXIST = 10134, -- 随机规则ID不存在
    RET_REGION_RANDOM_RULE_ID_READY_EXIST = 10135, -- 随机规则已经存在
    RET_REGION_RANDOM_RULE_ID_EXIST_DATA = 10136, --- 数据已经添加激活
    RET_REGION_DAY_SYS_TIME_ERROR = 10137, --- 时间戳不正确 比记录的小
    RET_REGION_NOT_IN_REGION_ONLINE = 10138, -- 当前不在区域联机中
    RET_REGION_MOUNT_READY_GET = 10139, --- 当前坐骑已经获取
    RET_REGION_MOUNT_REASON_NOT_EXIST = 10140, --- 获取坐骑的原因不存在
    RET_REGION_MOUNT_DATA_NOT_EXIST= 10141, --- 不存在坐骑信息
    RET_REGION_MOUNT_LEVEL_UP_ERROR = 10142, --- 当前等级与目标等级相等
    RET_REGION_MOUNT_LEVEL_UP_EXIST = 10143, -- 当前等级已经升级
    RET_REGION_MOUNT_LEVEL_INFO_NOT_EXIST = 10144, -- 不存在等级表信息
    RET_REGION_MOUNT_PRE_LEVEL_ERROR = 10145, -- 前置等级未完成
    RET_REGION_MOUNT_LEVEL_UP_RESOURCE_NOT_ENOUGH = 10146, --- 资源不足
    RET_REGION_MOUNT_CURRENT_LEVEL_UN_LOCK = 10147, -- 当前等级未解锁
    RET_REGION_MOUNT_NOT_EXIST = 10148, -- 坐骑不存在
    RET_REGION_MOUNT_RESOURCE_NOT_ENOUGH = 10149, ---- 资源不足
    RET_REGION_MOUNT_RESOURCE_NOT_MOUNT = 10150, --- 该资源不能绑定坐骑
    RET_REGION_MOUNT_RESOURCE_BIND_MOUNT = 10151, --- 该资源已经绑定该坐骑
    RET_REGION_MOUNT_RESOURCE_NOT_BIND_MOUNT = 10152, --- 该资源未绑定该坐骑
    RET_REGION_TIME_TO_FAST = 10153, --- 时间修改频率过快
    RET_REGION_MOUNT_NOT_OWNED = 10154, --- 未拥有该坐骑
    RET_REGION_SUB_REGION_CANT_FLY = 10155, --- 当前子区域不允许飞行
    RET_REGION_MOUNT_DATA_NOT_EXIST_IN_TABLE = 10156, --- 坐骑表中不存在该坐骑数据
    RET_REGION_MOUNT_FLY_LICENSE_NOT_OWNED = 10157, --- 未拥有飞行许可证

    -- DS集群
    RET_DS_CLUSTER_NOT_EXIST = 11001, --DS不存在
    RET_DS_CLUSTER_NOT_WORKING = 11002, --DS未申请，当前处于free状态
    RET_DS_CLUSTER_ENTER_FAILED = 11003, --DS连接失败，大概率因为DS拒绝连接
    RET_DS_CLUSTER_MAP_NOT_EXIST = 11004, --地图不存在，切换地图失败

    ---- 铸造系统
    RET_BLUE_STATE_NOT_TODOPRODUCED = 12001, ----当前蓝图状态不是未制作，不满足铸造需求
    RET_BLUE_INSUFFICIENT_QUANTITY = 12002, ---- 蓝图数量不足
    RET_BLUE_PRODUCT_COST_NO_ENOUGH = 12003, --- 铸造所需要的货币不足
    RET_BLUE_PRODUCT_RESOURCE_NO_ENOUGH = 12004, --- 铸造所需要的资源不足
    RET_BLUE_NOT_EXIST = 12005, --- 铸造的蓝图不存在
    RET_BLUE_FAIL_REASON_UNKNOW = 12006, ---铸造失败，原因未知
    RET_BLUE_PRODUCT_NOT_COMPLETE = 12007,  --- 铸造的蓝图没有完成
    RET_BLUE_ACCELERATEPRODUCT_FAIL_NOT_DOING = 12008,  --- 加速的蓝图不处于铸造状态
    RET_BLUE_ACCELERATEPRODUCT_FAIL_NOT_EXIST_ACCELERATECOSTTYPE = 12009, -- 不存在加速货币资源
    RET_BLUE_ACCELERATEPRODUCT_COSTTYPE_NO_ENOUGH = 12010, --- 加速所需要的资源货币不足
    RET_BLUE_STATE_NOT_DOING = 12011, ----- 当前蓝图状态不是制作中无法取消制作
    RET_BLUE_SLETEPARAM_WEAPON_IS_NULL = 12012, ---- 选择的武器是空值
    RET_BLUE_SLETEPARAM_MOD_IS_NULL = 12013, ---- 选择的Mod是空值
    RET_BLUE_SLETEPARAM_WEAPONID_NOT_EXIST = 12014, ---- 表里配置的WeaponId在选择武器中不存在
    RET_BLUE_SLETEPARAM_MODID_NOT_EXIST = 12015, ---- 表里配置的MODID在选择Mod中不存在
    RET_BLUE_MOD_COUNT_NOT_ENOUGH = 12016,  ---- 铸造所需要消耗的目标Mod数量不够
    RET_BLUE_MOD_TARGET_COUNT_NOT_ENOUGH = 12017, ---- 客户端选择Mod消耗的目标数量与配置数量对应不上
    RET_BLUE_WEAPON_COUNT_NOT_ENOUGH = 12018, ---- 铸造所需要消耗的武器不存在或者武器的Weaponid无法对应
    RET_BLUE_WEAPON_TARGET_COUNT_NOT_ENOUGH = 12019, ---- 客户端选择武器消耗的目标数量与配置数量对应不上
    RET_BLUE_DRAFT_NUM_ERROR = 12020, ---- 铸造数量不多 小于等于0
    RET_BLUE_WEAPON_REPEAT_UUID = 12021, ---- 铸造武器重复
    RET_BLUE_SELETEPARAM_ERROR = 12022, ---- 铸造选择的参数有问题
    RET_BLUE_ADD_REASON_NOT_EXIST = 12023, ---- 铸造添加原因不存在
    RET_BLUE_ADD_COUNT_ERROR = 12024, ---- 增加数量错误
    RET_BLUE_DRAFT_ID_NOT_EXIST = 12025, ---- 铸造ID不存在
    RET_BLUE_DRAFT_PRODUCT_NUM_MAX = 12026, --- 铸造的数量超过最大值
    RET_BLUE_RELEASE_VERSION_ERROR = 12027, --- 铸造蓝图版本有误
    RET_BLUE_CONVERT_RESOURCE_ID_ERROR = 12028, --- 铸造材料转化资源id有误
    RET_BLUE_CONVERT_RESOURCE_NUM_ERROR = 12029, --- 铸造材料转化资源数量有误
    RET_BLUE_CONVERT_RESOURCE_TYPE_ERROR = 12030, --- 铸造材料转化资源类型有误
    RET_BLUE_CONVERT_CONSUME_MOD_ERROR = 12031, --- 铸造材料转化消耗的mod有误

    -- 抽卡系统
    RET_GACHA_PARAMETER_INVALID = 13001, -- 参数错误
    RET_GACHA_TIME_INVALID = 13002, -- 卡池未开启
    RET_GACHA_NOT_EXIST = 13003, -- 卡池不存在
    RET_GACHA_RESOURCES_NOT_ENOUGH = 13004, -- 资源不足
    RET_GACHA_COUNTS_NOT_ENOUGH = 13005, -- 卡池剩余抽取次数不足
    RET_GACHA_LIMIT_DAY = 13006, -- 今日抽卡次数不足
    RET_GACHA_CONDITION_INVALID = 13007, -- 条件不满足
    RET_GACHA_SINGLE_DRAW_NOT_ALLOWED = 13008, -- 单抽不允许
    RET_GACHA_CANNOT_SELF_SELECT = 13009, -- 卡池无法自选
    RET_GACHA_SELF_SELECT_ITEM_INVALID = 13010, -- 选择的道具无效
    RET_GACHA_SELF_SELECT_INVALID = 13011, -- 自选卡池未选择自选道具
    RET_GACHA_CANNOT_GET_CUMULATIVE_REWARD = 13012, -- 卡池无法领取累抽奖励
    RET_GACHA_NO_MORE_CUMULATIVE_REWARD = 13013, -- 卡池无可领取累抽奖励

    --商城系统
    RET_SHOPITEM_NOT_EXIST = 14001, --商品不存在
    RET_SHOPITEM_REMAIN_PURCHASE_TIMES_EQUAL_ZERO = 14002, --商品购买次数已达上限,不能被购买
    RET_SHOPITEM_REMAIN_PURCHASE_TIMES_NOT_ENOUGH = 14003, --所购买的商品数量大于商品剩余购买次数
    RET_SHOPITEM_MONEY_NEEDED_NOT_ENOUGH = 14004, --购买商品所需货币不足
    RET_SHOPITEM_COUNT_NOT_CORRECT = 14005, --商品数量参数不正确
    RET_SHOPITEM_IS_NOT_VALID = 14006, --商品已下架
    RET_SHOPITEM_TYPE_IS_NOT_VALID = 14007, --商品类型无效
    RET_SHOPITEM_IS_LOCK = 14008, --商品所需历练等级不足
    RET_SHOPITEM_IS_EXCLUSION = 14009, --已购买互斥商品
    RET_SHOPITEM_EXIST_REQUIRE = 14010, --未购买完前置商品
    RET_SHOPITEM_UNIQUE_ALREDAY_OWNED = 14011, --唯一商品已拥有
    RET_SHOPITEM_NOT_USE_COIN1 = 14012, --不属于使用月石购买的商品
    RET_SHOPITEM_TAB_NOT_EXIST = 14013, --商品tab信息有误
    RET_SHOPITEM_TAB_IS_LOCK = 14014, --商品tab未解锁
    RET_SHOPITEM_NOT_REDDOT = 14015, --商品无需增强红点
    RET_SHOPITEM_REDDOT_CLEANED = 14016, --商品增强红点已清除
    RET_SHOPITEM_RAIDPOINT_NOT_ENOUGH = 14017, --商品解锁所需战斗积分不足
    RET_SHOPITEM_VOUCHER_NOT_EXIST = 14018, --抵扣券不存在
    RET_SHOPITEM_VOUCHER_PRICE_TYPE_NOT_MATCH = 14019, --抵扣券价格类型不匹配
    RET_SHOPITEM_VOUCHER_ITEM_ID_NOT_MATCH = 14020, --抵扣券商品id不匹配
    RET_SHOPITEM_VOUCHER_NOT_ENOUGH = 14021, --抵扣券不足
    RET_SHOPITEM_VOUCHER_PURCHASE_LIMIT_NOT_MATCH = 14022, --抵扣券购买次数不匹配
    RET_SHOPITEM_VOUCHER_THRESHOLDPRICE_NOT_MATCH = 14023,--售价未达到抵扣券门槛价格
    -- AvatarStatus
    RET_AVATAR_STATUS_INVALID = 15001, -- 状态切换失败

    ----- 印象系统
    RET_IMPRESSION_NOT_EXIST_PLUS_ID = 16001, ---- 不存在ImPrPlusId
    RET_IMPRESSION_NOT_EXIST_IMPRCHECKID = 16002, ---- 不存在ImCheckId
    RET_IMPRESSION_NOT_EXIST_STORYTALK = 16003, ---- 不存在StoryTalkId
    RET_IMPRESSION_NOT_EXIST_QUESTCHAINID = 16004, ----- 不存在任务链
    RET_IMPRESSION_TALK_FAILER = 16005, ----- 对话不是成功状态
    RET_IMPRESSION_NOT_ISFIRSTCHECK = 16006, ----- 印象系统不是第一次进行检测
    RET_IMPRESSION_REPEAT_ADD = 16007, ---- 重复进行添加
    RET_IMPRESSION_DICENUM_ERROR = 16008, ---- 骰子数量不一致
    RET_IMPRESSION_STORY_RESOURCE_COUNT = 16009, ---- 配置的扣除资源数量有问题
    RET_IMPRESSION_STORY_RESOURCE_NOT_EXIST = 16010, ---- 不存在失败所扣除的目标资源
    RET_IMPRESSION_STORY_COMPLETE = 16011, ----- 该任务节点已经完成
    RET_IMPRESSION_STORY_SUCCESSION = 16012, ----- 该节点已经成功
    RET_IMPRESSION_TALKTRIGGERID_NOT_EXIST = 16013, ----- 该印象系统talktriggerId不存在
    RET_IMPRESSION_TALKTAG_NOT_EXIST = 16014, ----- 不存在台本tag
    RET_IMPRESSION_SHOP_NOT_EXIST = 16015, ---- 印象商品不存在
    RET_IMPRESSION_SHOP_CONDITION_UNLOCK = 16016, ---- 印象商品条件未解锁
    RET_IMPRESSION_SHOP_PURCHASELIMIT = 16017,  ---- 超过最大购买次数
    RET_IMPRESSION_SHOP_REGIONID_ERROR = 16018, ---- 不能在当前区域购买其他区域的商品
    RET_IMPRESSION_SHOP_SUIT_ERROR = 16019, ---- 配表错误 特指不存在该印象商品的表格数据
    RET_IMPRESSION_SHOP_CONSUOME_RESOURCE_ERROR = 16020, ---- 商品消耗资源配表错误
    RET_IMPRESSION_TALKNODE_NONE = 16021, ---- TalkNodeId是空
    RET_IMPRESSION_PLUSID_ERROR = 16022, ---- 印象加值ID不是Int或者小于等于0
    RET_IMPRESSION_PRE_DIALOGUE_ID_ERROR = 16023, --- 印象系统的前置节点错误
    RET_IMPRESSION_PRE_DIALOGUE_ID_NOT_COMPLETE = 16024, --- 印象系统前置节点未完成
    RET_IMPRESSION_CURRENT_DIALOGUE_ID_ERROR = 16025, ---- 印象系统当前节点错误 
    RET_IMPRESSION_CURRENT_DIALOGUE_ID_NOT_COMPLETE = 16026, -- 印象系统当前节点已经存在 
    RET_IMPRESSION_CURRENT_NODE_SUCCESS = 16027, --- 印象节点已经成功
    RET_IMPRESSION_DYNAMIC_DIALOGUE_ID = 16028, --- 动态印象表配置的DialogueId错误
    RET_IMPRESSION_SAVE_LIST_LENGTH_ERROR = 16029, --- 存储长度有问题
    RET_IMPRESSION_END_PRE_NODE_EXIST_SAVE_NODE = 16030, --- 前置节点存在存储节点
    RET_IMPRESSION_END_NODE_EXIST = 16031, --- 后置节点不存在
    RET_IMPRESSION_NEXT_NODE_SAVE_ERROR = 16032, --- 后置节点存储错误
    RET_IMPRESSION_NEXT_NODE_NONE_SAVE = 16033, --- 后置节点都未存储
    RET_IMPRESSION_REGION_USE_NOT_TABLE_EXIST = 16034, --- 区域使用表不存在
    RET_IMPRESSION_PLUS_REGION_ID_NOT_EXIST = 16035, --- 区域加值区域Id不存在
    RET_IMPRESSION_CURRENT_REGION_NOT_USE_PLUS = 16036, --- 当前区域不能加值


    -- 成就
    RET_ACHV_NOT_EXIST_ACHVID = 17001,     ----- 成就不存在
    RET_ACHV_REWARD_HAS_BEEN_CLAIMED = 17002, ------ 成就奖励已经领取
    RET_ACHV_INCOMPLETE = 17003, ------- 成就未完成
    RET_ACHV_NOT_EXIST = 17004, ----- 成就不存在
    RET_ACHVTYPE_NOT_EXIST = 17005,-------成就类型不存在
    RET_ACHVTYPE_HAS_BEEN_CLAIMEDT = 17006,-------当前成就类型无奖励可领取

    -- 梦魇残声（HardBoss）
    RET_HARDBOSS_NOT_EXIST = 18001, -- 梦魇残声（HardBoss）不存在
    RET_HARDBOSS_DIFFICULTY_NOT_EXIST = 18002, -- 梦魇残声（HardBoss）难度不存在
    RET_HARDBOSS_CONDITION_NOT_MEET = 18003, -- 梦魇残声（HardBoss）条件不满足
    RET_HARDBOSS_CANNOT_SINGLE_ENTER_AS_DUNGEON = 18004, -- 梦魇残声（HardBoss）不能以单机副本模式进入

    -- 战斗轮盘
    RET_WHEEL_NOT_EXIST = 19001,  -- 战斗轮盘不存在
    RET_WHEEL_SLOT_NOT_EXIST = 19002,  -- 战斗轮盘槽不存在
    RET_WHEEL_SLOT_REPEAT_SET = 19003,  -- 战斗轮盘槽重复设置
    RET_WHEEL_WEAPON_UNVALID = 19004,  -- 武器被其他角色装备
    RET_WHEEL_REPEAT_RESOURCE = 19005,  -- 不允许战斗道具重复装备
    RET_WHEEL_RESOURCE_USEUP = 19006,  -- 战斗道具携带数量耗尽

    -- 资源
    RET_RESOURCE_NOT_EXIST = 20001, -- 资源不存在
    RET_RESOURCE_NOT_WEAPON = 20002, -- 魅影没有装备武器
    RET_RESOURCE_NOT_IN_WHEEL = 20003, -- 战斗轮盘没有配置该物品
    RET_RESOURCE_NOT_EXIST_CHARID = 20004, -- 无法使用魅影不存在该角色
    RET_RESOURCE_WHEEL_INFO_NOT_EXIST = 20005, -- 战斗轮盘配置不存在
    RET_RESOURCE_COUNT_ERROR = 20006, -- 资源数量有误

    -- 邮箱
    RET_MAIL_NOT_EXIST = 21001, --邮件不存在
    RET_MAIL_INBOX_FULL = 21002, --收件箱已满
    RET_MAIL_STAR_FULL = 21003, --收藏夹已满
    RET_MAIL_PLAYER_NOT_EXIST = 21004, --玩家不存在
    RET_MAIL_REWARD_HAS_GOT = 21005, --奖励已领取过
    RET_MAIL_NOT_NEED_REMARK_READ = 21006, --已读无需重复标记
    RET_MAIL_REWARD_IS_NIL = 21007, --没有奖励
    
    -- 系统引导
    RET_SYSTEMGUIDE_NOT_EXTIST = 22001, --系统引导不存在
    RET_SYSTEMGUIDE_HAS_BEEN_FINISHED = 22002, --系统引导已完成
    
    
    -- 邀约
    RET_PARTY_CHAR_NOT_EXIST = 23001, --角色不存在
    RET_PARTY_TOPIC_NOT_EXIST = 23002, --主题不存在
    RET_PARTY_RESOURCE_NOT_ENOUGH = 23003, --材料不够
    RET_PARTY_CHAR_HAS_UNLOCK = 23004, --角色已经解锁过了
    RET_PARTY_TOPIC_REWARDS_HAS_GOT = 23005, --奖励已领取
    RET_PARTY_TOPIC_NOT_COMPLETE = 23006, --前一话题未完成
    RET_PARTY_TOPIC_IS_UNLOCK = 23007, --话题聊天已解锁
    RET_PARTY_TOPIC_CONDITION_NOT_SATISFY = 23008, --话题聊天解锁条件不满足
    RET_PARTY_TOPIC_IS_LOCKED = 23009, --话题聊天未解锁
    RET_PARTY_TOPIC_IS_COMPETED = 23010, --话题聊天已完成

    -- 体力
    RET_ACTIONPOINT_NOT_ENOUGH = 24001, -- 体力不足
    RET_ACTIONPOINT_HAS_FULL = 24002, -- 体力已满
    RET_ACTIONPOINT_PURCHASE_MAX = 24003, -- 体力购买次数已达上限
    RET_ACTIONPOINT_PURCHASE_RESOURCE_NOT_ENOUGH = 24004, -- 体力购买所需资源不足

    RET_ACTIONPOINT_COST_TO_REWARD_NOT_IN_TIME_RANGE = 24005, -- 体力消耗奖励不在时间范围内
    RET_ACTIONPOINT_COST_TO_REWARD_ALREADY_GOT = 24006, -- 体力消耗奖励已领取
    RET_ACTIONPOINT_COST_TO_REWARD_NOT_ENOUGH = 24007, -- 体力消耗奖励未满足领取条件
    RET_ACTIONPOINT_COST_TO_REWARD_NOT_FOUND = 24008, -- 体力消耗奖励未找到
    RET_ACTIONPOINT_COST_TO_REWARD_CONDITION_CHECK_FAILED = 24009, -- 体力消耗奖励条件检查失败

    RET_DRESSUP_SUIT_CONFIGURATTIONS = 25001, -- 与当前装饰冲突
    RET_DRESSUP_DRESSUP_NOT_EXIST = 25002, --- 配饰不存在
    RET_DRESSUP_SUIT_NOT_EXIST = 25003, -- 不存在配饰页
    RET_DRESSUP_NOT_SUIT_FUNCTION = 25004, -- 服务端不存在设置装饰的方法，表可能发生更改
    RET_DRESSUP_NOT_EQUAL_CURRENT_CHAR = 25005, --- 当前配饰与角色冲突不许装备
    RET_DRESSUP_DATAMGR_CHARACCESSORYID_NOT_EXIST = 25006, --- 服务端存在一个没有配表的配饰

    --玩家相关
    RET_PLAYER_HEADICONID_NOT_EXIST = 26001, --玩家头像id不存在
    RET_PLAYER_SIGNATURE_TOO_LONG = 26002,--玩家个性签名过长
    RET_PLAYER_BIRTHDAY_CHANGE_LIMIT = 26003,--玩家修改生日次数已达上限
    RET_PLAYER_BIRTHDAY_INVALID = 26004,--玩家生日日期不合法
    RET_PLAYER_SIGNATURE_ILLEGAL = 26005,--玩家个性签名违法
    RET_PLAYER_NICKNAME_ILLEGAL = 26006,--玩家昵称违法
    RET_PLAYER_HEADICONID_NOT_POSSESS = 26007,--玩家头像未拥有
    RET_PLAYER_WEITANAME_ILLEGAL = 26008,--前主角昵称违法
    RET_PLAYER_WEITANAME_TOO_LONG = 26009,--前主角昵称过长
    RET_PLAYER_HEADICONID_IS_SAME = 26010,--当前头像已设置
    RET_PLAYER_HEADFRAME_IS_SAME = 26011,--当前头像框已设置
    RET_PLAYER_HEADFRAME_NOT_POSSESS = 26012,--玩家头像框未拥有
    RET_PLAYER_HEADFRAME_NOT_EXIST = 26013,--玩家头像框不存在
    RET_MOBILE_HUD_PLAN_INDEX_ERROR = 26014,--玩家移动端Hud布局方案索引有误
    
    -- 肉鸽玩法
    RET_ROUGELIKE_TREASURE_REPEAT = 27001,  -- 重复获取宝物
    RET_ROUGELIKE_BLESSING_REPEAT = 27002,  -- 重复获取刻印
    RET_ROUGELIKE_ROOM_REPEAT = 27003,  -- 重复进入房间
    RET_ROUGELIKE_SEASON_NOT_EXIST = 27004, -- 赛季不存在
    RET_ROUGELIKE_SEASON_NOT_OPEN = 27005, -- 赛季未开放
    RET_ROUGELIKE_TOKEN_NOT_ENOUGH = 27006, -- 代币不足
    RET_ROUGELIKE_ROOM_PASS_REPEAT = 27007, -- 房间重复通关
    RET_ROUGELIKE_ROOM_CANNOT_ENTER = 27008, -- 房间不可进入
    RET_ROUGELIKE_TREASURE_NOT_EXIT = 27009, -- 宝物不存在
    RET_ROUGELIKE_BLESSING_NOT_EXIT = 27010, -- 刻印不存在
    RET_ROUGELIKE_NOT_VALID = 27011, -- 玩家肉鸽信息不合法
    RET_ROUGELIKE_REFRESHTIME_NOT_ENOUGH = 27012, -- 刷新次数不足
    RET_ROUGELIKE_REFRESH_INVALID = 27013, -- 当前不满足刷新条件
    RET_ROUGELIKE_UPGRADE_NOT_EXIST = 27014, -- 升级的道具不存在
    RET_ROUGELIKE_UPGRADE_MAX_LEVEL = 27015, -- 当前道具已提升至最高等级
    RET_ROUGELIKE_SHOP_NOT_EXIST = 27016, -- 商城信息不存在
    RET_ROUGELIKE_SHOP_ITEM_NOT_EXIST = 27017, -- 商城道具不存在
    RET_ROUGELIKE_SHOP_ITEM_PURCHASE_TIME_NOT_ENOUGH = 27018, -- 商城道具购买次数不足
    RET_ROUGELIKE_TALENT_NOT_EXIST = 27019, -- 天赋不存在
    RET_ROUGELIKE_TALENT_NOT_ENOUGH = 27020, -- 天赋点不足
    RET_ROUGELIKE_TALENT_INVALID = 27021, -- 天赋方案不合法
    RET_ROUGELIKE_TALENT_CANNOT_SAVE = 27022, -- 当前有正在进行中的肉鸽战斗，无法保存天赋方案
    RET_ROUGELIKE_SELECT_NOT_EXIST = 27023, -- 选项不存在
    RET_ROUGELIKE_ROOM_NOT_EXIST = 27024, -- 房间信息错误
    RET_ROUGELIKE_EVENT_NOT_EXIST = 27025, -- 当前没有进行的事件
    RET_ROUGELIKE_DIFFICULTY_NOT_EXIST = 27026, -- 难度不存在
    RET_ROUGELIKE_DIFFICULTY_NOT_UNLOCK = 27027, -- 难度未解锁
    RET_ROUGELIKE_REWARD_ALREADY_GET = 27028, -- 周常奖励已领取
    RET_ROUGELIKE_REWARD_NOT_EXIST = 27029, -- 周常奖励不存在
    RET_ROUGELIKE_TM_REWARD_INVALID_COUNT = 27030, -- 肉鸽盗宝怪奖励次数非法
    RET_ROUGELIKE_REWARD_CANNOT_GET = 27031, -- 不满足领取该奖励条件
    RET_ROUGELIKE_STORY_NOT_EXIST = 27032, -- 剧情不存在
    RET_ROUGELIKE_STORY_NOT_FINISH = 27033, -- 剧情未完成
    RET_ROUGELIKE_CONTRACT_CANNOT_SAVE = 27034, -- 契约保存失败
    RET_ROUGELIKE_CONTRACT_INFO_INVALID = 27035, -- 契约信息错误
    RET_ROUGELIKE_UPGRADE_INFO_ERROR = 27036, -- 升级信息错误
    RET_ROUGELIKE_CANNOT_REFUND = 27037, -- 不能放弃
    RET_ROUGELIKE_MANUAL_REWARD_CANNOT_GET = 27038, -- 图鉴奖励领取失败
    RET_ROUGELIKE_GET_AWARD_EMPTY = 27039, -- 获取奖励结果为空

    -- 匹配
    RET_MATCH_NOT_EXIST = 28001, -- 匹配信息错误
    RET_MATCH_CANNOT_CANCEL = 28002, -- 不能取消匹配
    RET_MATCH_SERVER_CLOSED = 28003, -- 匹配服务器关闭
    RET_MATCH_SERVER_BUSY = 28004, -- 匹配服务器繁忙

    --Friend
    RET_FRIEND_UID_NOT_EXIST = 29001, --好友系统UID不存在
    RET_FRIEND_UID_ALREADY_FRIEND = 29002, --已经是好友了
    RET_FRIEND_UID_ALREADY_SEND_REQUEST = 29003, --已经发生过好友申请了
    RET_FRIEND_UID_SEND_REQUEST_MAX = 29004, --好友申请次数已达上限
    RET_FRIEND_UID_IN_BLACK_LIST = 29005, --好友在黑名单中
    RET_FRIEND_REQUEST_NOT_EXIST = 29006, --好友申请不存在
    RET_FRIEND_HOLD_MAX = 29007, --好友数量已达上限
    RET_FRIEND_REQUEST_TIMEOUT = 29008, --好友申请超时
    RET_FRIEND_BLOCK_MAX = 29009, --黑名单数量已达上限
    RET_FRIEND_STAR_MAX = 29010, --星标好友数量已达上限
    RET_FRIEND_REFRESH_TOO_FAST = 29011, --刷新过快
    RET_FRIEND_OTHER_PARTY_HOLD_MAX = 29012, --对方好友数量已达上限
    RET_FRIEND_UID_IN_OTHER_PARTY_BLACK_LIST = 29013, --在对方黑名单中
    RET_FRIEND_AUTO_AGREE = 29014, --等待对方同意
    RET_FRIEND_CONTENT_CONTAIN_SENSITIVE_WORD = 29015, --内容包含敏感词
    RET_FRIEND_UID_CAN_NOT_ADD_SELF = 29016, --不能添加自己为好友
    RET_FRIEND_UID_ALREADY_IN_BLACK_LIST = 29017, --已经在黑名单中
    RET_FRIEND_OTHER_RECEIVE_REQUEST_MAX_TODAY = 29018, -- 对方今日接收好友申请次数已达上限
    
    -- 聊天
    RET_CHAT_INVALID_CHANNEL = 30001, -- 非法的频道
    RET_CHAT_MESSAGE_EMPTY = 30002, -- 发送的内容不可为空
    RET_CHAT_MESSAGE_TOO_LONG = 30003, -- 发送的内容太长
    RET_CHAT_LIMIT_BLACK = 30004, -- 黑名单中的玩家不可私聊
    RET_CHAT_FORBID_CHAT = 30005, -- 您已被禁言
    RET_CHAT_OFFLINE = 30006, -- 对方已下线，请先申请为好友
    RET_CHAT_ALL_READ = 30007, -- 留言已读
    RET_CHAT_TOO_QUICK = 30008, -- 发送太频繁
    RET_CHAT_CHANNEL_NOT_EXIST = 30009, -- 频道不存在
    RET_CHAT_FRIEND_NOT_EXIST = 30010, -- 好友不存在
    RET_CHAT_CHANNEL_TYPE_INVALID = 30011, -- 频道类型错误
    RET_CHAT_NOT_JOIN_CHANNEL = 30012, -- 未加入聊天频道
    RET_CHAT_CONTENT_CONTAIN_SENSITIVE_WORD = 30013, -- 内容包含敏感词
    RET_CHAT_CONTENT_CONTAIN_SENSITIVE_WORD_ERROR = 30014,  -- 敏感词检测错误，请再次尝试
    RET_CHAT_CHANNEL_STATUS_ERROR = 30015,  -- 频道状态错误
    RET_CHAT_CHANNEL_MEMBER_MAX = 30016,  -- 频道成员已满
    RET_CHAT_CHANNEL_SWITCH_TOO_QUICK = 30017,---切频道太快了
    
    -- 奖励
    RET_REWARD_GENERATE_FAILED = 31001, -- 奖励生成失败

    --Pet
    RET_COST_PET_NOT_EXIST = 32001, --消耗的宠物不存在
    RET_PET_NOT_EXIST = 32002, --宠物不存在
    RET_PET_NOT_EXIST_IN_EXCEL = 32003, --消耗的宠物不存在于表中
    RET_PET_LEVEL_MAX = 32004, --宠物等级已满
    RET_PET_LEVEL_NOT_ENOUGH = 32005, --宠物等级不足
    RET_PET_ID_NOT_EQUAL = 32006, --宠物ID不一致
    RET_PET_NEED_BREAK = 32007, --宠物需要突破
    RET_PET_ALREADY_EQUIP = 32008, --宠物已装备
    RET_COST_PET_EQUIP = 32009, --消耗的宠物已装备
    RET_PET_ID_EQUAL = 32010, --宠物ID相同
    RET_COST_PET_LOCK = 32011, --消耗的宠物已锁定
    RET_COST_PET_NOT_IN_CONSUME_PETID = 32012, --消耗的宠物不在消耗列表中
    RET_PET_BREAK_RESOURCE_NOT_ENOUGH = 32013, --突破资源不足
    RET_PET_ENTRYUP_ENTRY_INVALID = 32016, --词条升级词条无效
    RET_PET_ENTRYUP_CONSUME_COUNT_NOT_ENOUGH = 32017, --词条升级耗材数量不足
    RET_PET_ENTRYUP_LEVLE_MAX = 32018, --词条等级已满
    RET_PET_ENTRYREPLACE_ENTRY_INVALID = 32019, --词条替换词条无效
    RET_PET_ENTRYREPLACE_RESOURCE_NOT_ENOUGH = 32020, --词条替换资源不足
    RET_PET_BREAK_MAX = 32021, --宠物突破已满
    RET_PET_NICKNAME_ILLEGAL = 32022, --宠物昵称违法
    RET_PET_NAME_TOO_LONG = 32023, --宠物昵称过长
    RET_PET_EXP_RESOURCE_NOT_ENOUGH = 32024, --宠物经验资源不足
    RET_PET_CONSUMABLE = 32025, --素材魔灵
    RET_PET_ENTRY_NOT_EXIST = 32026, --词条不存在
    RET_PET_ENTRY_ALREADY_EXIST = 32027, --词条已存在
    RET_PET_EXP_RESOURCE_NOT_EXIST_IN_EXCEL = 32028, --经验资源不存在于表中
    

    -- 快捷消息
    RET_QUICK_MESSAGE_INDEX_INVALID = 33001, -- 快捷消息索引错误
    RET_QUICK_MESSAGE_CONTENT_INVALID = 33002, -- 超出快捷消息最大长度

    -- 表情包
    RET_EMOTION_ID_INVALID = 34001, -- 表情包ID错误
    RET_EMOTION_ID_EXIST = 34002, -- 表情包ID已存在
    RET_EMOTION_ID_NOT_EXIST = 34003, -- 表情包ID不存在

    --动态事件
    RET_DYNAMICQUEST_NOT_EXIST = 35001,--动态事件状态不存在
    RET_DYNAMICQUEST_INACTIVE = 35002,--动态事件状态未激活
    RET_DYNAMICQUEST_INCD = 35003,--动态事件处于CD
    RET_DYNAMICQUEST_INGCD = 35004,--玩家处于GCD
    RET_DYNAMICQUEST_DAYLIMIT = 35005,--当日限次动态事件已达上限
    RET_DYNAMICQUEST_COMPLETENUMLIMIT = 35006,--当前动态事件完成次数已达上限
    RET_DYNAMICQUEST_JUDGE_FAIL = 35007,--动态事件概率判定失败
    RET_DYNAMICQUEST_TRIGGERTYPE_ERROR = 35008,--动态事件触发类型的参数不正确
    RET_DYNAMICQUEST_DOING = 35009,--动态事件状态进行中
    RET_DYNAMICQUEST_CHANCE_CONDITION_FAIL = 35010,--动态事件触发条件不满足
    RET_DYNAMICQUEST_NOT_IN_DISPATCHLIST = 35011,--动态事件不在当前派遣列表中，无法触发
    RET_DYNAMICQUEST_PLAYER_LEVEL_ERROR = 35012,--动态事件所需玩家等级不匹配，无法触发

    --活动相关
    RET_DAILY_LOGIN_NOT_EXIST = 36001, -- 每日登录活动不存在
    RET_DAILY_LOGIN_ALREADY_SIGN_IN = 36002, -- 已经签到
    RET_DAILY_LOGIN_REWARD_NOT_EXIST = 36003, -- 每日登录奖励不存在
    RET_DAILY_LOGIN_COUNT_NOT_ENOUGH = 36004, -- 每日登录次数不足
    RET_DAILY_LOGIN_NOT_IN_TIME = 36005, -- 不在活动时间内
    RET_DAILY_LOGIN_ALREADY_GET_REWARD = 36006, -- 已经领取奖励
    RET_PhaseQuest_NOT_EXIST = 36007, -- 任务不存在
    RET_PhaseQuest_REWARD_ALREADY_GOT = 36008, -- 任务奖励已领取
    RET_PhaseQuest_NOT_COMPLETE = 36009, -- 任务未完成
    RET_PhaseQuest_REWARD_TIME_OUT = 36010, -- 任务奖励已过期
    RET_PhaseQuest_NOT_IN_TIME = 36011, -- 不在任务时间内

    --组队相关
    RET_TEAM_NOT_EXIST = 37001, -- 组队不存在
    RET_TEAM_MEMBER_NOT_EXIST = 37002, -- 组队成员不存在
    RET_TEAM_MEMBER_NOT_LEADER = 37003, -- 不是队长
    RET_TEAM_INVATE_NOT_EXIST = 37004, -- 邀请不存在
    RET_TEAM_FULL = 37005, -- 队伍已满
    RET_TEAM_ALREADY_IN_TEAM = 37006, -- 已经在队伍中
    RET_TEAM_MEMBER_EMPTY = 37008, -- 队伍成员为空
    RET_TEAM_INVATE_SELF = 37009, -- 不能邀请自己
    RET_TEAM_INVATE_MAX = 37010, -- 邀请次数已达上限
    RET_TEAM_AVATAR_STATUS_CHACK_FAILED = 37011, -- 当前状态不允许该操作
    RET_TEAM_INVATE_AUTO_REFUSE = 37012, -- 自动拒绝
    RET_TEAM_ORIENTATION_CHECK_FAILED = 37013, -- 组队倾向检查失败
    RET_TEAM_DUNGEON_CHECK_FAILED = 37014, -- 团队有成员不满足副本进入条件
    RET_TEAM_IN_DUNGEON = 37015, -- 队伍正在副本/匹配中
    RET_TEAM_MATE_REFUSED = 37016, -- 队友拒绝挑战邀请
    RET_TEAM_CANNOT_JOIN = 37017,  -- 当前队伍无法加入
    RET_TEAM_KICK_SELF = 37018,  -- 不能踢出自己
    RET_TEAM_CANNOT_VOTING = 37019,  -- 当前无法投票

    --区域刷怪
    RET_REGION_SPECIAL_MONSTER_PROBABILITY_FAIL = 38001, -- 区域特殊怪物概率失败
    RET_REGION_SPECIAL_MONSTER_RULE_NOT_EXIST = 38002, -- 区域特殊怪物规则不存在
    RET_REGION_SPECIAL_MONSTER_MAX_COUNT = 38003, -- 区域特殊怪物数量已达上限
    RET_REGION_SPECIAL_MONSTER_NOT_IN_REGION = 38004, -- 区域特殊怪物不在区域内
    RET_REGION_SPECIAL_MONSTER_CONDITION_FAILED = 38005, -- 区域特殊怪物 触发条件失败
    RET_REGION_SPECIAL_MONSTER_CD = 38006, -- 区域特殊怪物CD中
    --CDK
    RET_CDK_USE_LIMIT = 39003, -- CDK使用次数已达上限
    RET_CDK_CODE_INVALID = 39004, -- CDK无效
    RET_CDK_CHANNEL_CHECK_FAILED = 39005, -- CDK渠道校验失败
    RET_CDK_TIME_CHECK_FAILED = 39006, -- CDK时间校验失败
    RET_CDK_USED = 39007, -- CDK已被使用
    RET_CDK_USED_BY_OTHER = 39008, -- CDK已被其他玩家使用
    RET_CDK_USED_BY_MINE = 39009, -- CDK已被自己使用
    
    --百科词条
    RET_WIKI_ENTRY_REWARD_NOT_EXIST = 40001, -- 奖励不存在
    RET_WIKI_ENTRY_CANT_GET = 40002, -- 不满足领取条件
    RET_WIKI_ENTRY_CANT_GET_IN_DUNGEON = 40003, -- Dungeon中不能领取奖励
    RET_WIKI_ENTRY_NOT_EXIST = 40004, -- 词条不存在
    RET_WIKI_ENTRY_TEXT_NOT_UNLOCK = 40005, -- 词条未解锁

    --大秘境
    RET_ABYSS_NOT_EXIST = 50001,--大秘境不存在
    RET_ABYSS_TEAM_PARAM_NOT_CORRECT = 50002,--大秘境配队数量不正确
    RET_ABYSS_TEAM_REPEAT = 50003,--大秘境配队角色存在重复
    RET_ABYSS_TEAM_NOT_OWNED = 50004,--大秘境配队角色未拥有
    RET_ABYSS_LEVEL_NOT_EXIST = 50005,--大秘境层数不存在
    RET_ABYSS_DUNGEON_NOT_EXIST = 50006,--大秘境关卡不存在
    RET_CURRENT_ABYSS_DUNGEON_IS_PASS = 5007,--当前副本已通关
    RET_ABYSS_PROGRESS_NOT_CORRECT = 50008,--大秘境进度不正确
    RET_ABYSS_TEAM_NOT_SELECT = 50009,--大秘境未配队
    RET_ABYSS_TEAM_NO_CHAR = 50010,--大秘境配队无角色
    RET_ABYSS_TEAM_NO_MELEEWEAPON = 50011,--大秘境配队无近战
    RET_ABYSS_TEAM_NO_RANGEDWEAPON = 50012,--大秘境配队无远程
    RET_ABYSS_TEAM_PHANTOM_NO_WEAPON = 50013,--大秘境配队魅影无武器
    RET_ABYSS_TEAM_PET_NOT_OWNED = 50014,--大秘境配队宠物未拥有
    RET_ABYSS_TEAM_IS_LOCKED = 50015,--大秘境配队已锁定
    RET_ABYSS_TEAM_IS_UNLOCK = 50016,--大秘境配队未锁定
    RET_ABYSS_SEASON_NOT_CORRECT = 50017,--大秘境赛季不匹配
    RET_LAST_ABYSS_NOT_PASS = 50018,--上一座大秘境未通关
    RET_ABYSS_STAR_ERROR = 50019,--大秘境星数有误
    RET_ABYSS_REWARD_IS_GOT = 50020,--大秘境奖励已领取
    RET_ABYSS_PASSTIME_ERROR = 50021,--大秘境房间通过时间有误
    RET_ABYSS_NOT_LOOP= 50022,--大秘境不是无尽关
    RET_ABYSS_ATTRTYPE_ERROR= 50023,--大秘境选择的属性有误

    -- 委托密函
    RET_WALNUT_NOT_ENOUGH = 51001, -- 委托密函数量不足
    RET_WALNUT_NOT_VALID = 51002, -- 当前副本无法使用该委托密函
    RET_WALNUT_CANNOT_OPEN_OUT_DUNGEON = 51003, -- 不能在副本外使用委托密函
    RET_WALNUT_DUNGEON_TYPE_NOT_VALID = 51004, -- 副本类型无法使用委托密函
    RET_WALNUT_SELECT_INDEX_OUT_OF_RANGE = 51005, -- 选择索引超出范围
    RET_WALNUT_REWARD_GET_FAILED = 51006, -- 获取委托密函奖励失败
    RET_WALNUT_CANNOT_SELECT_NOW = 51007, -- 当前无法选择委托密函
    RET_WALNUT_DUNGEON_NOT_OPEN = 51008, -- 该副本未开启委托密函
    RET_WALNUT_REWARD_CANNOT_SELECT_NOW = 51009, -- 当前无法选择委托密函奖励
    RET_WALNUT_VERSION_INVALID = 51010, -- 委托密函版本不合法

    -- 区域联机
    RET_ONLINE_REGION_NOT_EXIST = 52001, -- 区域联机位面不存在
    RET_ONLINE_REGION_STATUS_ERROR = 52002, -- 区域联机位面状态错误
    RET_ONLINE_REGION_NO_CURRENT_CHARACTER = 52003, -- 区域联机位面没有当前角色
    RET_ONLINE_REGION_LOCK = 52004, -- 区域联机位面未解锁
    RET_ONLINE_REGION_ALREADY_ENTER = 52005, -- 重复进入
    RET_ONLINE_REGION_ALREADY_LEAVE = 52006, -- 重复离开
    RET_ONLINE_REGION_CLOSE = 52007, -- 区域联机位面已关闭
    RET_ONLINE_REGION_SENDER_NOT_EXIST = 52008, -- 区域不存在该玩家
    RET_ONLINE_NOT_CREATE_ITEM = 52009, --区域不存在该创建的机关物品
    RET_ONLINE_NOT_CREATE_TARGET_ITEM = 52010, -- 当前区域玩家未创建目标物品
    RET_ONLINE_NOT_EXIST_INTERACTIVE_ID= 52011, -- 不存在该唯一ID机关
    RET_ONLINE_ITEM_READY_USE_PLAYER = 52012, ---该机关已经被他人占用
    RET_ONLINE_OWNER_NOT_USE_ITEM = 52013, -- 物品创建者不能使用机关
    RET_EXIST_USE_REGION_IETM_REQUEST = 52015, -- 存在物品使用请求
    RET_ONLINE_REQUEST_TIMEOUT = 52016, -- 请求超时
    RET_ONLINE_NOT_EXIST_USE_RESOURCE_ID = 52017, --- 不存在使用的资源ID
    RET_ONLINE_NOT_CREATE_MECHANISM = 52018, -- 不能创建机关
    RET_ONLINE_NOT_CREATE_TARGET_MOUNT = 52019, --- 没有创建该目标坐骑
    RET_ONLINE_GLOBAL_ITEM_NOT_EXIST = 52020, --- 不存在该索引的全局机关
    RET_ONLINE_OWNER_NOT_ONLINE = 52021, --- 主机玩家不在线
    RET_ONLINE_RECEIVE_ONT_ONLINE = 52022, --- 消息接收方不在线
    RET_ONLINE_LEAVE_ITEM_NOT_STATE_COMPONENT = 52023, --- 不存在交互信息
    RET_ONLINE_EXIST_USE_REGION_IETM_REQUEST = 52024, --- 纯在申请请求 耐心等待
    RET_ONLINE_REQUEST_REFRUSE_USE = 52025, --- 请求被对方拒绝
    RET_ONLINE_MOUNT_NOT_USE_ITEM = 52026, --- 坐骑不能使用该机关
    RET_ONLINE_CREATE_CHANNEL_FAIL = 52027, --- 区域联机创建频道失败
    RET_ONLINE_REGION_FULL = 52028, --- 区域联机位面已满
    RET_REGION_ONLLINE_NOT_SHOW_WEAPON_TYPE = 52029, --- 区域联机位面不显示武器类型
    RET_ONLINE_REGION_SWITCH_CD = 52030, --- 区域联机位面切换CD中
    RET_ONLINE_REGION_CHANNEL_NOT_EXIST = 52031,  -- 区域联机频道不存在
    RET_ONLINE_REGION_ALREADY_IN = 52032,  -- 已经在区域联机频道

    -- 角色试玩
    RET_CHARTRIAL_INVALID_DUNGEON = 53001, -- 副本类型不为试玩类型
    RET_CHARTRIAL_INVALID_EVENT = 53002, -- 试玩活动不存在
    RET_CHARTRIAL_NOT_OPEN = 53003, -- 试玩活动未开启
    RET_CHARTRIAL_ALREADY_GET_REWARD = 53004, -- 已经领取奖励
    RET_CHARTRIAL_NOT_FINISH = 53005, -- 试玩活动未完成

    -- LevelSequence
    RET_LEVELSEQUENCE_REGION_ID_CHECK_FAILED = 54001, -- LevelSequence region Id 校验失败
    RET_LEVELSEQUENCE_RECORDER_ID_CHECK_FAILED = 54002, -- LevelSequence recorder Id 校验失败
    RET_LEVELSEQUENCE_STATE_ID_CHECK_FAILED = 54003, -- LevelSequence state Id 校验失败

    --图鉴陈列室
    RET_ARCHIVE_NOT_EXIST = 55001,  --图鉴不存在
    RET_ARCHIVE_COUNT_ERROR = 55002,    --图鉴数量有误
    RET_ARCHIVE_REWARD_IS_GOT = 55003,  --图鉴奖励已获取

    --钓鱼系统
    RET_FISHING_SPOT_ERROR = 56001, --钓鱼点参数有误，不存在
    RET_FISHING_ROD_ERROR = 56002,  --鱼竿参数有误，不存在
    RET_FISHING_LURE_ERROR = 56003, --鱼饵参数有误，不存在
    RET_FISHING_SPOT_NO_FISH = 56004,   --钓鱼点鱼已钓完
    RET_FISHING_ACHV_NOT_EXIST = 56005,   --钓鱼成就不存在
    RET_FISHING_ACHV_NOT_COMPLETE = 56006,   --钓鱼成就未完成
    RET_FISHING_ACHV_REWARD_ALREADY_GOT = 56007,   --钓鱼成就奖励已领取
    RET_FISHING_FISH_SIZE_NOT_EXIST = 56008, -- 钓鱼尺寸不存在
    RET_FISHING_FISH_READY_LOCK = 56009, -- 鱼资源已经上解锁
    RET_FISHING_FISH_READY_UN_LOCK = 56010, -- 鱼支援已经解锁


    --Avatar相关
    RET_AVATAR_LEVEL_REWARD_GOT = 57001, -- 已领取等级奖励
    RET_AVATAR_LEVEL_REWARD_NOT_VALID = 57002, -- 等级奖励不可领取

    RET_DETECTIVE_GAME_INFER_FAILED = 58001, -- 推理失败
    RET_DETECTIVE_GAME_COMMIT_FAILED = 58002, -- 提交失败
    RET_DETECTIVE_GAME_ANSWER_NOT_EXIST = 58003, -- 线索不存在
    RET_DETECTIVE_GAME_NO_RESULT = 58004, -- 无结果
    RET_DETECTIVE_GAME_CURRENT_QUESTION_NOT_EXIST = 58005, -- 无问题

    -- 阵容预设
    RET_SQUAD_INDEX_ALREADY_EXIST = 59001, -- 阵容索引已存在
    RET_SQUAD_CHAR_NOT_EXIST = 59002, -- 角色不存在
    RET_SQUAD_MODSUIT_INVALID = 59003, -- 角色Mod方案不存在
    RET_SQUAD_MELEEWEAPON_NOT_EXIST = 59004, -- 近战武器不存在
    RET_SQUAD_MELEEWEAPON_MODSUIT_INVALID = 59005, -- 近战武器Mod方案不存在
    RET_SQUAD_RANGEDWEAPON_NOT_EXIST = 59006, -- 远程武器不存在
    RET_SQUAD_RANGEDWEAPON_MODSUIT_INVALID = 59007, -- 远程武器Mod方案不存在
    RET_SQUAD_PET_NOT_EXIST = 59008, -- 宠物不存在
    RET_SQUAD_WHEEL_NOT_EXIST = 59009, -- 轮盘方案不存在
    RET_SQUAD_PHANTOM_NOT_EXIST = 59010, -- 魅影不存在
    RET_SQUAD_PHANTOMWEAPON_NOT_EXIST = 59021, -- 魅影武器不存在
    RET_SQUAD_WEAPON_NOT_EXIST = 59011, -- 武器不存在
    RET_SQUAD_WEAPON_MODSUIT_INVALID = 59012, -- 武器Mod方案不存在
    RET_SQUAD_INDEX_NOT_EXIST = 59013, -- 阵容索引不存在
    RET_SQUAD_KEY_INVALID = 59014, -- 阵容参数无效
    RET_SQUAD_KEY_NOT_EXIST = 59015, -- 阵容缺少参数
    RET_SQUAD_CANNOT_DELETE_LAST_SQUAD = 59016, -- 不能删除最后一个阵容
    RET_SQUAD_MAX_EXCEEDED = 59017, -- 阵容数量超过上限
    RET_SQUAD_CHAR_DUPLICATE = 59018, -- 角色存在重复
    RET_SQUAD_WEAPON_TAG_INVALID = 59019, -- 武器标签非法
    RET_SQUAD_WEAPON_DUPLICATE = 59020, -- 武器存在重复


    -- 个人主页
    RET_PERSONAL_INFO_CHAR_NOT_EXIST = 60001, -- 角色不存在
    RET_PERSONAL_INFO_APPEARANCE_NOT_EXIST = 60002, -- 外观不存在
    RET_PERSONAL_INFO_MOD_SUIT_NOT_EXIST = 600003, -- Mod方案不存在
    RET_PERSONAL_INFO_CHAR_DISPLAY_EXIST = 60004, -- 角色展示已存在
    RET_PERSONAL_INFO_CHAR_DISPLAY_NOT_EXIST = 60005, -- 角色展示不存在
    RET_PERSONAL_INFO_DISPLAY_MAX = 60006, -- 展示数量已达上限
    RET_PERSONAL_INFO_WEAPON_NOT_EXIST = 60007, -- 武器不存在
    RET_PERSONAL_INFO_WEAPON_DISPLAY_EXIST = 60008, -- 武器展示已存在
    RET_PERSONAL_INFO_WEAPON_DISPLAY_NOT_EXIST = 60009, -- 武器展示不存在
    RET_PERSONAL_INFO_NOT_FIND = 60010, -- 未找到该玩家信息

    -- 月卡
    RET_MONTHCARD_NOT_OPEN = 61001, -- 月卡未开启
    RET_MONTHCARD_BUY_MAX = 61002, -- 月卡购买次数达到上限
    RET_MONTHCARD_NO_GOODS_ID = 61003, -- 月卡没有GoodsId

    
    RET_BATTLE_PASS_TASK_TYPE_ERROR = 62001, -- 战令任务类型错误
    RET_BATTLE_PASS_TASKID_ERROR = 62002, -- 战令任务ID错误
    RET_BATTLE_PASS_TASK_NOT_COMPLETE = 62003, -- 战令任务未完成
    RET_BATTLE_PASS_TASK_REWARDS_GOT = 62004, -- 战令任务奖励已领取
    RET_BATTLE_PASS_LEVEL_ERROR = 62005, -- 战令等级错误
    RET_BATTLE_PASS_VERSION_ERROR = 62006, -- 战令版本错误
    RET_BATTLE_PASS_RANK2_NOT_UNLOCK = 62007, -- 战令等级未解锁
    RET_BATTLE_PASS_LEVEL_NOT_ENOUGH = 62008, -- 战令等级不足
    RET_BATTLE_PASS_LEVEL_REWARDS_GOT = 62009, -- 战令等级奖励已领取
    RET_BATTLE_PASS_NOT_EXIST = 62010, -- 战令不存在
    RET_BATTLE_PASS_PET_CLAIMED = 62011, -- 宠物已领取
    RET_BATTLE_PASS_LAST_VERSION_NOT_EXIST = 62012, -- 上一版本战令不存在
    RET_BATTLE_PASS_PET_NOT_EXIST = 62013, -- 宠物不存在
    RET_BATTLE_PASS_PAY_CHECK_FAILED = 62014, -- 战令购买检查失败
    RET_BATTLE_PASS_PAY_RESOURCE_NOT_ENOUGH = 62015, -- 战令购买资源不足
    
    -- 充值
    PAY_ORDER_GEN_FAILED = 63001, -- 订单生成失败
    PAY_GOODS_NOT_EXIST = 63002, -- 充值道具不存在
    PAY_ORDER_FAILED = 63003, -- 订单失败
    PAY_ITEM_CANNOT_PURCHASE = 63004, -- 道具不可购买
    PAY_ORDER_IN_PROCESS = 63005, -- 订单正在处理中

    -- Mod 手册任务
    RET_MOD_BOOK_QUEST_NOT_EXIST = 64001, -- Mod手册任务不存在
    RET_MOD_BOOK_QUEST_NOT_COMPLETE = 64002, -- Mod手册任务未完成
    RET_MOD_BOOK_QUEST_REWARD_GOT = 64003, -- Mod手册任务奖励已领取
    RET_MOD_BOOK_QUEST_LOCK = 64004, -- Mod手册任务未解锁
    RET_MOD_BOOK_QUEST_PHASEID_NOT_EXIST = 64005, -- Mod手册任务阶段Id不存在
    RET_MOD_BOOK_QUEST_PHASE_REWARD_GOT = 64006, -- Mod手册任务阶段奖励已领取

    --止流活动
    RET_ZHILIU_NOT_EXIST = 65001, -- 止流活动不存在
    RET_ZHILIU_SUBMIT_RESOURCE_ERROR = 65002, -- 止流活动提交资源错误
    RET_ZHILIU_SUBMIT_RESOURCE_NOT_ENOUGH = 65003, -- 止流活动提交资源不足
    RET_ZHILIU_FINAL_REWARD_GOT = 65004, -- 止流活动最终奖励已领取
    
    -- 历练等级活动
    RET_ACTIVITY_PLAYER_LV_REWARD_NOT_EXIST = 66001, -- 等级奖励不存在
    RET_ACTIVITY_PLAYER_LV_REWARD_HAS_GOT = 66002, -- 等级奖励已领取
    RET_ACTIVITY_NOT_OPEN = 66003, -- 活动未开启
    RET_PLAYER_LV_NOT_ENOUGH = 66004, -- 玩家等级不足

    RET_StarterQuest_NOT_EXIST = 67001, -- 新手任务不存在
    RET_StarterQuest_REWARD_ALREADY_GOT = 67002, -- 新手任务奖励已领取
    RET_StarterQuest_NOT_COMPLETE = 67003, -- 新手任务未完成

    RET_MIDTERM_FIND_EVENTMAIN_NIL = 68001, -- 中期活动不存在
    RET_MIDTERM_REWARD_TIMEOUT = 68002, -- 中期活动奖励领取时间已结束
    RET_MIDTERM_REWARDS_NIL = 68003, -- 中期活动没有奖励可领取
    RET_MIDTERM_NO_SCORES_TO_GET = 68004, -- 中期活动没有积分可领取
    RET_MIDTERM_CONSTANT_ERROR = 68005, -- 中期活动常量配置错误
    RET_MIDTERM_TASK_NO_REWARD = 68006, -- 中期活动没有任务奖励可领取
    RET_MIDTERM_NEED_GETREWARD_FIRST = 68007, -- 需要先领取积分结算奖励
    RET_MIDTERM_TASK_ERROR = 68008, -- 中期活动没有该任务
    RET_MIDTERM_ADDNUM_NIL = 68009, -- 中期活动任务奖励数值错误
    RET_MIDTERM_TASKDATA_NIL = 68010, -- 中期活动任务配置错误
    RET_MIDTERM_NO_ACHV_SCORES_TO_GET = 68011, -- 中期活动没有成就积分可领取
    RET_MIDTERM_ACHV_NO_REWARD = 68012, -- 中期活动没有成就奖励可领取
    RET_MIDTERM_DATA_NIL = 68013, -- 中期活动数据不存在
    RET_MIDTERM_NOT_OPEN = 68014, -- 中期活动未开启
    RET_MIDTERM_TASK_NOT_COMPLETE = 68015, -- 中期活动任务未完成
    RET_MIDTERM_TASK_REWARD_REPEAT = 68016, -- 中期活动任务重复领奖


    RET_PAOTAI_INVALID_ID = 69001, -- 炮台活动无效参数Id
    RET_PAOTAI_INVALID_DUNGEON = 69002, -- 炮台活动副本类型配置错误
    RET_PAOTAI_INVALID_EVENT = 69003, -- 炮台活动Id不匹配
    RET_PAOTAI_NOT_OPEN = 69004, -- 炮台活动未开启
    RET_PAOTAI_ID_NOT_UNLOCK = 69005, -- 炮台活动当前序号关卡未解锁
    RET_PAOTAI_INVALID_SCOREIDX = 69006, -- 炮台活动无效积分参数
    RET_PAOTAI_REWARD_TIMEOUT = 69007, -- 炮台活动奖励领取超时
    RET_PAOTAI_SCORE_NOT_ENOUGH = 69008, -- 炮台活动积分条件不满足
    RET_PAOTAI_SCORE_REWARDED = 69009, -- 炮台活动积分奖励已领取
    RET_PAOTAI_SCORE_NO_REWARD = 69010, -- 炮台活动没有积分奖励可领取
    RET_PAOTAI_BUFF_NOT_UNLOCK = 69011, -- 炮台活动BUFF未解锁
    RET_PAOTAI_INVALID_CONSTANT = 60012, -- 炮台活动常量错误
    RET_PAOTAI_EVENTDATA_NOT_EXIST = 60013, -- 炮台活动数据不存在
    RET_PAOTAI_PAOTAIDATA_NOT_EXIST = 60014, -- 炮台关卡数据不存在
    RET_PAOTAI_PREDUNGEON_NOT_UNLOCK = 60015, -- 炮台关卡前置关卡未通关
    RET_PAOTAI_BUFF_INVALID = 60016, -- 炮台buff列表不合法

    RET_ACTIVITY_CONDITION_REWARD_NOT_EXIST = 70001, --条件发奖活动不存在
    RET_ACTIVITY_CONDITION_REWARD_NOT_COMPLETE = 70002, --条件发奖活动未完成
    RET_ACTIVITY_CONDITION_REWARD_HAS_CLAIM = 70003, -- 条件发奖活动已领取

    RET_ELITERUSHTIMES_NOT_ENOUGH = 71001, --号令者连战副本次数不足

    RET_COMMONQUEST_INVALID_QUEST = 72001, -- 活动任务无效任务id
    RET_COMMONQUEST_INVALID_EVENTID = 72002, -- 活动任务无效活动id
    RET_COMMONQUEST_REWARD_TIMEOUT = 72003, -- 活动任务不在奖励领取时间内
    RET_COMMONQUEST_DATA_NIL = 72004, -- 活动任务数据空
    RET_COMMONQUEST_QUEST_NOT_EXIST = 72005, -- 活动任务任务数据不存在
    RET_COMMONQUEST_REWARD_GOT = 72006, -- 活动任务奖励领已领取
    RET_COMMONQUEST_NOT_COMPLETE = 72007, -- 活动任务未完成
    RET_COMMONQUEST_NO_REWARD_TO_GET = 72008, -- 活动任务没有奖励可领取
    RET_COMMONQUEST_INVALID_PHASEID = 72009, -- 活动任务无效阶段id
    RET_COMMONQUEST_INVALID_REWARDID = 72010, -- 活动任务无效奖励id
    RET_COMMONQUEST_NOT_FINISH = 72011, -- 活动任务未完成
    RET_COMMONQUEST_NOT_OPEN = 72012, -- 活动任务未开启
    RET_COMMONQUEST_FINISHREWARD_GOT = 72013, -- 活动任务完成奖励已领取
    RET_COMMONQUEST_CANT_REWARD = 72014, -- 活动不可领奖

    RET_COMMUNITY_SERVER_INVALID = 73001,--未配置服务器社媒
    RET_COMMUNITY_NOT_IN_SERVER = 73002,--当前服务器不包含此社媒
    RET_COMMUNITY_ID_ERROR = 73003,--该社媒不存在
    RET_COMMUNITY_IS_REWARDMARK = 73004,--该社媒需要注册
    RET_COMMUNITY_IS_FOLLOWED = 73005,--该社媒已关注
    RET_COMMUNITY_REWARD_CANT_GET = 73006,--该社媒奖励不可领取

    RET_TEMPLE_INVALID_LEVEL_ID = 74001, --神庙无效关卡id
    RET_TEMPLE_INVALID_EVENT_ID = 74002, --神庙无效活动id
    RET_TEMPLE_REWARDED = 74003, --神庙奖励已领取
    RET_TEMPLE_STARS_NO_ENOUGH = 74004, --神庙星数进度不足
    RET_TEMPLE_INVALID_DUNGEON = 74005, --神庙无效副本
    RET_TEMPLE_NOT_OPEN = 74006, --神庙活动未开启
    RET_TEMPLE_LEVEL_NOT_OPEN = 74007, --神庙关卡未开启
    RET_TEMPLE_INVALID_REWARD_ID = 74008, --神庙无效奖励keyid
    RET_TEMPLE_NO_REWARD_TO_GET = 74009, --神庙没有奖励可领取
    RET_NOT_REWARD_TIME = 74010, --不是奖励领取时间

    RET_FEINA_PROGRESS_ERROR = 75001, -- 菲娜进度错误
    RET_FEINA_DATA_NOT_EXIST = 75002, -- 菲娜睡觉不存在
    RET_FEINA_CURRENT_STATE_NOT_CAN_REWARD = 75003, -- 当前状态不能领取奖励
    RET_FEINA_GET_ALL_REWARD_IS_EMPTY = 75004, -- 领取奖励为空

    RET_CATNAME_ILLEGAL = 76001, -- 猫猫名字违法

    RET_WYS_INVALID_EVENT_ID = 77001, -- 无由生活动活动Id无效
    RET_WYS_INVALID_LEVEL_ID = 77002, -- 无由生活动无效levelId
    RET_WYS_LEVEL_NOT_UNLOCK = 77003, -- 无由生活动当前Level未解锁
    RET_WYS_EVENT_DATA_NIL = 77004, -- 无由生活动活动数据nil
    RET_WYS_NOT_COMPLETED = 77005, -- 无由生活动奖励任务未完成
    RET_WYS_REWARD_REPEAT = 77006, -- 无由生活动领奖重复
    RET_WYS_REWARD_IS_EMPTY = 77007, -- 无由生活动奖励空
    RET_WYS_NOT_OPEN = 77008, --无由生活动未开启
    RET_WYS_SQUAD_INVALID = 77009, -- 无由生副本阵容无效

    RET_DOUBLEMODDROP_SET_FIRST_REPEAT = 78001, -- 双倍掉落首次标识设置重复

    RET_THEATER_INVALID_TASK = 79001, -- 剧场活动无效任务
    RET_THEATER_NOT_OPEN = 79002, -- 剧场活动未开启
    RET_THEATER_DATA_NIL = 79003, -- 剧场活动数据空
    RET_THEATER_TASK_NOT_COMPLETE = 79004, -- 剧场活动任务未完成
    RET_THEATER_TASK_REWARDED = 79005, -- 剧场活动任务奖励已领取
    RET_THEATER_DONATELIST_EMPTY = 79006, -- 剧场交付材料空
    RET_THEATER_EVENT_INVALID = 79007, -- 剧场活动id无效
    RET_THEATER_STEP_INVALID = 79008, -- 剧场阶段id武侠
    RET_THEATER_DONATE_RES_NOT_ENOUGH = 79009, -- 剧场交付资源不足
    RET_THEATER_STEP_NOT_MATCH = 79010, -- 剧场交付阶段不匹配
    RET_THEATER_STEP_DONATE_FINISHED = 79011, -- 剧场当前阶段的交付需求已完成
    RET_THEATER_PERFORMGAME_NOT_JOIN_TIME = 79012, -- 剧场表演小游戏 不是接取任务时间
    RET_THEATER_PERFORMGAME_HAS_JOINED = 79013, -- 剧场表演小游戏 已经接取过任务
    RET_THEATER_PERFORMGAME_NOT_PERFORM_TIME = 79014, -- 剧场表演小游戏 不是表演时间
    RET_THEATER_PERFORMGAME_PERFORMID_WRONG = 79015, -- 剧场表演小游戏 表演不匹配
    RET_THEATER_PERFORMGAME_NOT_JOIN = 79016, -- 剧场表演小游戏 未接取任务
    RET_THEATER_PERFORMGAME_HAS_PERFORMED = 79017, -- 剧场表演小游戏 已经表演过
    RET_THEATER_PERFORM_INVALID_ID = 79018, -- 剧场表演小游戏 无效表演id
    RET_THEATER_TASK_REWARD_EMPTY = 79019, -- 剧场任务奖励空
    RET_THEATER_DONATELIST_INVALID = 79020, -- 交付资源列表无效
    RET_THEATER_DONATE_REFRESH_CD = 79021, -- 交付列表刷新请求cd
    RET_THEATER_CANT_JOIN_PERFORM_GAME = 79022, -- 当前不能加入剧院表演小游戏

    RET_RAID_SEASON_EVENT_ID_NOT_EXIST = 80001, --- 不存在该活动对应的赛季
    RET_RAID_SEASON_CURRENT_SEASON_ERROR = 80002, --- 当前赛季与副本赛季不匹配
    RET_RAID_SEASON_NOT_EXIST_DUNGEON = 80003, -- 不存在对应的赛季副本
    RET_RAID_SEASON_DUNGEON_NOT_UNLOCK = 80004, -- 赛季副本未到解锁时间
    RET_RAID_SEASON_DUNGEON_NOT_DUNGEON_TYPE = 80005, -- 不存在该副本类型的判断
    RET_RAID_SEASON_NOT_RAID_SEASON_DATA = 80006, -- 不存在对应的赛季数据
    RET_RAID_SEASON_NOT_PRE_RAID_TIME = 80007, -- 不是预选赛时间
    RET_RAID_SEASON_NOT_RAID_TIME = 80008, -- 不是正赛时间
    RET_RAID_SEASON_CANT_REWARD = 80009, -- 无法领取奖励
    RET_RAID_SEASON_REPEAT_REWARD = 80010, -- 重复领奖
    RET_RAID_SEASON_PRE_RANK_CONF_NIL = 80011, -- 预选赛配置错误
    RET_RAID_SEASON_PRE_RANK_REWARD_NIL = 80012, -- 预选赛奖励配置错误
    RET_RAID_SEASON_PRE_RANK_DATA_NIL = 80013, -- 预选赛排名数据空
    RET_RAID_SEASON_NO_GROUP = 80014, -- 获取不到分组
    RET_RAID_SEASON_GROUP_FULL = 80015, -- 分配分组满
    RET_RAID_SEASON_NOT_RANK = 80016, --找不到排行榜
    RET_RAID_SEASON_RECORD_FIND_FAIL = 80017, -- 找不到排行榜记录

    RET_WEB_JUMP_SERVER_INVALID = 81001, -- 网页跳转服务器无效
    RET_WEB_JUMP_EVENT_CONF_NIL = 81002, -- 网页跳转表配置空
    RET_WEB_JUMP_ALREADY = 81003, -- 网页已跳转
    RET_WEB_JUMP_CANT_GET_REWARD = 81004, -- 网页跳转无法领取奖励

    RET_AUTO_CHESS_NOT_EXIST = 82001, -- 自走棋信息不存在
    RET_AUTO_CHESS_NOT_UNLOCK = 82002, -- 自走棋未解锁
    RET_AUTO_CHESS_NOT_VALID_IN_RANK_LEVEL = 82003, -- 当前段位无法进入该自走棋
    RET_AUTO_EVENT_NOT_OPEN = 82004, -- 自走棋活动未开启
    RET_AUTO_CHESS_MISSION_NOT_VALID = 82005, -- 自走棋任务无效
    RET_AUTO_CHESS_CARD_UNLOCKED = 82006, -- 自走棋卡牌已解锁
    RET_AUTO_CHESS_EQUIP_UNLOCKED = 82007, -- 自走棋装备未解锁
    RET_AUTO_CHESS_CANNOT_ADD_EQUIP = 82008, -- 自走棋棋子装备已满
    RET_AUTO_CHESS_CANNOT_REPLACE_EQUIP = 82009, -- 自走棋指定位置没有装备
    RET_AUTO_CHESS_CANNOT_REMOVE_EQUIP = 82010, -- 自走棋指定位置没有装备
    RET_AUTO_CHESS_SQUAD_INVALID = 82021, -- 自走棋阵容无效
    RET_AUTO_CHESS_CANNOT_ADD_SQUAD = 82022, -- 自走棋阵容已满
    RET_AUTO_CHESS_SQUAD_NOT_EXIST = 82023, -- 自走棋指定位置没有阵容
    RET_AUTO_CHESS_DUNGEON_NOT_MATCH = 82024, -- 自走棋副本Id不匹配
    RET_AUTO_CHESS_MAX_REFRESH = 82025, -- 自走棋最大刷新次数

    SECONDARY_PASSWORD_MISMATCH = 83001, -- 二级密码校验失败
    GIFT_SENDER_BAN_SEND             = 83002, -- 发送方被禁止送礼
    GIFT_RECIPIENT_BAN_RECV          = 83003, -- 接收方被禁止收礼
    GIFT_MAIL_CONTENT_TOO_LONG        = 83010, -- 礼物留言超出长度限制
    GIFT_REWARD_TYPE_ERROR            = 83011, -- 礼物奖励类型非法
    GIFT_GOODS_CONF_NIL               = 83012, -- 商品配置不存在
    GIFT_SHOP_ITEM_CONF_NIL           = 83013, -- 商城道具配置不存在
    GIFT_QUOTA_NOT_ENOUGH             = 83020, -- 送礼额度不足
    GIFT_QUOTA_NOT_ENOUGH_PAY_ORDER   = 83021, -- 未完成支付订单占用额度（需重登）
    GIFT_RECIPIENT_NOT_FOUND          = 83030, -- 接收方不存在
    GIFT_RECIPIENT_INVENTORY_FULL     = 83031, -- 接收方背包/唯一物品校验失败
    
    GIFT_GOODS_CANNOT_BE_GIFT         = 83014, -- 商品不可作为礼物

    GIFT_SHOP_MONEY_NOT_ENOUGH        = 83040, -- 购买礼物资源不足
    GIFT_SHOP_ITEM_INVALID         = 83053, -- 商城道具非法
    GIFT_SHOP_LIMIT_EXCEEDED          = 83054, -- 礼物购买数量超出限制
    GIFT_SENSITIVE_WORD_FOUND          = 83055, -- 礼物购买数量超出限制
    GIFT_CANNOT_SEND_TO_SELF = 83060, -- 不能送礼给自己
    GIFT_RECIPIENT_FRIEND_DURATION_NOT_ENOUGH = 83061, -- 送礼对象好友时长不足
    GIFT_RECIPIENT_NOT_FRIEND = 83062, -- 送礼对象不是好友
    GIFT_SENDER_MONTH_COUNT_EXCEEDED = 83063, -- 发送方当月送礼次数超出限制
    GIFT_RECIPIENT_REGION_CODE_RESTRICTED = 83064, -- 接收方地区码受限，无法接收礼物
    GIFT_SHOP_ITEM_SEND_LIMIT = 83065, -- 礼物购买数量超出发送限制
    GIFT_SEND_TOO_FAST = 83066, -- 送礼操作过于频繁，请稍后再试

    RET_SENSITIVE_WORD_FOUND = 84001, -- 敏感词检测到敏感词

    RET_REGION_REPUTATION_ERROR = 85001, -- 区域声望不存在
    RET_REGION_REPUTATION_QUEST_ID_ERROR = 85002, -- 区域声望任务id有误
    RET_REGION_REPUTATION_QUEST_STATE_ERROR = 85003, -- 区域声望任务状态有误
    RET_REGION_REPUTATION_QUEST_REWARD_ERROR = 85004, -- 区域声望奖励有误
    RET_REGION_REPUTATION_HAS_RECURRING_QUEST_DOING = 85005, -- 区域声望唯一循环副本任务正在进行中
    RET_REGION_REPUTATION_LEVEL_ERROR = 85006, -- 区域声望等级有误
    RET_REGION_REPUTATION_REFRESHTIMES_LIMIT = 85007, -- 区域声望手动刷新已达上限
    RET_REGION_REPUTATION_TYPE_ERROR = 85008, -- 区域声望委托任务的材料类型有误
    RET_REGION_REPUTATION_LEVEL_MAX = 85009, -- 当前区域声望已满级
    RET_REGION_REPUTATION_WEEK_EXP_LIMIT = 85010, -- 当周区域声望已达上限

    RET_FOOLS_DAY_INVALID_LIKE_TYPE = 86001, -- 不合法的点赞类型
    RET_FOOLS_DAY_NOT_LIKED_YET = 86002, -- 尚未点赞
    RET_FOOLS_DAY_ALREADY_LIKED = 86003, -- 已经点赞
    RET_FOOLS_DAY_PHOTO_LIMIT = 86004, -- 照片数量已达上限
    RET_FOOLS_DAY_PHOTO_NOT_FOUND = 86005, -- 照片未找到
    RET_OSS_UPLOAD_FAILED = 86006, -- OSS上传失败
    RET_FOOLS_DAY_REQUEST_TOO_FREQUENT = 86007, -- 请求过于频繁 
    RET_FOOLS_DAY_INVALID_REQUEST = 86008, -- 无效请求
    RET_FOOLS_DAY_PHOTO_NOT_EXIST = 86009, -- 照片不存在
    RET_FOOLS_DAY_PHOTO_CONTENT_TOO_LONG = 86010, -- 照片描述内容过长

    RET_CUMULATIVE_RECHARGE_EVENT_NOT_EXIST = 87001, -- 累计充值活动不存在
    RET_CUMULATIVE_RECHARGE_REWARD_NOT_VALID = 87002, -- 累计充值奖励无法领取

    RET_COMEBACK_NOT_OPEN_TIME = 88001, -- 回归活动不是开启时间
    RET_COMEBACK_DATA_NIL = 88002, -- 回归活动数据不存在
    RET_COMEBACK_INVALID = 88003, -- 回归活动不在生效时间
    RET_COMEBACK_REWARD_REPEAT = 88004, -- 回归活动回归奖励重复领取
    RET_COMEBACK_INVALID_LOGINCONF = 88005, -- 回归活动无效签到配置
    RET_COMEBACK_NO_REWARD_TO_GET = 88006, -- 回归活动没有奖励可领取
    RET_COMEBACK_INVALID_QUESTCONF = 88007, -- 回归活动我无效任务配置


    RET_SECONDARY_PASSWORD_NOT_ALL_NUMBER = 89003, --- 二级密码不全是数字
    RET_SECONDARY_PASSWORD_LEN_INVALID = 89004,     --- 二级密码长度不对
    RET_SECONDARY_PASSWORD_FREEZE_TIME = 89005,     --- 二级密码设置失败。当前正在封禁
    RET_SECONDARY_PASSWORD_ERROR = 89006,           --- 二级密码校验错误

    RET_INVITE_ACTIVITY_NOT_OPEN = 90001, -- 邀请码活动未开启
    RET_INVITEINFO_HTTP_REQUEST_FAIL = 90002, -- 获取邀请信息失败
    RET_INVITEINFO_HTTP_RET_FAIL = 90003, -- 获取邀请信息失败

    RET_PHOTO_ACTIVITY_NOT_OPEN = 91001, -- 拍照活动未开启
    RET_PHOTO_QUEST_CONF_NIL = 91002, -- 拍照活动任务配置空
    RET_PHOTO_QUEST_NOT_IN_TIME = 91003, -- 拍照活动不在生效时间内
    RET_PHOTO_QUEST_NOT_FINISH_COND = 91004, -- 拍照活动未完成条件
    RET_PHOTO_QUESTCHAIN_NOT_FINISH = 91005, -- 拍照活动未完成任务链
    RET_PHOTO_QUEST_REWARD_GOT = 91006, -- 拍照活动奖励已领取



    RET_SOLO_TREASURE_DUNGEON_MISS_SOLOTREASURE_ID = 92003, ---副本ID不合法 SoloTreasure.xlsx
    RET_SOLO_TREASURE_EVENT_DUNGEON_INVALID_ID = 92004, ---副本ID不合法
    RET_SOLO_TREASURE_DUNGEON_RESOURCE_NOT_ENOUGH = 92005, ---入场费不够
    RET_SOLO_TREASURE_DUNGEON_LOCKED = 92006, ---寻宝活动未开始/未解锁
    RET_SOLO_TREASURE_DUNGEON_TEAM_CHAR_ERROR = 92007, ---寻宝活动阵容角色有误
    RET_SOLO_TREASURE_DUNGEON_TEAM_WEAPON_ERROR = 92008, ---寻宝活动阵容武器有误
    RET_SOLO_TREASURE_DUNGEON_TEAM_PET_ERROR = 92009, ---寻宝活动阵容宠物有误
    RET_SOLO_TREASURE_DUNGEON_TEAM_PHANTOM_ERROR = 92010, ---寻宝活动阵容魅影有误
    RET_SOLO_TREASURE_DUNGEON_TEAM_ERROR = 92011, ---寻宝活动阵容有误
    RET_SOLO_TREASURE_DUNGEON_BAG_INVALID = 92012, ---寻宝背包不合法
    
    RET_BACKPACKPUZZLE_INVALID_LEVEL_ID = 93001, -- 背包整理关卡无效关卡id
    RET_BACKPACKPUZZLE_LEVEL_NOT_UNLOCK = 93002, -- 背包整理关卡未解锁
    RET_BACKPACKPUZZLE_INVALID_REWARDKEY = 93003, -- 背包整理关卡无效奖励keyid
    RET_BACKPACKPUZZLE_INVALID_EVENT_ID = 93004, -- 背包整理关卡无效活动id
    RET_BACKPACKPUZZLE_DATA_NIL = 93005,-- 背包整理关卡数据空
    RET_BACKPACKPUZZLE_SCORE_NOT_ENOUGH = 93006,-- 背包整理关卡领奖分数不够
    RET_BACKPACKPUZZLE_REWARD_GOT = 93007,-- 背包整理关卡奖励已领取
    RET_BACKPACKPUZZLE_NO_REWARD = 93008,-- 背包整理关卡没有奖励可领取
    RET_BACKPACKPUZZLE_NOT_COMPLETE = 93009,
    RET_BACKPACKPUZZLE_INVALID_SCORE = 93010, -- 背包整理关卡无效的分数

    RET_INTERACT_TRIGGER_ID_ERROR =  94001,--STL领奖的Id有误
    RET_INTERACT_TRIGGER_REWARD_GOT = 94002,--STL的奖励已领取

    RET_LIMIT_PRIZE_ROUND_END = 95001, -- 有限奖池轮次结束
    RET_LIMIT_PRIZE_DATA_NOT_EXIST = 95002, -- 有限奖池活动数据不存在
    RET_LIMIT_PRIZE_ROUND_NOT_EXIST = 95003, -- 有限奖池轮次数据不存在
    RET_LIMIT_PRIZE_RESOURCE_NOT_ENOUGH = 95004, -- 有限奖池抽卡资源不足
    RET_LIMIT_PRIZE_NOT_COMPLETE_SELF_SELECT = 95005, -- 有限奖池没有完成自选
    RET_LIMIT_PRIZE_CANNOT_SELF_SELECT = 95006, -- 当前奖励不可自选
    RET_LIMIT_PRIZE_SELF_SELECT_INDEX_ERROR = 95007, -- 自选奖励索引不存在
    RET_LIMIT_PRIZE_POOL_CANNOT_SELF_SELECT = 95008, -- 当前奖池状态不可自选

    RET_ACCESORRYDROP_EVENT_NOT_OPEN = 96001, -- 外观掉落活动未开启
    RET_ACCESORRYDROP_COIN_NOT_ENOUGH = 96002, -- 外观掉落开宝箱币不足
    RET_ACCESORRYDROP_NOT_REWARD_TIME = 96003, -- 外观掉落活动不是开宝箱时间
    RET_ACCESORRYDROP_DATA_NIL = 96004, -- 外观掉落数据空
    
        -- 公会
        RET_GUILD_CREATE_INVALID_UID = 97001, -- 创建工会：UID无效
        RET_GUILD_ALREADY_IN_GUILD = 97002, -- 创建工会：玩家已在工会中
        RET_GUILD_CREATE_BANNED = 97003, -- 创建工会：封禁状态不可创建
        RET_GUILD_CREATE_LEVEL_NOT_ENOUGH = 97004, -- 创建工会：等级不足
        RET_GUILD_CREATE_NAME_EMPTY = 97005, -- 创建工会：名称为空
        RET_GUILD_CREATE_DECL_EMPTY = 97006, -- 创建工会：宣言为空
        RET_GUILD_CREATE_NAME_TOO_LONG = 97007, -- 创建工会：名称超长
        RET_GUILD_CREATE_DECL_TOO_LONG = 97008, -- 创建工会：宣言超长
        RET_GUILD_CREATE_NAME_INVALID = 97009, -- 创建工会：名称不合规/敏感词
        RET_GUILD_CREATE_DECL_INVALID = 97010, -- 创建工会：宣言不合规/敏感词
        RET_GUILD_CREATE_ITEM_NOT_ENOUGH = 97011, -- 创建工会：创建道具不足
        RET_GUILD_CREATE_NAME_DUPLICATE = 97012, -- 创建工会：名称重复
        RET_GUILD_CREATE_DB_ERROR = 97013, -- 创建工会：数据库错误
        RET_GUILD_CREATE_GEN_ID_FAILED = 97014, -- 创建工会：生成工会ID失败
        RET_GUILD_CREATE_ENTITY_FAILED = 97015, -- 创建工会：工会实体创建失败
        RET_GUILD_CREATE_SERVER_ERROR = 97016, -- 创建工会：服务端异常
    
        RET_GUILD_NAME_EXIST = 97017, -- 工会名称已存在
}

setmetatable(ErrorCode, {
    __index = onMissingKey -- 当访问不存在的键时，调用 onMissingKey 函数
})

local temp = {}

for key, value in pairs(ErrorCode) do      
    if temp[value] then
        -- DebugPrint("conflict errcode",temp[value],key,value)
    end
    temp[value] = key
end

ErrorCode.Translate = temp

function ErrorCode:Name(errCode)
    return ErrorCode.Translate[errCode]
end

function ErrorCode:Check(Code, TipsType)
    if Code ~= self.RET_SUCCESS then
        print(_G.LogTag, "ErrorCode Check Result not Success", Code)
        if not GWorld.GameInstance then return end
        local UIManger = GWorld.GameInstance:GetGameUIManager()
        UIManger:ShowError(Code, nil, TipsType)
        return false
    end

    return true
end

function ErrorCode:GetText(ErrCode)
    local Err = DataMgr.ErrorCode[ErrCode]
    if not Err then return end
    local Key = CommonConst.SystemLanguage
    if CommonConst.SystemLanguage == CommonConst.SystemLanguages.CN then
        Key = "ErrorCodeContent"
    end
    return Err[Key]
end

return ErrorCode
