---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jinyi.li.
--- DateTime: 2026/1/21 16:18
---

local NetGuidMap = {}
local OnRepFuncLayer = {}
local ReplicatedClassRegistry = require "BluePrints.DungeonObject.Replication.ReplicatedClassRegistry"
local ClassRegistry = {}

local GameModeDungeonReplicatedProperty = {}

function GameModeDungeonReplicatedProperty:Init(Env)
    self:InitClassRegistry()

    if not Env.NetGuid then
        return
    end

    local NetGuid = Env.NetGuid
    NetGuidMap[NetGuid] = self
end

function GameModeDungeonReplicatedProperty:InitClassRegistry()
    self:RegisterReplicatedClass(ReplicatedClassRegistry)
end

function GameModeDungeonReplicatedProperty:RegisterReplicatedClass(ClassTable)
    for k, v in pairs(ClassTable) do
        ClassRegistry[k] = v
    end
end

function GameModeDungeonReplicatedProperty:BeginPlay()

end

function GameModeDungeonReplicatedProperty:EndPlay()

end

function GameModeDungeonReplicatedProperty:InitReplicatedProperties()
end

function GameModeDungeonReplicatedProperty:ReplicatedProperty(NetGuid, PropName, Value, OnRepFunc)
    local Inc = NetGuidMap[NetGuid]
    assert(Inc, string.format("ReplicatedProperty with not exist Actor: %d", NetGuid))

    local RepLayer = OnRepFuncLayer[NetGuid] or {}
    if OnRepFunc then
        RepLayer[PropName] = OnRepFunc
        OnRepFuncLayer[NetGuid] = RepLayer
    end

    -- todo: @SnowMoon 这里如果是Class的话有没有必要只赋值Value中的部分值？
    if type(Value) == "table" then
        repeat
            local NetGuid = Value._NetGuid
            if NetGuid then
                -- 这个对象引用一个已经同步的Actor
                Inc[PropName] = NetGuidMap[NetGuid]
                break
            end

            local Class = Value.__Class__
            if Class then
                -- 这个table是一个DungeonProperty Class
                local ClassInfo = ClassRegistry[Class]
                local ValueInc = ClassInfo(self)
                if ValueInc.BeginPlay then
                    ValueInc:BeginPlay()
                end

                for k, v in pairs(Value) do
                    ValueInc[k] = v
                end

                Inc[PropName] = ValueInc
                break
            end

            Inc[PropName] = Value
        until true
    else
        Inc[PropName] = Value
    end

    -- OnRep相关
    local CurOnRepFunc = RepLayer[PropName]
    if not CurOnRepFunc then
        return
    end

    local Func = Inc[CurOnRepFunc]
    if not Func then
        return
    end

    Func(Inc)
end

function GameModeDungeonReplicatedProperty:ReplicatedActor(Class, NetGuid, Props, _OnRepFuncLayer)
    assert(not NetGuidMap[NetGuid], string.format("ReplicatedActor with exist Actor: %d", NetGuid))

    local ClassInfo = ClassRegistry[Class]
    local Inc = ClassInfo(self)
    if Inc.BeginPlay then
        Inc:BeginPlay()
    end

    NetGuidMap[NetGuid] = Inc
    OnRepFuncLayer[NetGuid] = _OnRepFuncLayer
    for k, v in pairs(Props) do
        self:ReplicatedProperty(NetGuid, k, v)
    end
end

function GameModeDungeonReplicatedProperty:ReplicatedDeleteActor(NetGuid)
    local Inc = NetGuidMap[NetGuid]
    if not Inc then
        return
    end

    if Inc.EndPlay then
        Inc:EndPlay()
    end

    NetGuidMap[NetGuid] = nil
    OnRepFuncLayer[NetGuid] = nil
end

function GameModeDungeonReplicatedProperty:OnRepTestRep()
    print("ReplicatedDungeonObject", "OnRepTestRep", self.TestRep, self.TestClass)
    if self.TestClass then
        print("ReplicatedDungeonObject TestClass", self.TestClass.A, self.TestClass.D)

        if self.TestClass.TestClass2 then
            print("ReplicatedDungeonObject TestClass2", self.TestClass.TestClass2.C)
        end
    end
end


return GameModeDungeonReplicatedProperty