---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jinyi.li.
--- DateTime: 2024/11/15 11:10
---

local Class = _G.TypeClass
local BaseTypes = require "BluePrints.Client.CustomTypes.BaseTypes"
local CustomTypes = require "BluePrints.Client.CustomTypes.CustomTypes"
local prop = require "NetworkEngine.Common.Prop"
local FormatProperties = require "NetworkEngine.Common.Assemble".FormatProperties

local CharTrial = Class("CharTrial", CustomTypes.CustomAttr)
CharTrial.__Props__ = {
        -- EventId
        TrialId= prop.prop("Int", "client save"),
        -- 是否完成
        bFinished = prop.prop("Int", "client save", 0),
        -- 是否领奖
        bGetReward = prop.prop("Int", "client save", 0),
    }

    function CharTrial:Init(TrialId)
        if not TrialId then
            return
        end
        self.TrialId = TrialId
    end

    function CharTrial:IsFinished()
        return self.bFinished == 1
    end

    function CharTrial:SetFinished()
        if self.bFinished == 1 then
            return
        end
        self.bFinished = 1
    end

    function CharTrial:IsGetReward()
        return self.bGetReward == 1
    end

    function CharTrial:SetGetReward()
        if self.bGetReward == 1 then
            return
        end
        self.bGetReward = 1
    end

    FormatProperties(CharTrial)

local CharTrialDict = Class("CharTrialDict", CustomTypes.CustomDict)
    CharTrialDict.KeyType = BaseTypes.Int
    CharTrialDict.ValueType = CharTrial

    function CharTrialDict:GetOrInit(EventId)
        if not self[EventId] then
            self[EventId] = CharTrial(EventId)
        end

        return self[EventId]
    end


return {CharTrial = CharTrial, CharTrialDict = CharTrialDict}