---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jinyi.li.
--- DateTime: 2025/5/29 18:57
---

local Class = _G.TypeClass
local BaseTypes = require "BluePrints.Client.CustomTypes.BaseTypes"
local CustomTypes = require "BluePrints.Client.CustomTypes.CustomTypes"
local prop = require "NetworkEngine.Common.Prop"
local FormatProperties = require "NetworkEngine.Common.Assemble".FormatProperties


local Community = Class("Community", CustomTypes.CustomAttr)
    Community.__Props__ = {
        -- 累签天数
        SignInDay = prop.prop("Int", "save", 0),
        -- 上次签到时间
        LastSignTime = prop.prop("Int", "save", 0),
        -- 关注社媒列表,{关注社媒Id:关注状态,1-未关注，不可领取，2-已关注，待领取，3-已关注，已领取}
        CommunityFollowList = prop.prop("Int2IntDict", "client save"),
        -- 商品限购
        ShopLimit = prop.prop("Int2IntDict", "save"),
    }

    --设置社媒为已关注
    function Community:SetFollowed(CommunityId)
        if not self:IsFollowed(CommunityId) then
            self.CommunityFollowList[CommunityId] = 2
        end
    end

    --设置社媒关注奖励已领取
    function Community:SetRewardGot(CommunityId)
        if self:IsRewardCanGet(CommunityId) then
            self.CommunityFollowList[CommunityId] = 3
        end
    end

    -- 是否已关注
    function Community:IsFollowed(CommunityId)
        local FollowState = self.CommunityFollowList[CommunityId]
        if not FollowState then
            return false
        end
        return FollowState ~= 1
    end

    -- 是否待领取
    function Community:IsRewardCanGet(CommunityId)
        local FollowState = self.CommunityFollowList[CommunityId]
        if not FollowState then
            return false
        end
        return FollowState == 2
    end

    -- 是否已领取
    function Community:IsRewardGot(CommunityId)
        local FollowState = self.CommunityFollowList[CommunityId]
        if not FollowState then
            return false
        end
        return FollowState == 3
    end

    function Community:GetCommunity(CommunityId)
        if not self.CommunityFollowList[CommunityId] then
            self.CommunityFollowList[CommunityId] = 1
        end
        return self.CommunityFollowList[CommunityId]
    end

    FormatProperties(Community)

return {Community = Community}