---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lijinyi.
--- DateTime: 2023/4/6 9:36
---
local Class = _G.TypeClass
local BaseTypes = require "BluePrints.Client.CustomTypes.BaseTypes"
local CustomTypes = require "BluePrints.Client.CustomTypes.CustomTypes"
local prop = require "NetworkEngine.Common.Prop"
local FormatProperties = require "NetworkEngine.Common.Assemble".FormatProperties

local GachaBase = Class("GachaBase", CustomTypes.CustomAttr)
    GachaBase.__Props__ = {
        -- 卡池ID
        GachaId = prop.prop("Int", "client save", 0),
        -- 已经抽卡次数
        DrawCounts = prop.prop("Int", "client save", 0),
        -- 卡池可用性，因为有时间限制，所以客户端自己算可能算不准，所以让服务端算好了直接同步给客户端
        Usable = prop.prop("Int", "client save", 1),
        -- 自选道具
        SelfSelect = prop.prop("Int", "client save", 0),
        -- 本卡池已经出过5星的次数
        Already5StarCount = prop.prop("Int", "client save", 0),

        -- 读表数据
        -- 卡池类型
        GachaType = prop.getter("Data", "GachaType"),
        -- 单抽物品数量
        GachaTimes = prop.getter("Data", "GachaTimes"),
        -- 卡池抽取次数限制
        GachaLimit = prop.getter("Data", "GachaLimit"),
    }

    function GachaBase:Init(GachaId)
        if not GachaId then
            return
        end
        self.GachaId = GachaId
    end

    function GachaBase:SelfSelectData()
        return nil
    end

    function GachaBase:IsSelfSelectGacha()
        return self:SelfSelectData() ~= nil
    end

    function GachaBase:Type()
        return ""
    end

    FormatProperties(GachaBase)

local Gacha = Class("Gacha", GachaBase)
    Gacha.__Props__ = {
        -- 是否已发放抽卡资源,默认未发放0,发放之后改成1,仅用于教学卡池;
	    IsSendGachaResource = prop.prop("Int", "save",0),
    }

    function Gacha:Data()
        return DataMgr.Gacha[self.GachaId]
    end

    function Gacha:SelfSelectData()
        return DataMgr.GachaSelect[self.GachaId]
    end

    FormatProperties(Gacha)

local GachaDictBase = Class("GachaDictBase", CustomTypes.CustomDict)
    GachaDictBase.KeyType = BaseTypes.Int
    GachaDictBase.ValueType = GachaBase

    function GachaDictBase:NewGacha(GachaId)
        return self.ValueType(GachaId)
    end

    function GachaDictBase:UpdateUsable(GachaId, NewState)
        if not self[GachaId] then
            return
        end

        self[GachaId].Usable = NewState
        self[GachaId] = self[GachaId] -- 同步客户端
    end

    function GachaDictBase:SelfSelectItem(GachaId, ItemId)
        if not self[GachaId] then
            return
        end

        self[GachaId].SelfSelect = ItemId
        self[GachaId] = self[GachaId] -- 同步客户端
    end

local GachaDict = Class("GachaDict", GachaDictBase)
    GachaDict.ValueType = Gacha

local GachaRecord = Class("GachaRecord", CustomTypes.CustomAttr)
    GachaRecord.__Props__ = {
        -- 卡池Id
        GachaId = prop.prop("Int", "save"),
        -- 卡池类型
        GachaType = prop.prop("Str", "save"),
        -- 道具Id
        ItemId = prop.prop("Int", "save"),
        -- 道具类型
        ItemType = prop.prop("Int", "save"),
        -- 道具数量
        Count = prop.prop("Int", "save"),
        -- 道具品质
        Star = prop.prop("Int", "save"),
        -- 时间
        Time = prop.prop("Int", "save"),
    }

    function GachaRecord:Init(GachaEntity, Record, Time)
        self.GachaId = GachaEntity.GachaId
        self.GachaType = GachaEntity:Type()
        self.ItemId = Record.ResultId
        self.ItemType = Record.Sign
        self.Count = Record.Count
        self.Star = Record.Star
        self.Time = Time
    end

    function GachaRecord:Replace(GachaEntity, Record, Time)
        local GachaId = GachaEntity.GachaId
        if self.GachaId ~= GachaId then
            self.GachaId = GachaId
        end

        local Type = GachaEntity:Type()
        if self.GachaType ~= Type then
            self.GachaType = Type
        end

        if self.ItemId ~= Record.ResultId then
            self.ItemId = Record.ResultId
        end

        if self.ItemType ~= Record.Sign then
            self.ItemType = Record.Sign
        end

        if self.Count ~= Record.Count then
            self.Count = Record.Count
        end

        if self.Star ~= Record.Star then
            self.Star = Record.Star
        end

        if self.Time ~= Time then
            self.Time = Time
        end
    end

    function GachaRecord:Dump()
        return {
            GachaId = self.GachaId,
            GachaType = self.GachaType,
            ItemId = self.ItemId,
            ItemType = self.ItemType,
            Count = self.Count,
            Star = self.Star,
            Time = self.Time
        }
    end

    FormatProperties(GachaRecord)

-- 循环队列
local GachaRecordQueue = Class("GachaRecordQueue", CustomTypes.CustomDict)
    GachaRecordQueue.KeyType = BaseTypes.Int
    GachaRecordQueue.ValueType = GachaRecord

    function GachaRecordQueue:NewRecord(GachaEntity, Record, Time)
        return GachaRecord(GachaEntity, Record, Time)
    end

local GuaranteedDict = Class("GuaranteedDict", CustomTypes.CustomDict)
    GuaranteedDict.KeyType = BaseTypes.Str
    GuaranteedDict.ValueType = CustomTypes.Str2IntDict

local SkinGacha = Class("SkinGacha", GachaBase)
    SkinGacha.__Props__ = {
        -- 累抽奖励领取状态
        CumulativeRewardGot = prop.prop("IntSet", "client save"),
    }

    function SkinGacha:Data()
        return DataMgr.SkinGacha[self.GachaId]
    end

    function Gacha:SelfSelectData()
        return DataMgr.SkinGachaSelect[self.GachaId]
    end

    function GachaBase:Type()
        return "Skin"
    end

    FormatProperties(SkinGacha)

local SkinGachaDict = Class("SkinGachaDict", GachaDictBase)
    SkinGachaDict.ValueType = SkinGacha

return {
    Gacha = Gacha, GachaDict = GachaDict, GachaRecord = GachaRecord, GachaRecordQueue = GachaRecordQueue, GuaranteedDict = GuaranteedDict,
    SkinGacha = SkinGacha, SkinGachaDict = SkinGachaDict,
}
