---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jinyi.li.
--- DateTime: 2026/2/2 11:15
---

local Class = _G.TypeClass
local BaseTypes = require "BluePrints.Client.CustomTypes.BaseTypes"
local CustomTypes = require "BluePrints.Client.CustomTypes.CustomTypes"
local prop = require "NetworkEngine.Common.Prop"
local FormatProperties = require "NetworkEngine.Common.Assemble".FormatProperties

local LimitPrizeRecord = Class("LimitPrizeRecord", CustomTypes.CustomAttr)
    LimitPrizeRecord.__Props__ = {
        -- 时间
        TimeStamp = prop.prop("Int", "client save"),
        -- 轮次
        Round = prop.prop("Int", "client save"),
        -- 奖励索引
        PrizeIndex = prop.prop("Int", "client save"),
        -- 自选索引
        SelfSelectId = prop.prop("Int", "client save", 0),
    }

    function LimitPrizeRecord:Init(TimeStamp, Round, PrizeIndex, SelfSelectId)
        self.TimeStamp = TimeStamp
        self.Round = Round
        self.PrizeIndex = PrizeIndex
        self.SelfSelectId = SelfSelectId
    end

    FormatProperties(LimitPrizeRecord)

local LimitPrizeRecordList = Class("LimitPrizeRecordList", CustomTypes.CustomList)
    LimitPrizeRecordList.ValueType = LimitPrizeRecord

local LimitPrize = Class("LimitPrize", CustomTypes.CustomAttr)
    LimitPrize.__Props__ = {
        -- 当前轮次
        Round = prop.prop("Int", "client save", 0),
        -- 当前已经抽取次数
        DrawCounts = prop.prop("Int", "client save", 0),
        -- 奖池列表
        Prizes = prop.prop("IntList", "save"),
        -- 自选奖励
        SelfSelect = prop.prop("Int2IntDict", "client save", {}),
        -- 本轮已经抽到的奖励Id
        HasDrawPrizes = prop.prop("IntList", "client save"),
        -- 抽奖历史
        Record = prop.prop("LimitPrizeRecordList", "client save"),
    }

    function LimitPrize:IsRoundEnd()
        return self.DrawCounts == self.Prizes:Length()
    end

    function LimitPrize:AddRecord(TimeStamp, Round, PrizeIndex, SelfSelectId)
        local Record = LimitPrizeRecord(TimeStamp, Round, PrizeIndex, SelfSelectId)
        self.Record:Append(Record)
    end

    FormatProperties(LimitPrize)

local LimitPrizeDict = Class("LimitPrizeDict", CustomTypes.CustomDict)
    LimitPrizeDict.KeyType = BaseTypes.Int
    LimitPrizeDict.ValueType = LimitPrize

    function LimitPrizeDict:New()
        return LimitPrize()
    end

return {
    LimitPrize = LimitPrize,
    LimitPrizeDict = LimitPrizeDict,
    LimitPrizeRecord = LimitPrizeRecord,
    LimitPrizeRecordList = LimitPrizeRecordList,
}