---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lijinyi.
--- DateTime: 2024/4/26 14:51
---
local Class = _G.TypeClass
local BaseTypes = require "BluePrints.Client.CustomTypes.BaseTypes"
local CustomTypes = require "BluePrints.Client.CustomTypes.CustomTypes"
local prop = require "NetworkEngine.Common.Prop"
local FormatProperties = require "NetworkEngine.Common.Assemble".FormatProperties

local RewardParams = Class("RewardParams", CustomTypes.CustomAttr)
    RewardParams.__Props__ = {
        -- 奖励序列记录
        RewardSequences = prop.prop("RewardSequence.RewardSequenceAttr", "save cross"),
        -- 一次性奖励
        OnceReward = prop.prop("Int2IntDict","save cross"),
        -- 奖励翻倍率
        BonusRate = prop.prop("Int", "cross", 0),
        -- 奖励倍率相关Tag
        BonusRateTag = prop.prop("Str2IntDict", "cross save"),
        -- 经验倍率
        ExpRate = prop.prop("Int", "cross", 0),
        -- 经验倍率相关Tag
        ExpRateTag = prop.prop("Str2IntDict", "cross save"),
        -- 是否禁止获取经验
        bForbidExp = prop.prop("Bool", "", false),
    }

    FormatProperties(RewardParams)

return {RewardParams = RewardParams}
