---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lijinyi.
--- DateTime: 2024/3/7 11:20
---

local Class = _G.TypeClass
local BaseTypes = require "BluePrints.Client.CustomTypes.BaseTypes"
local CustomTypes = require "BluePrints.Client.CustomTypes.CustomTypes"
local prop = require "NetworkEngine.Common.Prop"
local FormatProperties = require "NetworkEngine.Common.Assemble".FormatProperties

local RougeLikeInfo = Class("RougeLikeInfo", CustomTypes.CustomAttr)
    RougeLikeInfo.__Props__ = {
        -- 肉鸽赛季具体数据
        RougeLikeSeasons = prop.prop("RougeLike.RougeLikeDict", "save"), -- 不作属性同步，存放每个赛季的肉鸽数据
        -- 最近肉鸽赛季Id，用于天赋相关重置
        LastSeasonId = prop.prop("Int", "save", -1),
        -- 标记是否有正在进行的肉鸽
        InProgress = prop.prop("Int", "client"),
        -- 天赋数据
        Talent = prop.prop("Int2IntDict", "client save"),
        -- 已获得的天赋点总数
        TalentTotalPoint = prop.prop("Int", "client save", 0),
        -- 正在进行的赛季Id
        ProgressingSeasonId = prop.prop("Int", "client save"),
        -- 正在进行的难度Id
        ProgressingDifficultyId = prop.prop("Int", "client"),
        -- 本周最高肉鸽积分
        WeeklyTotalScore = prop.prop("Int", "client save", 0),
        -- 本周奖励编号
        WeeklyRewardId = prop.prop("Int", "client save", -1),
        -- 本周已领奖阶段
        WeeklyRewardGot = prop.prop("Int2IntDict", "client save"),
        -- 图鉴记录
        Manual = prop.prop("Int2IntSetDict", "client save"),
        -- 图鉴奖励领取记录
        ManualRewardGot = prop.prop("Int2IntSetDict", "client save"),
        -- 上次肉鸽通过的层数
        LastPassRoom = prop.prop("Int", "client save", 0),
        -- 契约信息
        Contract = prop.prop("Int2IntDict", "client save"),
        -- 通关记录
        PassCount = prop.prop("Int2IntDict", "client save"),
    }

    function RougeLikeInfo:EnterDump(SeasonId, bHighestDifficulty)
        local res = {}
        local RougeLikeSeason = self.RougeLikeSeasons[SeasonId]
        res.SeasonId = SeasonId
        res.DifficultyId = RougeLikeSeason.DifficultyId
        res.RoomIndex = RougeLikeSeason.RoomIndex
        res.RoomId = RougeLikeSeason.RoomId
        res.PassRooms = RougeLikeSeason.PassRooms
        res.RandomRooms = RougeLikeSeason.RandomRooms
        res.RandomBlessings = RougeLikeSeason.RandomBlessings
        res.RandomTreasures = RougeLikeSeason.RandomTreasures
        res.Blessings = RougeLikeSeason.Blessings:Dump()
        res.Treasures = RougeLikeSeason.Treasures:Dump()
        res.MaxRefreshTime = RougeLikeSeason:GetMaxRefreshTime()
        res.RefreshTime = RougeLikeSeason.RefreshTime
        res.RefreshCost = RougeLikeSeason:GetRefreshCost()
        res.Shop = RougeLikeSeason:DumpShop()
        res.EventId = RougeLikeSeason.EventId
        res.Talent = self.Talent
        res.TokenExtraRate = RougeLikeSeason:GetTokenExtraRate()
        res.EndPointsExtraRate = RougeLikeSeason:GetEndPointsExtraRate()
        res.ShopDiscount = RougeLikeSeason:GetShopDiscount()
        res.StoryId = RougeLikeSeason.StoryId
        res.CanGetToken = RougeLikeSeason:IsCanGetToken()
        if bHighestDifficulty then
            res.Contract = self.Contract
        end

        return res
    end

    function RougeLikeInfo:FinishDump(RougeLike)
        local res = {}
        if not RougeLike then
            RougeLike = self.RougeLikeSeasons[self.ProgressingSeasonId]
        end

        if not RougeLike then
            return res
        end

        res.Blessings = RougeLike.Blessings:Dump()
        res.Treasures = RougeLike.Treasures:Dump()
        res.PassRooms = RougeLike.PassRooms

        return res
    end

    function RougeLikeInfo:GetSeason(SeasonId)
        return self.RougeLikeSeasons[SeasonId]
    end

    function RougeLikeInfo:NewRougeLike(SeasonId, Difficulty, PlayerInfo, SquadInfo, CommonCombatInfo)
        local Session = self.RougeLikeSeasons:NewRougeLike(SeasonId, Difficulty)
        Session:SaveDungeonInfo(PlayerInfo, SquadInfo, CommonCombatInfo)
        self.RougeLikeSeasons[SeasonId] = Session
        return Session
    end

    function RougeLikeInfo:ClearRougeLike(SeasonId)
        if self.RougeLikeSeasons[SeasonId] then
            self.RougeLikeSeasons[SeasonId] = nil
        end
    end

    function RougeLikeInfo:IsInProgress()
        return self.InProgress == 1
    end

    function RougeLikeInfo:GetHeatSum()
        local HeatSum = 0
        for k, v in pairs(self.Contract) do
            local HeatValue = DataMgr.RougeLikeContract[k].HeatValue or 0
            HeatSum = HeatSum + HeatValue * v
        end

        return HeatSum
    end

    function RougeLikeInfo:GetContractRate(SeasonId)
        local PointContractRate = DataMgr.RougeLikeSeason[SeasonId].PointContractRate or 0
        local HeatSum = self:GetHeatSum()

        return HeatSum * PointContractRate + 1
    end

    function RougeLikeInfo:SetPass(DifficultyId)
        local PreCount = self.PassCount[DifficultyId] or 0
        self.PassCount[DifficultyId] = PreCount + 1
        return PreCount == 0
    end

    function RougeLikeInfo:IsManualUnlocked(ManualType, Key)
        return self.Manual:HasElement(ManualType, Key)
    end

    function RougeLikeInfo:IsManualRewardGot(ManualType, Index)
        return self.ManualRewardGot:HasElement(ManualType, Index)
    end

    FormatProperties(RougeLikeInfo)

return {
    RougeLikeInfo = RougeLikeInfo,
}