---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jinyi.li.
--- DateTime: 2025/1/13 14:37
---

-- 阵容预设
local Class = _G.TypeClass
local BaseTypes = require "BluePrints.Client.CustomTypes.BaseTypes"
local CustomTypes = require "BluePrints.Client.CustomTypes.CustomTypes"
local prop = require "NetworkEngine.Common.Prop"
local FormatProperties = require "NetworkEngine.Common.Assemble".FormatProperties

local Squad = Class("Squad", CustomTypes.CustomAttr)
    Squad.__Props__ = {
        -- 阵容名称
        Name = prop.prop("Str", "client save", ""),
        -- 角色
        Char = prop.prop("ObjId", "client save", ""),
        -- Mod方案
        ModSuit = prop.prop("Int", "client save", 0),
        -- 近战武器
        MeleeWeapon = prop.prop("ObjId", "client save", ""),
        -- 近战武器Mod方案
        MeleeWeaponModSuit = prop.prop("Int", "client save", 0),
        -- 远程武器
        RangedWeapon = prop.prop("ObjId", "client save", ""),
        -- 远程武器Mod方案
        RangedWeaponModSuit = prop.prop("Int", "client save", 0),
        -- 宠物
        Pet = prop.prop("Int", "client save", 0),
        -- 战斗轮盘
        WheelIndex = prop.prop("Int", "client save", 0),
        -- 魅影1
        Phantom1 = prop.prop("ObjId", "client save", ""),
        -- 魅影1武器
        PhantomWeapon1 = prop.prop("ObjId", "client save", ""),
        -- 魅影2
        Phantom2 = prop.prop("ObjId", "client save", ""),
        -- 魅影2武器
        PhantomWeapon2 = prop.prop("ObjId", "client save", ""),
    }
    FormatProperties(Squad)

    function Squad:Init(Info)
        self:Update(Info)
    end

    function Squad:Update(Info)
        for k, v in pairs(Info) do
            self[k] = v
        end
    end

    function Squad:Dump()
        return self:save_dump(self)
    end

local SquadList = Class("SquadList", CustomTypes.CustomList)
    SquadList.ValueType = Squad

    function SquadList:NewSquad(Index, Info)
        self[Index] = Squad(Info)
    end

    function SquadList:CreateSquad(Info)
        return Squad(Info)
    end

return {
    Squad = Squad,
    SquadList = SquadList
}