---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by JuleszzZ.
--- DateTime: 2023/8/22 11:18
--- 系统引导服务端

local Class = _G.TypeClass
local BaseTypes = require "BluePrints.Client.CustomTypes.BaseTypes"
local CustomTypes = require "BluePrints.Client.CustomTypes.CustomTypes"
local prop = require "NetworkEngine.Common.Prop"
local FormatProperties = require "NetworkEngine.Common.Assemble".FormatProperties

local SystemGuide = Class("SystemGuide",CustomTypes.CustomAttr)
    SystemGuide.__Props__ = {
        --引导编号
        SystemGuideId = prop.prop("Int","client save"),
        --前置引导
        PreSysGuideId = prop.getter("Data","PreSysGuideId"),
        --完成任务链
        FinishQuestChain = prop.getter("Data","FinishQuestChain"),
        --完成任务
        FinishQuest = prop.getter("Data","FinishQuest"),
        --引导结束方式
        GuideEnd = prop.getter("Data","GuideEnd"),
        --引导完成状态，0为未完成，1为已完成
        State = prop.prop("Int","client save",'0'),
        --奖励
        RewardId = prop.getter("Data","RewardId"),
    }

    function SystemGuide:Init(SystemGuideId)
        if not SystemGuideId then
            return
        end
        self.SystemGuideId = SystemGuideId
    end

    function SystemGuide:Data()
        return DataMgr.SystemGuide[self.SystemGuideId]
    end

    function SystemGuide:SetFinishState()
        self.State = CommonConst.SystemGuideState.Finished
    end

    function SystemGuide:IsFinished()
        if self.State == CommonConst.SystemGuideState.Finished then
            return true
        end
        return false
    end

    FormatProperties(SystemGuide)

local SystemGuideDict = Class("SystemGuideDict",CustomTypes.CustomDict)
    SystemGuideDict.KeyType = BaseTypes.Int
    SystemGuideDict.ValueType = SystemGuide

    function SystemGuideDict:NewSystemGuide(SystemGuideId)
        return SystemGuide(SystemGuideId)
    end

    function SystemGuideDict:GetSystemGuide(SystemGuideId)
        if self[SystemGuideId] == nil then
            self[SystemGuideId] = self:NewSystemGuide(SystemGuideId)
        end
        return self[SystemGuideId]
    end

return {SystemGuide = SystemGuide, SystemGuideDict = SystemGuideDict}