---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lijinyi.
--- DateTime: 2024/10/17 15:50
---

local Class = _G.TypeClass
local BaseTypes = require "BluePrints.Client.CustomTypes.BaseTypes"
local CustomTypes = require "BluePrints.Client.CustomTypes.CustomTypes"
local prop = require "NetworkEngine.Common.Prop"
local FormatProperties = require "NetworkEngine.Common.Assemble".FormatProperties

local Walnut = Class("Walnut", CustomTypes.CustomAttr)
    Walnut.__Props__ = {
        -- ID->Count
        WalnutBag = prop.prop("Int2IntDict", "save"),
        -- 奖励参数
        RewardSequences = prop.prop("RewardSequence.RewardSequenceAttr", "cross save"),
        -- 核桃消耗记录
        ConsumeRecord = prop.prop("Int2IntDict", "save"),

        -- 当前核桃副本列表
        ValidWalnutDungeons = prop.prop("Dict", "", {}),
        -- 上次刷新时间
        WalnutLastRefreshTime = prop.prop("Int", "", 0),
        -- 当前选择的核桃Id
        WalnutId = prop.prop("Int", "cross", 0),
        -- 当前选择的核桃奖励列表
        WalnutRewardList = prop.prop("List", ""),
        -- 当前选择的核桃稀有度排序
        WalnutRarityList = prop.prop("List", ""),
        -- 当前是否可以选择核桃
        bCanSelectWalnut = prop.prop("Int", ""),
    }

    function Walnut:GetCount(WalnutId)
        return self.WalnutBag[WalnutId] or 0
    end

    function Walnut:Add(WalnutId, Count)
        if not DataMgr.Walnut[WalnutId] then
            return false
        end

        local PreCount = self.WalnutBag[WalnutId] or 0
        self.WalnutBag[WalnutId] = PreCount + Count
        return true
    end

    function Walnut:Remove(WalnutId, Count, bConsume)
        Count = Count or 1
        local PreCount = self.WalnutBag[WalnutId]
        if not PreCount then
            return false
        end

        if PreCount < Count then
            return false
        end

        self.WalnutBag[WalnutId] = PreCount - Count
        if bConsume then
            -- 核桃消耗记录
            local ConsumeCount = self.ConsumeRecord[WalnutId] or 0
            ConsumeCount = ConsumeCount + Count
            self.ConsumeRecord[WalnutId] = ConsumeCount
        end

        return true
    end

    function Walnut:SelectWalnut(WalnutId)
        self.WalnutId = WalnutId
        self:SetCanSelectWalnut(false)
    end

    function Walnut:UpdateWalnutRewardList(WalnutRewardList, RarityList)
        self.WalnutRewardList = WalnutRewardList
        self.WalnutRarityList = RarityList
    end

    function Walnut:ResetReward()
        self.WalnutRewardList = {}
        self.WalnutRarityList = {}
    end

    function Walnut:SetCanSelectWalnut(bCanSelect)
        self.bCanSelectWalnut = bCanSelect and 1 or 0
    end

    function Walnut:CanSelectWalnut()
        return self.bCanSelectWalnut == 1 and self.WalnutId > 0
    end

    FormatProperties(Walnut)

return {Walnut = Walnut}
