---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lijinyi.
--- DateTime: 2023/9/25 13:54
---

-- @SnowMoon
-- CheckCondition的对象有三个，C/S/DS
-- C端调用则使用服务端同步到客户端上的属性进行本地条件校验，不可靠，但是效率高
-- S端调用则使用服务端上的属性进行校验，但是无法完全校验所有条件，对于DS上的条件是无法校验的，需要客户端向DS调用RPC进行二次条件校验，最终结果可靠，但是效率低
-- DS端调用则使用DS上的属性进行校验，只能校验战斗内相关的条件，但是无法校验与玩家相关的属性，可靠，但是不完整

local ConditionUtils = {}

-- C/S/DS端调用
function ConditionUtils.CheckCondition(Avatar, ConditionIds, bShowFailed)
    if not Avatar then
        DebugPrint("CheckCondition bug Avatar is nil")
        return false
    end

    if not ConditionIds then
        return true
    end

    -- 默认不显示
    bShowFailed = bShowFailed or false
    if type(ConditionIds) ~= "table" then
        ConditionIds = { ConditionIds }
    end

    for i=1, #ConditionIds do
        local ConditionId = ConditionIds[i]
        if not ConditionUtils.CheckConditionInternal(Avatar, ConditionId) then
            ConditionUtils:CheckShowFailed(ConditionId, false, bShowFailed)
            return false
        end
    end
    return true
end

function ConditionUtils.CheckConditionInternal(Avatar, ConditionId, ConditionCheckId)
    local ConditionInfo = DataMgr.Condition[ConditionId]
    if not ConditionInfo then
        return false
    end

    local function CheckResult(ret)
        if ConditionInfo.IsNot then
            return not ret
        else
            return ret
        end
    end

    local Logic = string.lower(ConditionInfo.ConditionLogic)
    if Logic == "and" then
        for Condition, List in pairs(ConditionInfo.ConditionMap) do
            for i=1, #List do
                -- DebugPrint("Condition:",Condition)
                if not ConditionUtils["Judge"..Condition](Avatar, List[i], ConditionCheckId) then
                    return CheckResult(false)
                end
            end
        end

        return CheckResult(true)
    elseif Logic == "or" then
        for Condition, List in pairs(ConditionInfo.ConditionMap) do
            for i=1, #List do
                if ConditionUtils["Judge"..Condition](Avatar, List[i], ConditionCheckId) then
                    return CheckResult(true)
                end
            end
        end

        return CheckResult(false)
    else
        error("UnExpected ConditionLogic: "..Logic)
    end

    return CheckResult(false)
end

-- @SnowMoon 指定服务端进行条件判断，涉及奖励等重要条件时应调用此接口以防作弊
-- 只有C端需要调用
function ConditionUtils.ServerCheckCondition(Avatar, ConditionId, Callback, bShowFailed)
    assert(not GWorld:IsSkynetServer() and not IsDedicatedServer(GWorld.GameInstance), "ServerCheckCondition 非Server/DedicatedServer 接口")

    Avatar:ServerCheckCondition(ConditionId, Callback, bShowFailed)
end

function ConditionUtils:CheckShowFailed(ConditionId, Result, bShowFailed)
    if not bShowFailed then
        return
    end

    if Result then
        return
    end

    local UIManger = GWorld.GameInstance:GetGameUIManager()
    local ShowText = DataMgr.Condition[ConditionId].ConditionText
    if not ShowText then
        UIManger:ShowUITip(UIConst.Tip_CommonToast, "Unconfigured ConditionText "..tostring(ConditionId))
    else
        UIManger:ShowUITip(UIConst.Tip_CommonToast, GText(ShowText))
    end
end

-------------------------------------------- JudgeXX -------------------------------------------------------------------
function ConditionUtils:JudgePlayerLevelMin(Params)
    if GWorld:IsSkynetServer() or not IsDedicatedServer(GWorld.GameInstance) then
        return self.Level >= Params
    end

    return false
end

function ConditionUtils:JudgePlayerLevelMax(Params)
    if GWorld:IsSkynetServer() or not IsDedicatedServer(GWorld.GameInstance) then
        return self.Level <= Params
    end
    return false
end

function ConditionUtils:JudgeQuestChain(Params)
    if GWorld:IsSkynetServer() or not IsDedicatedServer(GWorld.GameInstance) then
        if self.QuestChains[Params] and (self.QuestChains[Params]:IsFinish() or self.QuestChains[Params]:GetAssumeFinish()) then
            return true
        end
        return self.QuestChains[Params] and self.QuestChains[Params]:IsFinish() and true or false
    end
    return false
end

function ConditionUtils:JudgeQuest(Params)
    if GWorld:IsSkynetServer() or not IsDedicatedServer(GWorld.GameInstance) then
        local QuestChainId = tonumber(string.sub(tostring(Params), 1, 6))
        local QuestChain = self.QuestChains[QuestChainId]
        if QuestChain then
            return QuestChain.CompleteQuestId:HasValue(Params) or QuestChain:GetAssumeFinish()
        end
        return false
    end
    return false
end

function ConditionUtils:JudgeTrueQuest(Params)
    if GWorld:IsSkynetServer() or not IsDedicatedServer(GWorld.GameInstance) then
        local QuestChainId = tonumber(string.sub(tostring(Params), 1, 6))
        local QuestChain = self.QuestChains[QuestChainId]
        return QuestChain and QuestChain.CompleteQuestId:HasValue(Params) and true or false
    end
    return false
end

function ConditionUtils:JudgeTrueQuestChain(Params)
    if GWorld:IsSkynetServer() or not IsDedicatedServer(GWorld.GameInstance) then
        return self.QuestChains[Params] and self.QuestChains[Params]:IsFinish() and true or false
    end
    return false
end


function ConditionUtils:JudgeRegionCapturePet(CreatorId)
    if GWorld:IsSkynetServer() then
        local WorldRegionEid = self:GetStaticCreatorRegionEid_StaticCreatorId(CreatorId)
        if not WorldRegionEid then
            return false 
        end
        local PetRegionAttr = self.PetRegionAttrs:GetPetRegionAttr(WorldRegionEid)
        return PetRegionAttr and PetRegionAttr:IsSuccess()
    else
        if not IsDedicatedServer(GWorld.GameInstance) then
            local GameMode = UGameplayStatics.GetGameMode(self)
            if not IsValid(GameMode) then
                return false
            end
            local RegionDataMgrSubSystem = GameMode:GetRegionDataMgrSubSystem()
            if RegionDataMgrSubSystem then
                local WorldRegionEids = RegionDataMgrSubSystem:GetControlWorldRegionEidByCreatorId(CreatorId)
                for WorldRegionEid, _ in pairs(WorldRegionEids) do
                    local PetRegionAttr = self.PetRegionAttrs:GetPetRegionAttr(WorldRegionEid)
                    if PetRegionAttr then
                        return PetRegionAttr and PetRegionAttr:IsSuccess()
                    end
                end
            end
            return false
        end
        return false
    end
    return false
end


function ConditionUtils:JudgeVarEqual(Params)
    if GWorld:IsSkynetServer() or not IsDedicatedServer(GWorld.GameInstance) then
        return self.StoryVariable[Params[1]] ~= nil and self.StoryVariable[Params[1]] == Params[2]
    end
    return false
end




function ConditionUtils:JudgeImpression(Params)
    if GWorld:IsSkynetServer() or not IsDedicatedServer(GWorld.GameInstance) then
        local TalkTriggerId, StorylineState = Params[1], Params[2]

        if (StorylineState == 1 and AvatarUtils:IsStorylineComplete(self, TalkTriggerId))
        or (StorylineState == 2 and AvatarUtils:IsStorylineSuccess(self, TalkTriggerId))
        or (StorylineState == 3 and AvatarUtils:IsStorylineFailure(self, TalkTriggerId)) then
            return true
        end
    end
    return false
end

function ConditionUtils:JudgeHaveResource(Params)
    if GWorld:IsSkynetServer() or not IsDedicatedServer(GWorld.GameInstance) then
        local ResourceId, ResourceCount = Params[1], Params[2]

        local Count = self.Resources:QueryResourceCount(ResourceId)
        return Count >= ResourceCount
    end

    return false
end

function ConditionUtils:JudgeMechanismState(Params, ConditionCheckId)
    if GWorld:IsSkynetServer() then
        ConditionUtils.CallDedicatedServerCondition(self,"MechanismState", Params, ConditionCheckId)

        return true -- 跳过DS条件
    else
        local StaticId, ManualItemId, StateId = tonumber(Params[1]), tonumber(Params[2]), tonumber(Params[3])
        local GameState = UGameplayStatics.GetGameState(GWorld.GameInstance)
        if StaticId == 0 and ManualItemId ~= 0 then
            return GameState.ManualMechanismStateIdMap:Find(ManualItemId) == StateId
        elseif ManualItemId == 0 and StaticId ~= 0 then
            return GameState.MechanismStateIdMap:Find(StaticId) == StateId
        end
        return true
    end
end

function ConditionUtils:JudgeAvatarStatus(Params)
    if GWorld:IsSkynetServer() or not IsDedicatedServer(GWorld.GameInstance) then
        local AvatarStatus, Condition = Params[1], Params[2]
        local Status = CommonConst.AvatarStatus[AvatarStatus]
        local InStatus = false
        if Status then
            if GWorld:IsSkynetServer() then
                InStatus = self:InStatus(Status)
            else
                InStatus = self:InStatus(nil, Status)
            end
        end

        if Condition == "T" then
            return InStatus
        elseif Condition == "F" then
            return not InStatus
        end
    end

    return false;
end

function ConditionUtils:JudgeSubRegionType(Params)
    if GWorld:IsSkynetServer() or not IsDedicatedServer(GWorld.GameInstance) then
        return self:CheckSubRegionType(nil, Params)
    end

    return false
end

function ConditionUtils:JudgeDungeonComplete(Params)
    if GWorld:IsSkynetServer() or not IsDedicatedServer(GWorld.GameInstance) then
        local DungeonId, Relation, Counts = Params[1], Params[2], Params[3]
        local Dungeon = self.Dungeons[DungeonId]
        if not Dungeon then
            if Relation < 0 or (Relation == 0 and Counts == 0) then
                return true
            else
                return false
            end
        end

        local PassCount = Dungeon.PassCount
        return (Relation > 0 and PassCount >= Counts) or
                (Relation < 0 and PassCount <= Counts) or
                (Relation == 0 and PassCount == Counts)
    end

    return false;
end


function ConditionUtils:JudgePhaseQuestEnd(Params)
    if GWorld:IsSkynetServer() or not IsDedicatedServer(GWorld.GameInstance) then
        local EventId, PhaseId = Params[1], Params[2]
        local QuestIds = DataMgr.QuestPhaseMap[EventId][PhaseId]
        local ExcelToProp = {
            ["CommonQuestDetail"] = "StarterQuests",
            ["ModGuideQuest"] = "ModGuideQuests",
        }
        local TargetCounters = self[ExcelToProp[DataMgr.EventMain[EventId].SubExcel]]

        for _, QuestId in pairs(QuestIds) do
            local TargetCounter = TargetCounters[QuestId]
            if not TargetCounter then
                return false
            end
            if TargetCounter:IsComplete() == false or TargetCounter.RewardsGot == false then
                return false
            end
        end
        return true
    end
    return false;
end

function ConditionUtils:JudgeDailyLoginEnd(Params)
    if GWorld:IsSkynetServer() or not IsDedicatedServer(GWorld.GameInstance) then
        local EventId = Params[1]
        local DailyLogin = self.DailyLogin[EventId]
        local DailyLoginExcel = DataMgr.DailyLogin[EventId]
        if not DailyLogin or not DailyLoginExcel then
            return false
        end
        
        if CommonUtils.Size(DailyLogin.RewardsRecord) >= DailyLoginExcel.LoginDuration then
            return true
        end
        return false
    end
    return false;
end

function ConditionUtils:JudgeConstantBool(Params)
    Params = string.lower(Params)
    return Params == "t" or Params == "true"
end

function ConditionUtils:JudgeTestClientCon(Params, ConditionCheckId)
    if GWorld:IsSkynetServer() then
        ConditionUtils.CallClientCondition(self,"TestClientCon", Params, ConditionCheckId)

        return true
    elseif IsDedicatedServer(GWorld.GameInstance) then
        return false
    else
        print(_G.LogTag, "JudgeTestClientCon")
        return true
    end
end

function ConditionUtils:JudgeInStoryMode(Params, ConditionCheckId)
    local bIsInStoryMode = false
    if Params == "T" then
        bIsInStoryMode = true
    end

    if GWorld:IsSkynetServer() then
        ConditionUtils.CallClientCondition(self, "InStoryMode", Params, ConditionCheckId)
        return true
    elseif IsDedicatedServer(GWorld.GameInstance) then
        return false
    else
        local Controller = UE4.UGameplayStatics.GetPlayerController(GWorld.GameInstance, 0)
        if (Controller == nil) then
            return false
        end

        local PlayerController = Controller:Cast(UE4.ASinglePlayerController)
        if (PlayerController == nil) then
            return false
        end

        return PlayerController:GetStoryModeState() == bIsInStoryMode
    end
end

function ConditionUtils:JudgeInDungeon(Params)
    if GWorld:IsSkynetServer() then
        local DungeonComponentBase = require "src.components.dungeon_components.DungeonComponentBase"
        return self:IsInDungeon() and DungeonComponentBase:GetUniqueDungeonId() == Params
    elseif not IsDedicatedServer(GWorld.GameInstance) then
        return self:IsInDungeon() and GWorld.GameInstance:GetCurrentDungeonId() == Params
    else
        local GameMode = UE4.UGameplayStatics.GetGameMode(GWorld.GameInstance)
        return GameMode:IsInDungeon() and GameMode.DungeonId == Params
    end
end

function ConditionUtils:JudgeInHardBossDifficulty(Params)
    if GWorld:IsSkynetServer() then
        if not self:IsInHardBoss() then
            return false
        end

        if self:IsInMultiDungeon() then
            local DungeonComponentBase = require "src.components.dungeon_components.DungeonComponentBase"
            local DungeonId = DungeonComponentBase:GetUniqueDungeonId()
            local HardBossInfo = DataMgr.HardBossDg[DungeonId]
            if not HardBossInfo then
                return false
            end

            return HardBossInfo.DifficultyId == Params
        end

        return self:IsInHardBoss() and self.CurrentHardBossInfo and self.CurrentHardBossInfo.DifficultyId == Params
    elseif not IsDedicatedServer(GWorld.GameInstance) then
        if not self:IsInHardBoss() then
            return false
        end

        if self:IsInMultiDungeon() then
            local DungeonId = WorldTravelSubsystem():GetCurrentSceneId()
            local HardBossInfo = DataMgr.HardBossDg[DungeonId]
            if not HardBossInfo then
                return false
            end

            return HardBossInfo.DifficultyId == Params
        else
            return self.HardBossInfo and self.HardBossInfo.DifficultyId == Params
        end
    else
        local DungeonId = WorldTravelSubsystem():GetCurrentSceneId()
        local HardBossInfo = DataMgr.HardBossDg[DungeonId]
        if not HardBossInfo then
            return false
        end

        return HardBossInfo.DifficultyId == Params
    end
end

function ConditionUtils:JudgeCharEquipRarityLevelModCount(Params)
    if GWorld:IsSkynetServer() or not IsDedicatedServer(GWorld.GameInstance) then
        local Rarity, ModLevel,Count = Params[1], Params[2], Params[3]
        for _ ,Char in pairs(self.Chars) do
            local ModCount = 0
            local ModSuit = AvatarUtils:GetTargetModSuit(Char, Char.ModSuitIndex)
            for ModSlotId,ModSlotEid in pairs(ModSuit) do
                local Mod = self.Mods[ModSlotEid]
                if Mod and Mod.Rarity >= Rarity and Mod.Level >= ModLevel then
                    ModCount = ModCount + 1
                    if ModCount >= Count then
                        return true
                    end
                end
            end
        end
    end
    return false
end

function ConditionUtils:JudgeCurrentCharId(Params)
    if GWorld:IsSkynetServer() or not IsDedicatedServer(GWorld.GameInstance) then
        local CurrentChar = self.Chars[self.CurrentChar]
        return CurrentChar.CharId == Params
    end
    return false
end

function ConditionUtils:JudgeOwnCharIdAndLevel(Params)
    if GWorld:IsSkynetServer() or not IsDedicatedServer(GWorld.GameInstance) then
        local CharId, CharLevel = Params[1], Params[2]
        for _ ,CharInfo in pairs(self.Chars) do
            if CharInfo.CharId == CharId and CharInfo.Level >= CharLevel then
                return true
            end
        end
    end
    return false
end

function ConditionUtils:JudgeDynamicEventCompleteTimes(Params)
    if GWorld:IsSkynetServer() or not IsDedicatedServer(GWorld.GameInstance) then
        local DynamicEventId, Times = Params[1], Params[2]
        if self.DynamicQuests[DynamicEventId] and self.DynamicQuests[DynamicEventId].AlreadyCompleteTimes >= Times then
            return true
        end
    end
    return false
end

function ConditionUtils:JudgeExploreGroup(Params)
    if GWorld:IsSkynetServer() or not IsDedicatedServer(GWorld.GameInstance) then
        for ExploreId ,Info in pairs(self.Explores) do
            if ExploreId == Params and Info:IsComplete() then
                return true
            end
        end
    end
    return false
end

function ConditionUtils:JudgeImprShopUnlock(Params)
    local TargetRegionId = Params[1]
    local ImpressionType = Params[2]
    local TargetValue = Params[3]
    if GWorld:IsSkynetServer() or not IsDedicatedServer(GWorld.GameInstance) then
        local CurrentImpression = self.Impressions:GetImpression(TargetRegionId)
        if not CurrentImpression then return false end
        if ImpressionType == "Any" then
            return CurrentImpression:GetImpressionValueByType(CommonConst.ImpressionType.Benefit) >= TargetValue or
            CurrentImpression:GetImpressionValueByType(CommonConst.ImpressionType.Morality) >= TargetValue or
            CurrentImpression:GetImpressionValueByType(CommonConst.ImpressionType.Wisdom) >= TargetValue or
            CurrentImpression:GetImpressionValueByType(CommonConst.ImpressionType.Empathy) >= TargetValue or
            CurrentImpression:GetImpressionValueByType(CommonConst.ImpressionType.Chaos) >= TargetValue
        elseif ImpressionType == "All" then
            return CurrentImpression:GetImpressionValueByType(CommonConst.ImpressionType.Benefit) >= TargetValue and
            CurrentImpression:GetImpressionValueByType(CommonConst.ImpressionType.Morality) >= TargetValue and
            CurrentImpression:GetImpressionValueByType(CommonConst.ImpressionType.Wisdom) >= TargetValue and
            CurrentImpression:GetImpressionValueByType(CommonConst.ImpressionType.Empathy) >= TargetValue and
            CurrentImpression:GetImpressionValueByType(CommonConst.ImpressionType.Chaos) >= TargetValue
        else
            local CurrentValue = CurrentImpression:GetImpressionValueByType(ImpressionType)
            if TargetValue <= CurrentValue then
                return true
            end
        end
    end
    return false
end

function ConditionUtils:JudgeRougeLikePreAward(Params)
    if not GWorld:IsSkynetServer() then
        return false
    end

    local AwardType = Params[1]
    local AwardId = Params[2]
    local SeasonId = self:GetCurrentRougeLikeSeason()
    local RougeLike = self.RougeLike:GetSeason(SeasonId)
    if not RougeLike then
        return false
    end

    local AwardList = RougeLike[AwardType.."s"]
    return AwardList[AwardId]
end

function ConditionUtils:JudgeRougeLikeGroupMin(Params)
    if not GWorld:IsSkynetServer() then
        return false
    end

    local AwardType = Params[1]
    local GroupId = Params[2]
    local Count = Params[3]
    local SeasonId = self:GetCurrentRougeLikeSeason()
    local RougeLike = self.RougeLike:GetSeason(SeasonId)
    if not RougeLike then
        return false
    end

    -- todo @SnowMoon 反复check的性能问题，看看有什么别的方式能代替这种check
    local AwardList = RougeLike[AwardType.."s"]
    local RealCount = 0
    for AwardId, _ in pairs(AwardList) do
        if DataMgr["RougeLike"..AwardType][AwardId][AwardType.."Group"] == GroupId then
            RealCount = RealCount + 1
        end

        if RealCount >= Count then
            return true
        end
    end

    return false
end

function ConditionUtils:JudgeRougeLikeGroupMax(Params)
    if not GWorld:IsSkynetServer() then
        return false
    end

    local AwardType = Params[1]
    local GroupId = Params[2]
    local Count = Params[3]
    local SeasonId = self:GetCurrentRougeLikeSeason()
    local RougeLike = self.RougeLike:GetSeason(SeasonId)
    if not RougeLike then
        return false
    end

    -- todo @SnowMoon 反复check的性能问题，看看有什么别的方式能代替这种check
    local AwardList = RougeLike[AwardType.."s"]
    local RealCount = 0
    for AwardId, _ in pairs(AwardList) do
        if DataMgr["RougeLike"..AwardType][AwardId][AwardType.."Group"] == GroupId then
            RealCount = RealCount + 1
        end

        if RealCount >= Count then
            return false
        end
    end

    return true
end

function ConditionUtils:JudgeRougeLikeDifficulty(Params)
    if not GWorld:IsSkynetServer() then
        return false
    end

    local DifficultyId = Params[1]
    local Logic = Params[2]
    local function CheckResult(bOriginResult)
        if Logic == "T" then
            return bOriginResult
        else
            return not bOriginResult
        end
    end

    local SeasonId = self:GetCurrentRougeLikeSeason()
    local RougeLike = self.RougeLike:GetSeason(SeasonId)
    if not RougeLike then
        return CheckResult(false)
    end

    return CheckResult(RougeLike.DifficultyId == DifficultyId)
end

function ConditionUtils:JudgeRougeLikePassRoom(Params)
    if not GWorld:IsSkynetServer() then
        return false
    end

    local PassRoom = Params
    local SeasonId = self:GetCurrentRougeLikeSeason()
    local RougeLike = self.RougeLike:GetSeason(SeasonId)
    if not RougeLike then
        return false
    end

    return RougeLike.PassRooms:Length() >= PassRoom
end
function ConditionUtils:JudgeDialogueHasRead(DialogueId)
    if not GWorld:IsSkynetServer() and IsDedicatedServer(GWorld.GameInstance) then
        return false
    end
    if self.CompletedDialogues[DialogueId] then
        return true
    else
        return false
    end
end

function ConditionUtils:JudgeEquipPetId(PetUnitId)
    if not GWorld:IsSkynetServer() and IsDedicatedServer(GWorld.GameInstance) then
        return false
    end
    if self.CurrentPet == 0 then
        return false
    end
    if PetUnitId == -1 then
        return true
    end
    local Pet = self.Pets[self.CurrentPet]

    if Pet and Pet.PetId == PetUnitId then
        return true
    end
    return false
end

function ConditionUtils:JudgeUnlockMountId(MountId)
    if not GWorld:IsSkynetServer() and IsDedicatedServer(GWorld.GameInstance) then
        return false
    end
    if MountId == -1 then
        if CommonUtils.Size(self.Mounts) > 0 then
            return true
        else
            return false
        end
    end
    if self.Mounts[MountId] then
        return true
    else
        return false
    end
end

function ConditionUtils:JudgeConditionalRewardEventEnd(EventId)
    if not GWorld:IsSkynetServer() and IsDedicatedServer(GWorld.GameInstance) then
        return false
    end
    if self.ClaimActivityConditionRewardRecord[EventId] then 
        return true
    else
        return false
    end
end

function ConditionUtils:JudgeDualTerminalLogin(DeviceType)
    if not GWorld:IsSkynetServer() and IsDedicatedServer(GWorld.GameInstance) then
        return false
    end
    if not self.SdkDeviceId[DeviceType] then
        DebugPrint("JudgeConditionalDualTerminalLogin",DeviceType)
        return false
    end
    DebugPrint("JudgeConditionalDualTerminalLogin true",DeviceType)
    return true
end

local function IsGameServerOrClient()
    if not GWorld:IsSkynetServer() and IsDedicatedServer(GWorld.GameInstance) then
        return false
    end
    return true
end

function ConditionUtils:JudgePlayerLvEventEnd(EventId)
    if not IsGameServerOrClient() then
        return false
    end

	local AllComplete = true
	for k,v in pairs(DataMgr.PlayerLvEvent[EventId]) do
		if self.ActivityPlayerLvRewardsGot:HasElement(EventId,k) == false then
			AllComplete = false
			break
		end
	end
    return AllComplete
end

function ConditionUtils:JudgeHardBossComplete(Params)
    local DifficultyId, Times = Params[1], Params[2]
    if GWorld:IsSkynetServer() or not IsDedicatedServer(GWorld.GameInstance) then
        return self.HardBoss:GetPassCount(DifficultyId) >= Times
    end
    return false
end

function ConditionUtils:JudgeDungeonType(Params)
    local DungeonType = Params

    if GWorld:IsSkynetServer() then
        local DungeonComponentBase = require "src.components.dungeon_components.DungeonComponentBase"
        if not DungeonComponentBase:IsDungeonRunning() then
            return false
        end

        local CurDungeonType = DungeonComponentBase:GetDungeonType()
        return CurDungeonType == DungeonType
    else
        if not WorldTravelSubsystem():IsDungeonWorld() then
            return false
        end

        local CurDungeonType = WorldTravelSubsystem():GetCurrentDungeonType()
        return CurDungeonType == DungeonType
    end
end

function ConditionUtils:JudgeRougeLikeManual(Params)
    local ManualType, ManualId, ConditionLogic = Params[1], Params[2], Params[3]

    if GWorld:IsSkynetServer() or not IsDedicatedServer(GWorld.GameInstance) then
        local bUnLocked = self.RougeLike:IsManualUnlocked(ManualType, ManualId)
        if ConditionLogic == "T" then
            return bUnLocked
        else
            return not bUnLocked
        end
    end

    return false
end

function ConditionUtils:JudgeRougeLikeComplete(Params)
    local DifficultyId = Params

    if GWorld:IsSkynetServer() or not IsDedicatedServer(GWorld.GameInstance) then
        return self.RougeLike.PassCount:Get(DifficultyId, 0) > 0
    end

    return false
end

function ConditionUtils:JudgePlayerInBattlePass(Params)
    local Avatar = GWorld:GetAvatar()
    if Avatar then
        local BattlePassVersion = Avatar.BattlePassVersion
        return BattlePassVersion ~= 0
    end

    return false
end

function ConditionUtils:JudgeTeleportIsUnlock(Params, ConditionCheckId)
    local TargetData = DataMgr.TeleportPoint[Params]
    if not TargetData or not TargetData.StaticId or not TargetData.TeleportPointSubRegion then
        return false
    end
    if GWorld:IsSkynetServer() then
        ConditionUtils.CallClientCondition(self, "TeleportIsUnlock", Params, ConditionCheckId)
        return true
    end
    local GameMode = UE4.UGameplayStatics.GetGameMode(GWorld.GameInstance)
    if GameMode then
        local RegionDataMgrSubSystem = GameMode:GetRegionDataMgrSubSystem()
        if RegionDataMgrSubSystem then
            local TmpFullRegionStoreDatas = GameMode:GetRegionDataMgrSubSystem().DataLibrary:GetFullRegionStoreDatas()
            if TmpFullRegionStoreDatas then
                for _, RegionBaseData in pairs(TmpFullRegionStoreDatas) do
                    if TargetData.StaticId == RegionBaseData.CreatorId and TargetData.TeleportPointSubRegion == RegionBaseData.SubRegionId then
                        return RegionBaseData.State and RegionBaseData.State.OpenState or false
                    end
                end
            end
        end
    end
    return false
end

function ConditionUtils:JudgeLoginDay(Params)
    local Day = Params
    if GWorld:IsSkynetServer() or not IsDedicatedServer(GWorld.GameInstance) then
        return self.TotalLoginDays >= Day
    end

    return false
end

function ConditionUtils:JudgeRougeLikePreRoom(Params)
    if not GWorld:IsSkynetServer() then
        return false
    end

    local RoomId = Params
    local SeasonId = self:GetCurrentRougeLikeSeason()
    local RougeLike = self.RougeLike:GetSeason(SeasonId)
    if not RougeLike then
        return false
    end

    return CommonUtils.HasValue(RougeLike.PassRooms, RoomId)
end

function ConditionUtils:JudgeTimeArrived(Params)
    local TimeStr = Params
    -- 提取年月日时分秒
    local year, month, day, hour, min, sec = TimeStr:match("(%d+)-(%d+)-(%d+) (%d+):(%d+):(%d+)")
    year = tonumber(year)
    month = tonumber(month)
    day = tonumber(day)
    hour = tonumber(hour)
    min = tonumber(min)
    sec = tonumber(sec)

    local timestamp = TimeUtils.DataToTimestampForArea(year, month, day, hour, min, sec, "China")
    if GWorld:IsSkynetServer() then
        timestamp = TimeUtils.EastEightToLocalTimestamp(timestamp)
    else
        timestamp = DataMgr.LocalTimeProxy(timestamp)
    end

    local now = TimeUtils.NowTime()
    return now >= timestamp
end

function ConditionUtils:JudgeHaveResourceSType(Params)
    local ResourceSType = Params[1]
    local Count = Params[2]

    if GWorld:IsSkynetServer() then
        local HaveCount = self:GetResourceSTypeCount(ResourceSType)
        return HaveCount >= Count
    elseif not IsDedicatedServer(GWorld.GameInstance) then
        -- todo: @SnowMoon 如果不建立索引的性能太差则再考虑优化客户端check时的性能
        local HaveCount = 0
        for _, Resource in pairs(self.Resources) do
            if Resource.ResourceSType == ResourceSType then
                HaveCount = HaveCount + Resource.Count
            end
        end

        return HaveCount >= Count
    end

    return false
end

function ConditionUtils:JudgeFollowCommunityComplete(Params)
    if not GWorld:IsSkynetServer() and not IsDedicatedServer(GWorld.GameInstance) then
        local DevServerList = require "BluePrints.UI.GameLogin.DevServerList"
        if not DevServerList[self.Hostnum] then return false end
        local EMCache = require "EMCache.EMCache"
        local Languagetype = "ChinaCN"
        local SystemLanguage = EMCache:Get("SystemLanguage") or "CN"
        local IsGlobalPak = UE.AHotUpdateGameMode.IsGlobalPak()
        if IsGlobalPak then
            Languagetype = "Abroad"..SystemLanguage
        end
        local CommunityInfo = DataMgr.FollowCommunityEvent[Languagetype]
        if not CommunityInfo or not CommunityInfo.CommunityList then return false end
        for _,CommunityId in ipairs(CommunityInfo.CommunityList) do
            if not self.Community:IsRewardGot(CommunityId) then
                return false
            end
        end
        return true
    end
    return false
end

function ConditionUtils:JudgeIsCurrentCharEquipMod(Params)
    local bIsCurrentCharEquipMod = false
    if Params == "T" then
        bIsCurrentCharEquipMod = true
    end
    local bEquipMod = false
    if GWorld:IsSkynetServer() or not IsDedicatedServer(GWorld.GameInstance) then
        local CurrentChar = self.Chars[self.CurrentChar]
        for ModSlotId, ModSlotEid in pairs(AvatarUtils:GetTargetModSuit(CurrentChar, CurrentChar.ModSuitIndex)) do
			local mod = self.Mods[ModSlotEid]
			if mod then
				bEquipMod = true
                break
			end
		end
    end
    return bEquipMod == bIsCurrentCharEquipMod
end

function ConditionUtils:JudgeActivePropEffectId(Params, ConditionCheckId)
    if GWorld:IsSkynetServer() then
        ConditionUtils.CallClientCondition(self, "ActivePropEffectId", Params, ConditionCheckId)
        return true
    elseif IsDedicatedServer(GWorld.GameInstance) then
        return false
    else
        local Player = UE4.UGameplayStatics.GetPlayerCharacter(GWorld.GameInstance, 0)
        if Player == nil then
            return false
        end

        if not Player.ActivePropEffectId then
            return false
        end
        return Player.ActivePropEffectId == Params
    end
    
end

function ConditionUtils:JudgeBattleWheelEquipResourceId(Params, ConditionCheckId)
    if GWorld:IsSkynetServer() then
        ConditionUtils.CallClientCondition(self, "BattleWheelEquipResourceId", Params, ConditionCheckId)
        return true
    elseif IsDedicatedServer(GWorld.GameInstance) then
        return false
    else
        if not Params or not type(Params) == "number" then
            DebugPrint("lgc@JudgeBattleWheelEquipResourceId Params is not number")
            return false
        end

        local Ret = false
        local Avatar = GWorld:GetAvatar()
        if not Avatar or not Avatar.Wheels or not next(Avatar.Wheels) then
            return false
        else
            for _, Wheel in pairs(Avatar.Wheels) do
                if Wheel then
                    for _, Slot in pairs(Wheel) do
                        if Slot then
                            if Slot.ResourceId and Slot.ResourceId == Params then
                                Ret = true
                                break
                            end
                        end
                    end
                end
                if Ret then
                    break
                end
            end
        end

        DebugPrint("lgc@JudgeBattleWheelEquipResourceId Params = "..tostring(Params).. " Ret = "..tostring(Ret))
        return Ret
    end
    
end

function ConditionUtils:JudgeDailyFreeTicketAmount(Params)
    local Now = TimeUtils.NowTime()
    local OpenEventId
    for EventId, _ in pairs(DataMgr.DoubleModDrop) do
        local EventConf = DataMgr.EventMain[EventId]
        if EventConf and EventConf.EventStartTime and EventConf.EventEndTime then
            if Now >= EventConf.EventStartTime and Now < EventConf.EventEndTime then
                OpenEventId = EventId
                break
            end
        end
    end

    local DailyFreeTicketAmount = DataMgr.ModDropConstant.DailyFreeTicketAmount.ConstantValue

    if not OpenEventId or not DailyFreeTicketAmount then
        return false
    end

    local DoubleModDropProp = self.DoubleModDrop[OpenEventId]
    if DoubleModDropProp then 
        local RemainTimes = DailyFreeTicketAmount - DoubleModDropProp:GetEliteRushTimes()
        if RemainTimes < Params then
            return false
        end
    else
        if DailyFreeTicketAmount < Params then
            return false
        end
    end

    return true
end

function ConditionUtils:JudgeHaveItem(Params)
    if GWorld:IsSkynetServer() or not IsDedicatedServer(GWorld.GameInstance) then
        local ItemType,ItemId,Count = Params[1],Params[2],Params[3]
        local CheckFuncName = "Check"..ItemType.."Enough"
        local CheckMethod = self[CheckFuncName]
        if not CheckMethod then return false end
        if CheckMethod(self,{[ItemId] = Count}) then
            return true
        end
    end
    return false
end

function ConditionUtils:JudgeBuyGoods(Params)
    if GWorld:IsSkynetServer() or not IsDedicatedServer(GWorld.GameInstance) then
        local ShopItemId,Count = Params[1],Params[2]
        local ShopItem = self.ShopItems[ShopItemId]
        if not ShopItem then return false end
        return Count <= ShopItem.AlreadyPurchaseTimes
    end
    return false
end

function ConditionUtils:JudgeGachaCount(Params)
    if GWorld:IsSkynetServer() or not IsDedicatedServer(GWorld.GameInstance) then
        local GachaId,Count = Params[1],Params[2]
        local Gacha = self.SkinGachaPool[GachaId]
        if not Gacha then return false end
        return Count <= Gacha.DrawCounts
    end
    return false
end

function ConditionUtils:JudgeInteractTriggerFinished(Params)
    return self:CheckInteractTriggerRewardIsGot(Params)
end

function ConditionUtils:JudgeForgeLevel(Params)
    if GWorld:IsSkynetServer() then
        return self.WeaponForgeLevel > Params
    end
    return false
end

function ConditionUtils:JudgeHyperCardLevel(Params)
    if GWorld:IsSkynetServer() then
        local WeaponId = Params[1]
        local NeedHyperLevel = Params[2]
        local WeaponConf = DataMgr.Weapon[WeaponId]
        if WeaponConf.WeaponSubType == CommonConst.WeaponSubType.Normal then
            return false
        end
        local bFinishCond = false
        for _, Weapon in pairs(self.Weapons) do
            if Weapon.WeaponId == WeaponId then
                if Weapon.HyperCardLevel >= NeedHyperLevel then
                    bFinishCond = true
                    break
                end
            end
        end
        return bFinishCond
    end
    return false
end

function ConditionUtils:JudgeInteractTriggerFinished(Params)
    if GWorld:IsSkynetServer() or not IsDedicatedServer(GWorld.GameInstance) then
        local InteractTriggerId = Params
        if self.InteractTriggerRewardRecords and self.InteractTriggerRewardRecords[InteractTriggerId] then
            return true
        end
        return false
    end
    return false
end

function ConditionUtils:JudgeHaveGotSoloTreasureScore(Params)
    if GWorld:IsSkynetServer() or not IsDedicatedServer(GWorld.GameInstance) then
        local EventId, Score = Params[1], Params[2]
        local TreasureHunt = self.TreasureHunts[EventId]
        if not TreasureHunt then
            return false
        end
        return TreasureHunt.TotalScore >= Score
    end
    return false
end
------------------------------------------------------------------------------------------------------------------------

function ConditionUtils:PackParams(ConditionName, Params)
    local ResultStr = ConditionName..","

    if type(Params) == "table" then
        for i=1, #Params do
            if i == #Params then
                ResultStr = ResultStr..tostring(Params[i])
            else
                ResultStr = ResultStr..tostring(Params[i])..","
            end
        end
    else
        ResultStr = ResultStr..tostring(Params)
    end

    return ResultStr
end

function ConditionUtils:UnpackParams(ParamStr)
    local t = CommonUtils.Split(ParamStr, ",")
    local Params = {}
    local t_len = #t
    if t_len == 2 then
        Params = t[2]
    else
        for i=2, #t do
            Params[i-1] = t[i]
        end
    end

    return t[1], Params
end

------------------------------------------------------------------------------------------------------------------------

-- 获取条件Id对应的条件内容
function ConditionUtils:GetConditionContent(ConditionId)
    local Condition = DataMgr.Condition[ConditionId]
    if not Condition then
        return {}
    end

    return Condition.ConditionMap
end

-- 获取条件Id对应的条件逻辑
function ConditionUtils:GetConditionLogic(ConditionId)
    local Condition = DataMgr.Condition[ConditionId]
    if not Condition then
        return nil
    end

    return Condition.ConditionLogic
end

------------------------------------------------------------------------------------------------------------------------

function ConditionUtils:CallDedicatedServerCondition(ConditionName, Params, ConditionCheckId)
    if not ConditionCheckId then
        return
    end
    self:CallClientMethod("CheckDedicatedServerCondition", ConditionCheckId, ConditionUtils:PackParams(ConditionName, Params))
end

function ConditionUtils:CallClientCondition(ConditionName, Params, ConditionCheckId)
    if not ConditionCheckId then
        return
    end
    self:CallClientMethod("CheckClientCondition", ConditionCheckId, ConditionUtils:PackParams(ConditionName, Params))
end

return ConditionUtils