---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jinyi.li.
--- DateTime: 2026/2/9 19:11
---

local Component = {}

function Component:SetGameModeLevel(Level)
    ServerPrint("SetGameModeLevel", Level)
    local GameMode = GWorld.GameInstance:GetCurrentGameMode()
    GameMode:SetGameModeLevel(Level)
end

return Component