---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lijinyi.
--- DateTime: 2023/9/25 17:06
---

-- @SnowMoon
-- 作为DS的条件触发器，在这里监听DS场景中的条件，当满足条件后回调逻辑服进行完整条件判断，最终通知客户端
-- PS：单机时也可以通过这个方式走触发器
-- PS*: 纯客户端条件不可通过这个方式走触发器，纯客户端条件在条件满足后客户端主动CheckCondition即可

local Component = {}

function Component:TriggerCondition(ConditionType, ...)
    local info = DataMgr.Condition2Id[ConditionType]
    assert(info, "Unknown ConditionType: "..ConditionType)

    local Params = {...}
    local ConditionIds = info
    local ConditionIdsFunc = self["Get"..ConditionType.."Ids"]
    if ConditionIdsFunc then
        ConditionIds = ConditionIdsFunc(self, info, ...)
    else
        for i=1, #Params do
            local p = Params[i]
            ConditionIds = ConditionIds[p]
            if ConditionIds == nil then
                return
            end
        end
    end

    if type(ConditionIds) ~= "table" then
        return
    end

    local func = self["TriggerCondition"..ConditionType]
    for i=1, #ConditionIds do
        local ConditionId = ConditionIds[i]
        if func then
            func(self, ConditionId)
        else
            print(_G.LogTag, "TriggerCondition", ConditionType, ConditionId)
            self:ServerTriggerCheckCondition(ConditionId)
        end
    end
end

function Component:ServerTriggerCheckCondition(ConditionId)
    if IsStandAlone(self) or IsClient(self) then
        local Avatar = GWorld:GetAvatar()
        if Avatar then
            Avatar:ClientTriggerCheckCondition(ConditionId)
        end
    else
        if GWorld.bDebugServer then
            return
        end

        local DSEntity = GWorld:GetDSEntity()
        if DSEntity then
            DSEntity:TriggerCondition(ConditionId)
        end
    end
end

------------------------------------------- 自定义Trigger触发器 ---------------------------------------------------------

-- e.g. 用于自定义条件触发器的实际行为，如果没有自定义触发器则会默认直接触发条件，参考下例
--function Component:TriggerConditionXXX(ConditionId)
--    print(_G.LogTag, "TriggerConditionXXX", ConditionId)
--    NotifyGameModeTriggerCondition(ConditionId)
--    NotifyClientTriggerCondition(ConditionId)
--    if not GameMode.AA then
--        return
--    end
--
--    self:ServerTriggerCheckCondition(ConditionId)
--end

------------------------------------------------------------------------------------------------------------------------
------------------------------------------- ConditionIds解析 -----------------------------------------------------------

------------------------------------------------------------------------------------------------------------------------

return Component