---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jinyi.li.
--- DateTime: 2025/6/25 14:27
---

--- @SnowMoon 作为单机逻辑服和联机DS奖励规则和生成奖励的组件
--- 这个模块不以Component的方式注册，而是以require的方式引用，作为全局单例使用
--- 这个模块不依赖于任何其他的模块存在（包括Avatar和GameMode），具有功能独立性

local GameModeRewardParseComponent = {}

function GameModeRewardParseComponent:ParseReward(UnitId, RewardReason, ExtraInfo)
    local func = self["ParseReward_"..RewardReason]
    assert(func, string.format("ParseReward cannot find function for RewardReason: %s", RewardReason))

    return func(self, UnitId, ExtraInfo)
end

function GameModeRewardParseComponent:ParseReward_Chest(UnitId, ExtraInfo)
    return self:MechanismReward(UnitId, ExtraInfo)
end

function GameModeRewardParseComponent:MechanismReward(UnitId, ExtraInfo)
    local MechanismInfo = DataMgr.Mechanism[UnitId]
    if not MechanismInfo then
        return false
    end

    local RewardId = MechanismInfo.RewardId
    local UnitParams = MechanismInfo.UnitParams
    if ExtraInfo.bRare and UnitParams then
        local RareRewardId = UnitParams.RareRewardId
        if RareRewardId then
            RewardId = RareRewardId
        end
    end

    return true, {RewardId}
end

function GameModeRewardParseComponent:ParseReward_BreakableItem(UnitId, ExtraInfo)
    return self:MechanismReward(UnitId, ExtraInfo)
end

function GameModeRewardParseComponent:ParseReward_MonsterDead(UnitId)
    local MonsterInfo = DataMgr.Monster[UnitId]
    if not MonsterInfo then
        return false
    end

    local RewardId = MonsterInfo.RewardId
    return true, {RewardId}
end

function GameModeRewardParseComponent:ParseReward_PickUp(UnitId)
    local DropInfo = DataMgr.Drop[UnitId]
    if not DropInfo then
        return false
    end

    local UseEffect = DropInfo.UseEffectType
    if not UseEffect then
        return false
    end

    return true, {}
end

function GameModeRewardParseComponent:ParseReward_Repeated(UnitId, ExtraInfo)
    return self:MechanismReward(UnitId, ExtraInfo)
end

return GameModeRewardParseComponent