---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jinyi.li.
--- DateTime: 2024/10/21 16:46
---

local RewardSequenceFunc = {}

function RewardSequenceFunc.Init(RewardId)
    return {
        RewardId = RewardId,
        RewardIndex = 0,
        Rewards = {},
        RandomCount = 0,
    }
end

function RewardSequenceFunc.AddIndex(self, RewardId, Data, bCeiling)
    local Sequence = self.SequenceDict[RewardId]
    if not Sequence then
        Sequence = RewardSequenceFunc.Init(RewardId)
        RewardSequenceFunc.UpdateRewards(Sequence, self.Seed, Data, bCeiling)
    end

    local RewardLength = Sequence.Rewards.Length and Sequence.Rewards:Length() or #Sequence.Rewards
    if Sequence.RewardIndex >= RewardLength then
        RewardSequenceFunc.UpdateRewards(Sequence, self.Seed, Data, bCeiling)
        Sequence.RewardIndex = 1
    else
        Sequence.RewardIndex = Sequence.RewardIndex + 1
    end

    self.SequenceDict[RewardId] = Sequence
end

-- Seed是这个Sequence的固定值，RewardId是奖励参数，两者加和确定这个Sequence中这个Reward的随机数种子
-- 通过再加和随机次数控制每次随机的结果一致
function RewardSequenceFunc.Random(Sequence, Seed, min, max)
    math.randomseed(Seed + Sequence.RandomCount + Sequence.RewardId)
    Sequence.RandomCount = Sequence.RandomCount + 1
    return math.random(min, max)
end

function RewardSequenceFunc.Shuffle(Sequence, Seed, T)
    local Count = #T
    while Count > 1 do
        local n = RewardSequenceFunc.Random(Sequence, Seed, 1, Count - 1)
        if T[n] ~= nil then
            T[Count], T[n] = T[n], T[Count]
            Count = Count - 1
        end
    end
end

function RewardSequenceFunc.UpdateRewards(Sequence, Seed, Data, bCeiling)
    local RewardInfo = Data[Sequence.RewardId]
    local Result = {}

    if bCeiling then
        -- 截断序列模式下，只需要随机出指定奖励前的奖励内容即可
        for i=2, #RewardInfo.Param do
            local MaxCount = RewardInfo.Param[i]
            local n = RewardSequenceFunc.Random(Sequence, Seed, 0, MaxCount)
            for j=1, n do
                Result[#Result + 1] = i
            end
        end
        RewardSequenceFunc.Shuffle(Sequence, Seed, Result)
        Result[#Result + 1] = 1 -- 最后在末尾填充指定奖励
    else
        -- 完整序列模式下，排列所有选项然后打乱顺序即可
        for i=1, #RewardInfo.Param do
            local Param =RewardInfo.Param[i]
            for j=1, Param do
                Result[#Result + 1] = i
            end
        end

        RewardSequenceFunc.Shuffle(Sequence, Seed, Result)
    end

    Sequence.Rewards = Result
end

function RewardSequenceFunc.GetReward(self)
    return self.Rewards[self.RewardIndex]
end

return RewardSequenceFunc