---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lijinyi.
--- DateTime: 2023/12/11 18:33
---
local bson = require "bson"
local zlib = require "zlib"
local bOpenCompress = false
local SerializeUtils = {}

local function IsObjId(str)
    if #str == 14 and string.byte(string.sub(str,1,1)) == 0 then
        return true
    end

    return false
end

function SerializeUtils:ToStringEx(value)
    local ValueType = type(value)
    if ValueType=='table' then
        return self:TableToStr(value)
    elseif ValueType=='string' then
        if IsObjId(value) then
            return self:SerializeObjId(value)
        else
            local escaped_value = value:gsub("'", "\\'")
            return "\'"..escaped_value.."\'"
        end
    elseif ValueType == "number" or ValueType == "boolean" then
        return tostring(value)
    elseif ValueType == "userdata" then
        return self:SerializeUserdata(value)
    end
end

function SerializeUtils:IsArrayTable(t)
    if not t or type(t) ~= "table" then
        return false
    end

    local max_index = 0
    local count = 0

    -- 单次遍历，同时检查
    for key, _ in pairs(t) do
        if type(key) == "number" then
            -- 检查是否为整数
            if key ~= math.floor(key) then
                return false
            end

            -- 检查是否为正数
            if key <= 0 then
                return false
            end

            -- 更新最大索引和计数
            if key > max_index then
                max_index = key
            end
            count = count + 1
        else
            -- 有非数字键，肯定不是纯数组
            return false
        end
    end

    -- 空表是有效的数组
    if count == 0 then
        return true
    end

    -- 检查连续性：最大索引应该等于元素数量
    return max_index == count
end

function SerializeUtils:TableToStr(t)
    if t == nil then return "" end
    local retstr= "{"

    if SerializeUtils:IsArrayTable(t) then
        for i=1, #t do
            local signal = ","
            if i==1 then
                signal = ""
            end

            retstr = retstr..signal..self:ToStringEx(t[i])
        end
    else
        local signal = ""
        for key,value in pairs(t) do
            if type(key)=='number' or type(key) == 'string' then
                retstr = retstr..signal.."["..self:ToStringEx(key).."]="..self:ToStringEx(value)
            else
                if type(key)=='userdata' then
                    retstr = retstr..signal.."*s"..self:TableToStr(getmetatable(key)).."*e".."="..self:ToStringEx(value)
                else
                    retstr = retstr..signal..key..":"..self:ToStringEx(value)
                end
            end

            signal = ","
        end
    end

    retstr = retstr.."}"
    return retstr
end

function SerializeUtils:StrToTable(str)
    print(_G.LogTag, str)
    if str == nil or type(str) ~= "string" or str == "" then
        return {}
    end

    return load("return " .. str)()
end

local function DefaultSerializeUserdata(value)
    return "\""..tostring(value).."\""
end

function SerializeUtils:SerializeUserdata(value)
    local result = {}

    if not value.IsSerializable or not value:IsSerializable() then
        print(_G.LogTag, "SerializeUtils:SerializeUserdata Failed for bSerialized is not exist.")
        return DefaultSerializeUserdata(value)
    end

    local str = CommonUtils.Split(tostring(value), ":")
    result.SerializeName = str[1]
    local ValueString = value:ToString()
    ValueString = string.gsub(ValueString, "\r\n", "") -- 去除回车
    ValueString = string.gsub(ValueString, "%s+", "") -- 去除空格
    result.ValueString = ValueString
    return self:TableToStr(result)
end

function SerializeUtils:SerializeObjId(value)
    local result = {}
    local ret = ""
    for index=3,#value do
        ret = ret..string.format("%02X",string.byte(string.sub(value,index,index)))
    end
    result.ObjIdStr = ret
    return self:TableToStr(result)
end

function SerializeUtils:TransformTable(Table)
    if Table.SerializeName then
        -- 是userdata
        local userdata = load("return " .. Table.SerializeName .. "()")()
        userdata:InitFromString(Table.ValueString)
        return userdata
    elseif Table.ObjIdStr then
        -- 是objid
        return bson.objectid(Table.ObjIdStr)
    end

    for key, value in pairs(Table) do
        if type(value) == "table" then
            Table[key] = self:TransformTable(value)
        end
    end

    return Table
end

function SerializeUtils:Serialize(Table, threshold)
    threshold = threshold or 1024

    local Serialized = self:TableToStr(Table)

    if bOpenCompress and #Serialized > threshold then
        return self:CompressString(Serialized)
    else
        return Serialized
    end
end

function SerializeUtils:UnSerialize(TableStr)
    if not TableStr or TableStr == "" then
        return {}
    end

    TableStr = self:DecompressString(TableStr)
    return self:TransformTable(self:StrToTable(TableStr))
end

function SerializeUtils:CompressString(str)
    if not str or str == "" then
        return str
    end

    -- 对于小字符串，压缩可能反而更大，设置阈值
    if #str < 100 then
        return str
    end

    local ok, compressed = pcall(function()
        local deflate = zlib.deflate()
        return deflate(str, "finish")
    end)

    if not ok or not compressed then
        print(_G.LogTag, "Compression failed: " .. tostring(compressed))
        return str
    end

    -- 如果压缩后数据反而更大，返回原数据
    if #compressed >= #str then
        return str
    end

    -- 添加压缩标记和版本信息
    local header = string.pack(">B", 0x5A)  -- 0x5A = 'Z'
    return header .. compressed  -- 使用gzip头标识
end

function SerializeUtils:DecompressString(Str)
    if not Str or Str == "" then
        return Str
    end

    -- 检查是否是压缩数据（是否有gzip头）
    if #Str <= 1 or Str:byte(1) ~= 0x5A then
        return Str  -- 不是压缩数据，直接返回
    end

    -- 去除gzip头
    -- 解析头部
    local compressed_data = Str:sub(2)

    local ok, decompressed = pcall(function()
        local inflate = zlib.inflate()
        return inflate(compressed_data, "finish")
    end)

    if not ok or not decompressed then
        error("Decompression failed: " .. tostring(decompressed))
    end

    return decompressed
end

return SerializeUtils