---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jinyi.li.
--- DateTime: 2026/3/5 17:18
---

local Player = require "BluePrints.DungeonObject.Entity.Player"
local PlayerManager = DungeonClass.Class()

function PlayerManager:BeginPlay()
    self:InitReplicatedProperties(self, "Players", {})
end

function PlayerManager:AddPlayer(AvatarEid)
    self.Players[AvatarEid] = Player(self)
    self.Players = self.Players -- 触发属性同步
end

function PlayerManager:RemovePlayer(AvatarEid)
    if not self.Players[AvatarEid] then
        return
    end

    self.Players[AvatarEid] = nil
    self.Players = self.Players -- 触发属性同步
end


return PlayerManager