---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lijinyi.
--- DateTime: 2023/6/1 10:55
---


require "UnLua"

---@type BP_EMPhantomState_C
local BP_EMPhantomState_C = Class({
    "BluePrints.Common.TimerMgr",
})

function BP_EMPhantomState_C:Initialize(Initializer)
end

function BP_EMPhantomState_C:OnRep_TeamRecoveryState(PrevRecoveryState)
    DebugPrint("LHQ_PhantomState OnRep_TeamRecoveryState, NewState:" .. self.TeamRecoveryState, "Eid:", self.Eid, "PrevRecoveryState: ", PrevRecoveryState)
    EventManager:FireEvent(EventID.OnTeamRecoveryStateChange, self.Eid, self.TeamRecoveryState, PrevRecoveryState)
    
    -- if self.TeamRecoveryState == UE4.ETeamRecoveryState.Alive then
        -- EventManager:FireEvent(EventID.ChangePhantomGuideState, "Alive", self.Eid)
        -- EventManager:FireEvent(EventID.ChangePhantomMiniMapIcon, "Alive", self.Eid)
    -- elseif self.TeamRecoveryState == UE4.ETeamRecoveryState.Dying then
        -- EventManager:FireEvent(EventID.ChangePhantomGuideState, "Dead", self.Eid)
        -- EventManager:FireEvent(EventID.ChangePhantomMiniMapIcon, "Dead", self.Eid)
    -- elseif self.TeamRecoveryState == UE4.ETeamRecoveryState.IsWaitingRecover then
        -- EventManager:FireEvent(EventID.ChangePhantomGuideState, "Recovering", self.Eid)
    -- end
end

function BP_EMPhantomState_C:OnRep_RecoveryValue()
    DebugPrint("PhantomState OnRep_RecoveryValue", self.RecoveryValue)
    EventManager:FireEvent(EventID.OnRepPhantomRecoveryValue, self.RecoveryValue)
end

function BP_EMPhantomState_C:OnRep_RecoverySpeed()

    -- 目前应该暂时只有人质在用，如果要扩展到所有魅影之后再移动这个判断
    if not self.bIsHostage then
        return
    end
    DebugPrint("PhantomState OnRep_RecoverySpeed", self.RecoverySpeed)
    if self.TeamRecoveryState == UE4.ETeamRecoveryState.IsWaitingRecover and self.RecoverySpeed > 0 then
        if self.IsRecovering then
            return
        end
        self.IsRecovering = true
        self:OnEnterRecoveringState()
    else
        if not self.IsRecovering then
            return
        end
        self.IsRecovering = false
        self:OnExitRecoveringState()
    end
end

function BP_EMPhantomState_C:OnRep_DyingDuration()
    DebugPrint("PhantomState OnRep_DyingDuration", self.DyingDuration)
    EventManager:FireEvent(EventID.OnRepPhantomDyingDuration, self.DyingDuration)
end

function BP_EMPhantomState_C:OnRep_OwnerEid()
    EventManager:FireEvent(EventID.OnRepOwnerEidPhantomState, self.Eid, self.OwnerEid)
end


function BP_EMPhantomState_C:OnEnterRecoveringState()
    self:TriggerRescueTimerFloatVisibility(true)
end

function BP_EMPhantomState_C:OnExitRecoveringState()
    self:TriggerRescueTimerFloatVisibility(false)
end

-- todo 还可以全走fireevent 先这样吧
function BP_EMPhantomState_C:TriggerRescueTimerFloatVisibility(IsShow)
    if not self.bIsHostage then
        return
    end

    local RescueTimeFloat = UIManager(self):GetUIObj("DungeonRescueTimeFloat")
    local CaptureFloat = UIManager(self):GetUIObj("DungeonCaptureFloat")
    if RescueTimeFloat == nil then
        return
    end
    RescueTimeFloat:OnHostageRecoverState(IsShow)
    if IsShow then --true开始复活 false结束复活
        CaptureFloat.Panel_time:SetVisibility(UE4.ESlateVisibility.Collapsed)
    else
        CaptureFloat.Panel_time:SetVisibility(UE4.ESlateVisibility.SelfHitTestInvisible)
    end
end

return BP_EMPhantomState_C
