---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jinyi.li.
--- DateTime: 2025/12/17 14:08
---
local AutoChessModel = require "BluePrints.UI.AutoChess.AutoChessDataModel"

local Component = {}

function Component:OnLoginSuccess()
    AutoChessModel:InitModel()
end


function Component:RefreshRandomMission(Callback)
    local cb = function (Ret)
        DebugPrint("RefreshRandomMission Result", Ret)
        if Callback then
            Callback(Ret)
        end
    end

    self:CallServer("RefreshRandomMission", cb)
end

function Component:AutoChessAddEquip(Callback, MonsterId, EquipId, ReplaceEquipIndex)
    DebugPrint("AutoChessAddEquip", MonsterId, EquipId, ReplaceEquipIndex)
    assert(MonsterId)
    assert(EquipId)
    ReplaceEquipIndex = ReplaceEquipIndex or 0
    local cb = function (Ret)
        if Callback then
            Callback(Ret)
        end

        EventManager:FireEvent(EventID.OnAutoChessEquipChange, MonsterId, EquipId, ReplaceEquipIndex)
    end

    self:CallServer("AutoChessAddEquip", cb, MonsterId, EquipId, ReplaceEquipIndex)
end

function Component:AutoChessRemoveEquip(Callback, MonsterId, EquipIdx)
    DebugPrint("AutoChessRemoveEquip", MonsterId, EquipIdx)
    assert(MonsterId)
    assert(EquipIdx)
    local cb = function (Ret)
        if Callback then
            Callback(Ret)
        end

        EventManager:FireEvent(EventID.OnAutoChessEquipChange, MonsterId, EquipId)
    end

    self:CallServer("AutoChessRemoveEquip", cb, MonsterId, EquipIdx)
end

function Component:AutoChessAddSquad(Callback, Squad, SquadIndex)
    DebugPrint("AutoChessAddSquad", SquadIndex)
    assert(Squad)
    assert(SquadIndex)

    local cb = function (Ret)
        if ErrorCode:Check(Ret) then
            if Callback then
            Callback(Ret)
            end
        end
    end

    self:CallServer("AutoChessAddSquad", cb, Squad, SquadIndex)
end

function Component:AutoChessRemoveSquad(Callback, SquadId)
    DebugPrint("AutoChessRemoveSquad", SquadId)
    assert(SquadId)
    local cb = function (Ret)
        if ErrorCode:Check(Ret) then
            if Callback then
                Callback(Ret)
            end
        end
    end

    self:CallServer("AutoChessRemoveSquad", cb, SquadId)
end

function Component:AutoChessCombatStart(Callback, Squad)
    assert(Squad)
    local cb = function (Ret)
        if Callback then
            Callback(Ret)
        end
    end

    self:CallServer("AutoChessCombatStart", cb, Squad)
end

-- 通知客户端新解锁的内容
function Component:AutoChessUnlock(UnlockType, UnlockId)
    AutoChessModel:InitReddotTree()
    if UnlockType == "Card" then
        ReddotManager.IncreaseLeafNodeCount("AutoChessMonster", 1, {Id = UnlockId})
    elseif UnlockType == "Equip" then
        ReddotManager.IncreaseLeafNodeCount("AutoChessEquip", 1, {Id = UnlockId})
    end
end

function Component:ttac()
    self:AutoChessAddSquad()
end

return Component