---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lijinyi.
--- DateTime: 2023/3/13 10:23
---
-- 这个组件用于与DS集群通信，进出任何在线的DS场景
local Component = {}

-- 连接并进入一个正在使用的DS
function Component:ConnectAndEnterDS(DSIp, DSPort, DungeonId, CurrentRewards)
    self.logger.info("DSMgr ConnectAndEnterDS")
    self.AvatarBattleInfo = nil
    self.CacheDSInfo = {
        DSIp = DSIp,
        DSPort = DSPort,
        DungeonId = DungeonId,
    }

    if CurrentRewards then
        self:CacheDungeonRewards(CurrentRewards)
    end

    self:ConnectDSServer(DSIp, DSPort, DungeonId)
    if GWorld.IsDev then
        self:GetDSLogPath()
    end
end

function Component:ConnectDSServer(DSIp, DSPort, DungeonId)
    -- 连接DS
    self.logger.debug("ConnectDSServer", DSIp, DSPort, type(DSIp), type(DSPort))
    self.logger.debug("other info", self.Account, CommonUtils.ObjId2Str(self.Eid), DungeonId)
    WorldTravelSubsystem():ChangeSceneConnectDedicatedServer(DungeonId, DSIp, DSPort, self.Account, CommonUtils.ObjId2Str(self.Eid))
end

function Component:QuickReconnectDS()
    print(_G.LogTag, "QuickReconnectDS")
    if not self.CacheDSInfo then
        return false
    end

    self:ConnectDSServer(self.CacheDSInfo.DSIp, self.CacheDSInfo.DSPort, self.CacheDSInfo.DungeonId)
    return true
end

function Component:OnClientWasKicked(Reason)
    self:CallServerMethod("OnClientWasKicked", Reason)
end

function Component:OnMatchPrepareToBattle()
    print(_G.LogTag, "OnMatchPrepareToBattle")
    
    EventManager:FireEvent(EventID.OnMatchPrepareToBattle)
end

-- 退出DS
function Component:ExitDS()
    self.logger.info("DSMgr ExitDS")
    local Avatar = GWorld:GetAvatar()
	Avatar:ExitDungeon()
end

function Component:KickPlayer(AvatarEid)
    self:CallServerMethod("KickPlayer", AvatarEid)
end

--function Component:OnNotifyClientToLoad()
--    GWorld.GameInstance:ShowLoadingUI(UIConst.COMMONCHANGESCENE)
--end
--
--function Component:OnNotifyClientToUnload()
--    self.logger.info("OnNotifyClientToUnload")
--    if GWorld.GameInstance:GetLoadingUI() then
--        GWorld.GameInstance:CloseLoadingUI()
--    end
--end

function Component:GetDSLogPath()
    local function cb(ret, DSLogPath)
        print(_G.LogTag, "DSLogPath", DSLogPath)
    end
    self:CallServer("DoGmCommand", cb, "GMGetDSLogPath")
end

-- 逻辑服通知与DS断开连接
function Component:OnDisconnectDS()
    DebugPrint("OnDisconnectDS")

    if GWorld.GameInstance:IsInTempScene() then
        -- 在结算的临时场景中收到断开连接，正常情况，直接return
        return
    end

    -- 否则，直接退出副本
    local Avatar = GWorld:GetAvatar()
	Avatar:ExitDungeon()
    GWorld.GameInstance.LogicServerCallbackInfo = nil       -- 要清掉逻辑服回调缓存，否则下次结算会有问题
    GWorld.GameInstance.IsInSettlementScene = nil
    GWorld.GameInstance.IsDSOnDungeonFinish = nil
    DebugPrint("TryDungeonSettlement: OnDisconnectDS ClearInfo")
end

return Component