---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lijinyi.
--- DateTime: 2023/4/6 17:11
---

local Component = {}
local GachaController = require "BluePrints.UI.WBP.Gacha.GachaController"
local GachaModel = require "BluePrints.UI.WBP.Gacha.GachaModel"
local EMCache = require "EMCache.EMCache"

function Component:EnterWorld()
	GachaController:Init()
end

function Component:LeaveWorld()
	GachaController:Destory()
end

function Component:DrawGacha(GachaId, Counts)
    self.logger.info("Avatar DrawGacha", GachaId, Counts)
    local function callback(ret, Data, RebateData)
        self.logger.info("DrawGacha Result callback", ret)
        EventManager:FireEvent(EventID.OnDrawGacha,ret,Data)
    end
    self:CallServer("ClientDrawGacha", callback, GachaId, Counts)
end

-- 非上线更新卡池信息的时机，触发了卡池更新，即定时开启/关闭卡池的事件回调
function Component:OnGachaPoolUpdate(GachaId, GachaType)
    EventManager:FireEvent(EventID.OnGachaPoolUpdate)
    GachaModel:CheckReddot()
    GachaModel:CheckNew()
end

-------------------------- 历史记录相关 ---------------------------

--function Component:GetGachaRecord(StartIndex, Limit)
--    self.logger.info("GetGachaRecord", StartIndex, Limit)
--    StartIndex = StartIndex or 0
--    local RecordLength = self:GetGachaRecordLength()
--    Limit = Limit or RecordLength
--
--    if StartIndex + Limit > RecordLength then
--        Limit = RecordLength - StartIndex
--    end
--
--    local Result = {}
--    local ReadPtr = self.GachaRecordParams.Rear - StartIndex
--    print(_G.LogTag, self.GachaRecordParams.Front, self.GachaRecordParams.Rear)
--    for i=1, Limit do
--        table.insert(Result, self.GachaRecordQueue[(ReadPtr - i + self.GachaRecordParams.MaxLength + 1) % (self.GachaRecordParams.MaxLength + 1)]:Dump())
--    end
--
--    return Result
--end
--
--function Component:GetGachaRecordLength()
--    return (self.GachaRecordParams.Rear - self.GachaRecordParams.Front + self.GachaRecordParams.MaxLength + 1) % (self.GachaRecordParams.MaxLength + 1)
--end

function Component:OpenGachaRecord(Callback)
    self.logger.info("OpenGachaRecord")
    local cb = function (ret, Records)
        if not ErrorCode:Check(ret) then
            return
        end

        -- PrintTable(Records, 3)

        if Callback then
            Callback(Records)
        end
    end

    self:CallServer("OpenGachaRecord", cb)
end

--序章抽卡
function Component:PrologueGacha(Obj,Func)
	self.logger.debug("PrologueGacha Start",Obj,Func)
	local function callback(Ret,IsFinish,RewardReturn)
		self.logger.debug("PrologueGacha Result",Ret,IsFinish,RewardReturn)
        if Obj and Func then
            Func(Obj)
        end
        -- if ErrorCode:Check(Ret) and (not IsFinish)then
        --     --获得/已有碎片
        --     local Config = DataMgr.InitConfig[1]
        --     local AlternativeCharId = Config.AlternativeCharId
        --     UIUtils.OpenSystem(CommonConst.ArmoryEnterId,false, {
        --         OnCloseDelegate = {
        --             Obj,Func
        --         },
        --         SelectedTargetId = AlternativeCharId,
        --         EscapeArmoryCharID = AlternativeCharId,
        --         bNoEndCamera = true,
        --     })
        -- else
        --     if Obj and Func then
        --         Func(Obj)
        --     end
        -- end
	end
	self:CallServer("PrologueGacha",callback)
end

--每日刷新抽卡卡池Spine动画缓存
function Component:OnDailyRefreshGachaCache()
    local CacheData = EMCache:Get("GachaSystem")
    self.logger.debug("----jzn---OnDailyRefreshGachaCache----",CacheData)
    if CacheData then
        for key,value in pairs(CacheData) do
            CacheData[key] = false
        end
        EMCache:Set("GachaSystem",CacheData)
    end
end

--每日刷新限时抽卡券到期泡泡的播放
function Component:OnDailyRefreshGachaBubble()
	local Cache = EMCache:Get("GachaBubble")
    self.logger.debug("----jzn---OnDailyRefreshGachaBubble----",Cache)
    if Cache ~= nil then
        EMCache:Set("GachaBubble",false)
    end
end

function Component:SetGachaSelfSelect(Callback, GachaId, SelfSelect)
    self:CommonSetGachaSelfSelect(Callback, GachaId, "", SelfSelect)
end

function Component:SetSkinGachaSelfSelect(Callback, GachaId, SelfSelect)
    self:CommonSetGachaSelfSelect(Callback, GachaId, "Skin", SelfSelect)
end

function Component:DrawSkinGacha(GachaId, Counts)
    self.logger.info("Avatar DrawSkinGacha", GachaId, Counts)
    local function callback(ret, Data, RebateData)
        self.logger.info("DrawSkinGacha Result callback", ret)
        EventManager:FireEvent(EventID.OnDrawGacha,ret,Data, RebateData)
    end
    self:CallServer("ClientDrawSkinGacha", callback, GachaId, Counts)
end

function Component:CommonSetGachaSelfSelect(Callback, GachaId, Type, SelfSelect)
    self.logger.info("SetGachaSelfSelect", GachaId, Type, SelfSelect)
    local cb = function (ret)
        if not ErrorCode:Check(ret) then
            return
        end

        if Callback then
            Callback(ret)
        end
    end

    self:CallServer("SetGachaSelfSelect", cb, GachaId, Type, SelfSelect)
end

function Component:GetGachaCumulativeReward(Callback, GachaId, Stage)
    self.logger.info("GetGachaCumulativeReward", Stage)
    local cb = function (ret, Reward)
        -- ErrorCode:Check(ret)

        if Callback then
            Callback(ret, Reward)
        end
    end

    self:CallServer("GetGachaCumulativeReward", cb, GachaId, Stage)
end

return Component