---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lijinyi.
--- DateTime: 2023/8/2 18:28
---

----------------- BossBattle HardBoss Nightmare梦魇残声 --------------
local Component = {}
local EMCache = require "EMCache.EMCache"

function Component:EnterWorld()
    EventManager:AddEvent(EventID.ConditionComplete, self, self.UpdateHardBossReddot)
end

function Component:LeaveWorld()
	EventManager:RemoveEvent(EventID.ConditionComplete, self)
end

function Component:UpdateHardBossReddot(ConditionId)
    if not ReddotManager.GetTreeNode("HardBossItem") then
        ReddotManager.AddNode("HardBossItem")
    end
    if not ReddotManager.GetTreeNode("HardBossMain") then
        ReddotManager.AddNode("HardBossMain")
    end
    local HardbossItemCacheDetail = ReddotManager.GetLeafNodeCacheDetail("HardBossItem")
    local HardbossNode = ReddotManager.GetTreeNode("HardBossMain")
    for _,data in pairs(DataMgr.HardBossMain) do
        if data.UnlockCondition == ConditionId then
            if not HardbossItemCacheDetail[data.HardBossId] then
                HardbossItemCacheDetail[data.HardBossId] = 1
			    ReddotManager.IncreaseLeafNodeCount("HardBossItem")
                if HardbossNode and HardbossNode.Count == 0 then
                    ReddotManager.IncreaseLeafNodeCount("HardBossMain")
                end
            end
        end
    end
end

function Component:EnterHardBoss(HardBossId, DifficultyId, OtherCallback)
    print(_G.LogTag, "Avatar EnterHardBoss", HardBossId, DifficultyId)
    assert(HardBossId)
    assert(DifficultyId)
    local Callback = function (Ret)
        print(_G.LogTag, "EnterHardBoss Ret", Ret)
        ErrorCode:Check(Ret)
        if OtherCallback then
            OtherCallback(Ret)
        end
    end

    self:CallServer("EnterHardBoss", Callback, HardBossId, DifficultyId)
end

function Component:ReEnterHardBoss(OtherCallback)
    print(_G.LogTag, "ReEnterHardBoss")

    local Callback = function (Ret)
        print(_G.LogTag, "ReEnterHardBoss Ret", Ret)
        ErrorCode:Check(Ret)
        if OtherCallback then
            OtherCallback(Ret)
        end
    end
    self:CallServer("ReEnterHardBoss", Callback)
end

function Component:OnEnterHardBoss(HardBossId, DifficultyId)
    print(_G.LogTag, "OnEnterHardBoss", HardBossId, DifficultyId)
    -- 成功开始HardBoss
    -- todo 这个信息之后存到GameState上同步下来
    self.HardBossInfo = {
        HardBossId = HardBossId,
        DifficultyId = DifficultyId
    }

    -- todo 目前只考虑单机，联机以后有需求再说
    if IsStandAlone(GWorld.GameInstance) then
        local GameMode = UE.UGameplayStatics.GetGameMode(GWorld.GameInstance)
        GameMode.EMGameState:SetInHardBossValue(true)
        self:PreEnterHardBoss(GameMode)
        GameMode:InitHardBoss(HardBossId, DifficultyId)
    end
end

function Component:OnFinishHardBoss(CurrentHardBossInfo, IsWin, Rewards, CostTime)
    print(_G.LogTag, "Avatar OnFinishHardBoss", IsWin, CostTime)
    if IsStandAlone(GWorld.GameInstance) then
        local GameMode = UE.UGameplayStatics.GetGameMode(GWorld.GameInstance)
        if GameMode.QuitHardBoss then
            GameMode:QuitHardBoss()
            GWorld.GameInstance:PushLogicServerCallbackInfo(IsWin, CurrentHardBossInfo, Rewards, nil, CostTime)     -- IsWin放到第一个参数，方便后面单独拿
        end
    end
end

function Component:ExitHardBoss()
    print(_G.LogTag, "Avatar ExitHardBoss")
    local Callback = function ()
        print(_G.LogTag, "Avatar ExitHardBossCallback")
        local GameMode = UE.UGameplayStatics.GetGameMode(GWorld.GameInstance)
        GameMode.EMGameState:SetInHardBossValue(false)
        EventManager:FireEvent(EventID.OnExitDungeon)
        self.HardBossInfo = nil
        -- todo 目前只考虑单机
        if IsStandAlone(GWorld.GameInstance) then
            self:PreExitHardBoss()
            -- local GameMode = UE.UGameplayStatics.GetGameMode(GWorld.GameInstance)
            GameMode:EndHardBossCallBack()
        end
    end
    self:CallServer("ExitHardBoss", Callback)
end

function Component:PreEnterHardBoss(GameMode)
    local PlayerController = UE.UGameplayStatics.GetPlayerController(GWorld.GameInstance, 0)
    local Player = PlayerController:GetMyPawn()
    Player:RefreshRecoveryData("HardBoss")
    Player:SetRecoveryCount(0)
    -- Player:SetRecoveryMaxCount(math.floor(DataMgr.GlobalConstant.HardBossRebirtTime.ConstantValue))
    -- Player:SetPhantomRecoveryMaxCount(math.floor(DataMgr.GlobalConstant.HardBossPhantomRebirtTime.ConstantValue))
    
    -- local PlayerState = PlayerController.PlayerState
    -- PlayerState:SetRecoveryCount(0)
    -- PlayerState:SetRecoveryMaxCount(math.floor(DataMgr.GlobalConstant.HardBossRebirtTime.ConstantValue))
    -- PlayerState:SetPhantomRecoveryCount(0)
    -- PlayerState:SetPhantomRecoveryMaxCount(math.floor(DataMgr.GlobalConstant.HardBossPhantomRebirtTime.ConstantValue))

    GWorld.GameInstance:EnablePlayerCharacterInput() -- 再次挑战的时候需要先接收输入
    GameMode:PreInitPlayer(PlayerController, {Avatar = self})
end

function Component:PreExitHardBoss()
    local PlayerController = UE.UGameplayStatics.GetPlayerController(GWorld.GameInstance, 0)
    local Player = PlayerController:GetMyPawn()
    Player:RefreshRecoveryData("CommonRegion")
    Player:SetRecoveryCount(0)

    -- 开启玩家输入
    GWorld.GameInstance:EnablePlayerCharacterInput()
end

function Component:CheckHardBossCondition(DifficultyId)
    local UnlockCondition = DataMgr.HardBossDifficulty[DifficultyId].UnlockCondition
    if not UnlockCondition then
        return true
    end

    return self:CheckCondition(UnlockCondition)
end

function Component:CheckHardBossUnlockCondition(HardBossId)
    local UnlockCondition = DataMgr.HardBossMain[HardBossId].UnlockCondition
    if not UnlockCondition then
        return true
    end

    return self:CheckCondition(UnlockCondition)
end

return Component