---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jinyi.li.
--- DateTime: 2025/2/7 15:38
---

local Component = {}
local PersonInfoController = require "BluePrints.UI.WBP.PersonInfo.PersonInfoController"
function Component:EnterWorld()
	PersonInfoController:Init()
end

function Component:LeaveWorld()
	PersonInfoController:Destory()
end
function Component:AddCharDisplay(Callback, Id, AppearancePlan, ModPlan)
    if not Id or not AppearancePlan or not ModPlan then
        DebugPrint("AddCharDisplay Invalid arguments")
        return
    end

    local function cb(ret)
        if not ErrorCode:Check(ret) then
            return
        end

        if Callback then
            Callback(ret)
        end
    end

    self:CallServer("AddCharDisplay", cb, Id, AppearancePlan, ModPlan)
end

function Component:RemoveCharDisplay(Callback, Index)
    if not Index then
        DebugPrint("RemoveCharDisplay Invalid arguments")
        return
    end

    local function cb(ret)
        if not ErrorCode:Check(ret) then
            return
        end

        if Callback then
            Callback(ret)
        end
    end

    self:CallServer("RemoveCharDisplay", cb, Index)
end

function Component:UpdateCharDisplay(Callback, Index, Id, AppearancePlan, ModPlan)
    if not Index or not Id or not AppearancePlan or not ModPlan then
        DebugPrint("UpdateCharDisplay Invalid arguments")
        return
    end

    local function cb(ret)
        if not ErrorCode:Check(ret) then
            return
        end

        if Callback then
            Callback(ret)
        end
    end

    self:CallServer("UpdateCharDisplay", cb, Index, Id, AppearancePlan, ModPlan)
end

function Component:AddWeaponDisplay(Callback, Id, ModPlan)
    if not Id or not ModPlan then
        DebugPrint("AddWeaponDisplay Invalid arguments")
        return
    end

    local function cb(ret)
        if not ErrorCode:Check(ret) then
            return
        end

        if Callback then
            Callback(ret)
        end
    end

    self:CallServer("AddWeaponDisplay", cb, Id, ModPlan)
end

function Component:RemoveWeaponDisplay(Callback, Index)
    if not Index then
        DebugPrint("RemoveWeaponDisplay Invalid arguments")
        return
    end

    local function cb(ret)
        if not ErrorCode:Check(ret) then
            return
        end

        if Callback then
            Callback(ret)
        end
    end

    self:CallServer("RemoveWeaponDisplay", cb, Index)
end

function Component:UpdateWeaponDisplay(Callback, Index, Id, ModPlan)
    if not Index or not Id or not ModPlan then
        DebugPrint("UpdateWeaponDisplay Invalid arguments")
        return
    end

    local function cb(ret)
        if not ErrorCode:Check(ret) then
            return
        end

        if Callback then
            Callback(ret)
        end
    end
    self:CallServer("UpdateWeaponDisplay", cb, Index, Id, ModPlan)
end

--查看玩家个人主页
function Component:CheckOtherPlayerPersonallInfo(PlayerUuid,bForceUsedServerData)
    self.logger.debug("CheckOtherPlayerPersonallInfo Begin",PlayerUuid)
    if not PlayerUuid then
        DebugPrint("CheckOtherPlayerPersonallInfo Invalid arguments")
        return
    end
    local function cb(ret,PlayerInfo)
        self.logger.debug("CheckOtherPlayerPersonallInfo Callback",ret,PlayerUuid,PlayerInfo)
        if not ErrorCode:Check(ret) then
            return
        end
        PlayerInfo.Uuid=PlayerUuid
        PersonInfoController:OpenView(PlayerInfo,bForceUsedServerData)
        DebugPrint("yklua Had Received Server Open PersonInfo")
    end
    DebugPrint("yklua Had Call Open PersonInfo")
    self:CallServer("CheckOtherPlayerPersonallInfo", cb, PlayerUuid)
end

function Component:GetOtherPlayerPersonallInfo(PlayerUuid, CallbackInfo)
        if not PlayerUuid then 
        DebugPrint("GetOtherPlayerPersonallInfo Invalid arguments")
        return
    end
    local function cb(ret, PlayerInfo)
        if not ErrorCode:Check(ret) then
            return
        end
        
        PlayerInfo.Uuid = PlayerUuid
        CallbackInfo.Func(PlayerInfo)
    end
    
    self:CallServer("CheckOtherPlayerPersonallInfo", cb, PlayerUuid)
end

function Component:SetPersonalInfoVisible(VisibleType)
    self.logger.debug("SetPersonalInfoVisible", VisibleType)
    if not CommonUtils.HasValue(CommonConst.PersonalInfoVisibleType, VisibleType) then
        DebugPrint("SetPersonalInfoVisible Invalid arguments")
        return
    end

    self:CallServerMethod("SetPersonalInfoVisible", VisibleType)
end

--function Component:TTPI()
--    local CharId = self.CurrentChar
--    self:AddCharDisplay(nil, CharId, 1, 1)
--    DebugPrint("TTPI 1")
--    DebugPrintTable(self.PersonalInfo, 4)
--
--    self:UpdateCharDisplay(nil, 2, CharId, 1, 2)
--
--    self:UpdateCharDisplay(nil, 1, CharId, 1, 2)
--    DebugPrint("TTPI 2")
--    DebugPrintTable(self.PersonalInfo, 4)
--
--    self:RemoveCharDisplay(nil, 2)
--
--    self:RemoveCharDisplay(nil, 1)
--    DebugPrint("TTPI 3")
--    DebugPrintTable(self.PersonalInfo, 4)
--
--    local WeaponId = self.MeleeWeapon
--    self:AddWeaponDisplay(nil, WeaponId,  1)
--    DebugPrint("TTPI 4")
--    DebugPrintTable(self.PersonalInfo, 4)
--
--    self:UpdateWeaponDisplay(nil, 1, WeaponId, 2)
--    DebugPrint("TTPI 5")
--    DebugPrintTable(self.PersonalInfo, 4)
--
--    self:RemoveWeaponDisplay(nil, 1)
--    DebugPrint("TTPI 6")
--    DebugPrintTable(self.PersonalInfo, 4)
--end

return Component