---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jinyi.li.
--- DateTime: 2025/7/31 16:56
---
-- 结算场景联机相关

local Component = {}

-- 玩家列表进入结算场景联机
function Component:PlayerEnterSettlementOnlineArea(UidArray)
    DebugPrint("gmy@PlayerEnterSettlementOnlineArea", #UidArray, table.concat(UidArray, " "))
    self.SettlementUidArray = UidArray
end

-- 玩家退出结算场景联机
function Component:PlayerExitSettlementOnlineArea(Uid)
    DebugPrint("gmy@PlayerExitSettlementOnlineArea", Uid)
    if self.SettlementUidArray then
        for Index, TeammateUid in ipairs(self.SettlementUidArray) do
            if TeammateUid == Uid then
                table.remove(self.SettlementUidArray, Index)
                break
            end
        end
    end

    DebugPrint("gmy@PlayerExitSettlementOnlineArea End", Uid, self.SettlementUidArray and #self.SettlementUidArray or 0)
end

-- 自己离开结算场景
function Component:OnExitSettlement()
    DebugPrint("gmy@OnExitSettlement")
    self.SettlementUidArray = nil
end

-- 是否在多人结算场景
function Component:IsInMultiSettlement()
    DebugPrint("gmy@SettlementOnlineMgr Component:IsInMultiSettlement", self.SettlementUidArray,  self.SettlementUidArray and #self.SettlementUidArray or 0)
    return self.SettlementUidArray and #self.SettlementUidArray > 1
end

-- 玩家选择核桃
function Component:NotifySettlementAreaPlayerSelectWalnut(Uid, WalnutId)
    DebugPrint("NotifySettlementAreaPlayerSelectWalnut", Uid, WalnutId)
    EventManager:FireEvent(EventID.SettlementSelectWalnut, Uid, WalnutId)
end

-- 玩家选择门票
function Component:NotifySettlementAreaPlayerSelectTicket(Uid, TicketId)
    DebugPrint("NotifySettlementAreaPlayerSelectTicket", Uid, TicketId)
end

function Component:SettlementBattleEvent(EventName, ...)
    print(_G.LogTag, "SettlementBattleEvent", EventName)
    local func = self["SettlementBattleEvent_"..EventName]
    if func then
        func(self, ...)
    else
        print(_G.LogTag, "Unknown SettlementBattleEvent", EventName)
    end
end

-- 开始投票
function Component:SettlementBattleEvent_StartVote(DungeonId, bMatch)
    DebugPrint("gmy@Component:SettlementBattleEvent_StartVote", DungeonId)
    -- 尝试打开DungeonMatchTimingBar
    local Avatar = GWorld:GetAvatar()
    assert(Avatar, "Avatar is nil")

    local Panel = UIManager(self):GetUI("DungeonMatchTimingBar")
    if Panel and Panel.bClosing then
        UIManager(self):UnLoadUINew("DungeonMatchTimingBar")
    end

    UIManager(self):LoadUINew("DungeonMatchTimingBar",
            DungeonId, Const.DUNGEON_MATCH_BAR_STATE.TEAMMATE_CONFIRMING, bMatch)
    TeamController:RecvTeamOnVoteStart(DungeonId)
end

-- 成员投票
function Component:SettlementBattleEvent_OnMemberVote(Uid)
    DebugPrint(DebugTag, LXYTag, "TeamBattleEvent_OnMemberVote", Uid)
    TeamController:RecvTeamOnVoteAgreed(Uid)
end

-- 成员拒绝
function Component:SettlementBattleEvent_Refused(Uid)
    DebugPrint("gmy@SettlementOnlineMgr Component:SettlementBattleEvent_Refused", Uid, self.Uid)
    EventManager:FireEvent(EventID.TeamMatchOneRefused, Uid)
    TeamController:RecvTeamOnVoteRefused(Uid)

    if Uid ~= self.Uid then
        UIManager(self):ShowUITip("CommonToastMain", GText("TOAST_DUNGEON_CANCEL_REJECT"), 1.5)
    end
end

-- 开始选择核桃
function Component:SettlementBattleEvent_SelectWalnut(DungeonId)
    DebugPrint("gmy@SettlementOnlineMgr Component:SettlementBattleEvent_SelectWalnut", DungeonId)
    local WalnutChoiceUI = UIManager(self):LoadUINew("WalnutChoice", CommonConst.WalnutUser.Settlement, DungeonId, GWorld.GameInstance.CombatData.TempTeamInfo)
    local WalnutUtils = require "BluePrints.UI.WBP.Walnut.WalnutChoice.WalnutUtils"
    local WalnutId = WalnutUtils:GetWalnutCacheIdByDungeonId(DungeonId)
    WalnutChoiceUI:SelectWalnutById(WalnutId)
    EventManager:FireEvent(EventID.SelectWalnut)
end

-- 核桃选择完成
function Component:SettlementBattleEvent_WalnutSelectComplete()
    DebugPrint("gmy@SettlementOnlineMgr Component:SettlementBattleEvent_WalnutSelectComplete")
    EventManager:FireEvent(EventID.WalnutSelectComplete)
end

-- 开始选择门票
function Component:SettlementBattleEvent_SelectTicket(DungeonId)
    DebugPrint("gmy@SettlementOnlineMgr Component:SettlementBattleEvent_SelectTicket", DungeonId)
    EventManager:FireEvent(EventID.SelectTicket)
    local function GetValidAvatar()
        local Avatar = GWorld:GetAvatar()
        if not Avatar then
            assert(Avatar, "Avatar is nil")
            return nil
        end
        return Avatar
    end
    local function OnRightConfirm(_, PackageData)
        local Avatar = GetValidAvatar()
        if not Avatar then return end
        
        DebugPrint("gmy@SettlementOnlineMgr SelectTicket", DungeonId, PackageData.Content_1.TicketId)
        
        local Functor = function()
            local bIsSolo = #self.SettlementUidArray <= 1
            if bIsSolo then
                UIManager(self):LoadUINew("DungeonMatchTimingBar",
                        DungeonId, Const.DUNGEON_MATCH_BAR_STATE.WAITING_MATCHING_WITH_CANCEL, true)
            end
        end
        Avatar:SelectTicket(Functor, DungeonId, PackageData.Content_1.TicketId)
    end

    local function OnCancelVote()
        local Avatar = GetValidAvatar()
        if Avatar then
            Avatar:VoteStartBattle(false)
        end
    end

    local CurSelectedDungeonId = DungeonId
    -- 弹出通用门票确认弹窗
    local CommonDialog = UIManager(self):ShowCommonPopupUI(100123, {
        DungeonId = CurSelectedDungeonId,
        RightCallbackFunction = OnRightConfirm,
        LeftCallbackFunction = OnCancelVote,
        CloseBtnCallbackFunction = OnCancelVote,
        DontCloseWhenRightBtnClicked = true,
        AutoFocus = true,
        YesButtonText = GText("UI_CONFIRM_SELECTION")
    }, self)
end

-- 开始匹配
function Component:SettlementBattleEvent_Matching()
    DebugPrint("gmy@Component:SettlementBattleEvent_Matching")
    EventManager:FireEvent(EventID.TeamMatchStartMatching)
end

-- 正在申请战斗场景
function Component:SettlementBattleEvent_WaitEntering()
    DebugPrint("gmy@Component:SettlementBattleEvent_WaitEntering")
    EventManager:FireEvent(EventID.TeamMatchStartEntering)
    TeamController:RecvTeamOnVoteEntering()
end

-- DS Crash
function Component:SettlementBattleEvent_BattleFailed()
    DebugPrint(ErrorTag, "gmy@Component:SettlementBattleEvent_BattleFailed")
    if not self:IsInBigWorld() and not self:IsInSingleDungeon() and not self:IsInEnterSingleDungeon() then
        self:ExitDungeon()
    end
end


return Component