---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jinyi.li.
--- DateTime: 2026/2/28 16:41
---

-- 自热更，只需要更新代码，旧的副本不影响，下一个创建的副本会自动用新的代码
-- 禁止在代码中动态require

local ServerDungeon = DungeonClass.Class()
ServerDungeon.__Name__ = "ServerDungeon"
ServerDungeon.__Component__ = {
    -- 服务器专属写这里
    "BluePrints.DungeonObject.Server.ServerDungeonBase",

    -- Skynet专属
    "src.components.dungeon_components.ServerBaseDungeonObject",

    -- 共有的写这里
}


local GameModeDungeon = DungeonClass.Class()
GameModeDungeon.__Name__ = "GameModeDungeon"
GameModeDungeon.__Component__ = {
    -- 共有的写这里

    -- GameMode专属写这里
    "BluePrints.DungeonObject.GameMode.GameModeDungeonBase",
}

local ClientDungeon = DungeonClass.Class()
ClientDungeon.__Name__ = "ClientDungeon"
ClientDungeon.__Component__ = {
-- 客户端专属写这里
"BluePrints.DungeonObject.Client.ClientDungeonBase",

-- 共有的写这里
}


local DedicatedServerDungeon = DungeonClass.Class()
DedicatedServerDungeon.__Name__ = "DedicatedServerDungeon"
DedicatedServerDungeon.__Component__ = {
-- 共有的写这里

-- 服务器专属写这里
"BluePrints.DungeonObject.Server.ServerDungeonBase",

-- DedicatedDedicatedServer专属
"BluePrints.DungeonObject.DedicatedServer.DedicatedServerBase"
}

local Dungeon = {
    Server = ServerDungeon,
    DedicatedServer = DedicatedServerDungeon,
    GameMode = GameModeDungeon,
    Client = ClientDungeon,
}

local CreateFunction = function(Type)
    local Value = Dungeon[Type]
    DungeonClass.AssembleComponents(Value)
    return Value()
end

return CreateFunction