-- ---@WBP_Battle_Resurrection_Indicator_PC_C
-- --- Generated by EmmyLua(https://github.com/EmmyLua)
-- --- Created by JuleszzZ
-- --- DateTime: 2023/5/30 16:05
-- ---复活队友指引

-- require "UnLua"

-- local WBP_Battle_Resurrection_Indicator_PC_C = Class("BluePrints.UI.BP_UIState_C")

-- function WBP_Battle_Resurrection_Indicator_PC_C:Initialize(Initializer)
--     self.Super.Initialize(self)
--     self.Teammate = nil         --队友
--     self.CurMainPlayer =  nil   --当前主机


--     local RecoveryData = DataMgr.PlayerRotationRates
--     self.MaxDyingTime = RecoveryData["MaxDyingTime"].ParamentValue[1]
-- end

-- function WBP_Battle_Resurrection_Indicator_PC_C:InitRecoverIndicator(OwnerActor)
--     self:RemoveAllDispatcher()
--     self:AddDispatcher(EventID.CharDie,self,self.OnTeammateDie)
--     self:AddDispatcher(EventID.CharWaitingResurgence,self,self.OnTeammateCanRecovery)
--     self:AddDispatcher(EventID.CharRecover,self,self.OnTeammateRecovery)
--     self.Owner = OwnerActor

--     local Name = self:GetTargetRoleName(self.Owner)
--     if Name then 
--         if self.Owner:IsPlayer() then 
--             self.Text_PlayerName:SetText('Player'..Name)
--         else
--             self.Text_PlayerName:SetText(Name)
--         end
--     end

--     if self.Owner:IsPhantom() then 
--         self.Text_Time:SetText(GText('BATTLE_RECOVERY_WAITHELP'))
--     end
-- end

-- function WBP_Battle_Resurrection_Indicator_PC_C:OnTeammateDie(TargetEid)
--     self.Teammate = Battle(self):GetEntity(TargetEid)
--     if self.Owner.Eid ~= TargetEid and self.Owner:IsMainPlayer() then
--         if self.Teammate:IsPhantom() then
--             local Player = UE4.UGameplayStatics.GetPlayerCharacter(self, 0)
--         elseif self.Teammate:IsPlayer() then 
--             -- UIManager(self):ShowUITip_BattleCommonTop(UIConst.Tip_CommonTop, 'BATTLE_RECOVERY_TEAMMATEDEAD')
--             UIManager(self):ShowUITip(UIConst.Tip_CommonTop, string.format(GText("BATTLE_RECOVERY_TEAMMATEDEAD"), self.Teammate:GetNickName()))
--         end
--     end
-- end

-- function WBP_Battle_Resurrection_Indicator_PC_C:OnTeammateCanRecovery(TargetEid)
--     self.Teammate = Battle(self):GetEntity(TargetEid)
--     if self.Owner.Eid ~= TargetEid and self.Owner:IsMainPlayer() and self.Teammate.BillBoardComponent then
--         self.Teammate.BillBoardComponent:RefreshPlayerBillBoard(self.Owner)
--     end
-- end

-- function WBP_Battle_Resurrection_Indicator_PC_C:UpdateRecoverIndicator(PlayerActor)
--     --if not self.Owner:IsNearDying() then
--     --    return
--     --end
--     --self.BeginTime = UE4.UGameplayStatics.GetRealTimeSeconds(self)
--     self.BeginTime = self.Owner.EnterDyingTimestamp
--     self.CurMainPlayer = PlayerActor
--     self.RootWidget:SetRenderOpacity(1.0)
--     self.RootWidget:SetVisibility(UE4.ESlateVisibility.SelfHitTestInvisible)
--     self:AddTimer(0.1, self.RefreshTeammateRecoverIndicator, true, 0, "RefreshTeammateRecoverIndicator")

--     self.LastRemainTime = nil 
--     self.LastDistance = nil
-- end

-- function WBP_Battle_Resurrection_Indicator_PC_C:GetTargetRoleName(Target)
--     ---TODO 玩家名字暂时用角色名代替
--     if Target:IsPlayer() then 
--         local GameState = UE4.UGameplayStatics.GetGameState(self)
--         for key,value in pairs(GameState.PlayerArray) do
--             if value == Target.PlayerState then
--                 return key
--             end
--         end
--     elseif Target:IsPhantom() then 
--         local BattleCharName = GText(DataMgr.BattleChar[Target.CurrentRoleId].CharName)
--         return BattleCharName
--     end
-- end

-- function WBP_Battle_Resurrection_Indicator_PC_C:RefreshTeammateRecoverIndicator()
--     if not self.Owner:IsRealDead() and self.Owner:GetRecoveryPercent() < 0.00001 then
--         self.Switch_Progress:SetActiveWidgetIndex(0)
--         local PlayerLoc = self.CurMainPlayer:K2_GetActorLocation()
--         local OwnerLoc = self.Owner:K2_GetActorLocation()
--         local Distance = math.floor(UE4.UKismetMathLibrary.Vector_Distance(OwnerLoc,PlayerLoc)/Const.MaxRecoverValue)
        
--         if self.Owner:IsPlayer() and self.Owner.HaveDyingCountDown == true then 
--             self.NowTime = UE4.UGameplayStatics.GetRealTimeSeconds(self)
--             local Time = math.floor(math.max(self.MaxDyingTime - self.Owner:GetDyingDuration() , 0))
--             if not self.LastRemainTime or Time ~= self.LastRemainTime then 
--                 self.Text_Time:SetText(GText('BATTLE_RECOVERY_WAITHELP')..math.floor(Time)..'s')
--                 self.LastRemainTime = Time 
--             end
--         end

--         if not self.LastDistance or Distance ~= self.LastDistance then 
--             self.Text_Distance:SetText(math.floor(Distance)..'m')
--             self.LastDistance = Distance
--         end

--     else
--         self.Switch_Progress:SetActiveWidgetIndex(1)
--         local Percent = math.ceil(math.clamp(self.Owner:GetRecoveryPercent(), 0, Const.MaxRecoverValue))
--         self.Progress_Rescue:SetPercent(Percent/Const.MaxRecoverValue)
--         self.Text_RescueProgress:SetText(GText('BATTLE_RECOVERY_ISHELPING')..math.floor(self.Owner:GetRecoveryPercent())..'%')
--     end
-- end

-- function WBP_Battle_Resurrection_Indicator_PC_C:OnTeammateRecovery(TargetEid)
--     self.Teammate = Battle(self):GetEntity(TargetEid)
--     if self.Owner.Eid == TargetEid and not self.Owner:IsMainPlayer() then
--         if (self:IsExistTimer("RefreshTeammateRecoverIndicator")) then
--             self:RemoveTimer("RefreshTeammateRecoverIndicator")
--         end        
--         if self.Teammate:IsPhantom() then 
--             -- UIManager(self):LoadUI(UIConst.COMMONSCREENTOAST, "CommonScreenToast", UIConst.ZORDER_FOR_COMMON_TIP, 'Phantom ' .. Tip, 1.5)
--             UIManager(self):ShowUITip_BattleCommonTop(UIConst.Tip_CommonTop, 'BATTLE_RECOVERY_TEAMMATERECOVERY')
--         elseif self.Teammate:IsPlayer() then
--             local GameState = UE4.UGameplayStatics.GetGameState(self)
--             for key,value in pairs(GameState.PlayerArray) do
--                 if value == self.Teammate.PlayerState then
--                     -- UIManager(self):LoadUI(UIConst.COMMONSCREENTOAST, "CommonScreenToast", UIConst.ZORDER_FOR_COMMON_TIP, 'Player'..key..Tip, 1.5)
--                     UIManager(self):ShowUITip(UIConst.Tip_CommonTop, string.format(GText("BATTLE_RECOVERY_TEAMMATERECOVERY"), self.Teammate:GetNickName()))
--                 end
--             end
--         end
--         self.RootWidget:SetRenderOpacity(0.0)
--         self.RootWidget:SetVisibility(UE4.ESlateVisibility.Collapsed)
    
--         if self.Teammate:IsPhantom() and IsValid(self.Teammate.BillBoardComponent) then
--             local UIStyleNodeName = nil
--             if self.Owner.Data.BloodUIParmas then UIStyleNodeName = self.Owner.Data.BloodUIParmas.UIStyleNodeName end
--             self.Teammate:InitMonsterBillBoard(self.Teammate, "Monster", UIStyleNodeName)
--         end
--     end
-- end



-- return WBP_Battle_Resurrection_Indicator_PC_C