---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jinyi.li.
--- DateTime: 2026/1/23 15:29
---

local TestClass = require "BluePrints.DungeonObject.Replication.TestClass"
local TestClass2 = require "BluePrints.DungeonObject.Replication.TestClass2"
local Player = require "BluePrints.DungeonObject.Entity.Player"

return {
    TestClass = TestClass,
    TestClass2 = TestClass2,
    Player = Player,
}
